force-app/main/default/objects/ConstructionZone__c/ConstructionZone__c.object-meta.xml
<CustomObject>
    <label>工事区分</label>
    <nameField>
        <label>工区名称</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/ConstructionZone__c/fields/ConstructionZoneNo__c.field-meta.xml
<CustomField>
    <fullName>ConstructionZoneNo__c</fullName>
    <label>工区No</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ConstructionZone__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>工事区分</relationshipLabel>
    <relationshipName>ConstructionZones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/ConstructionZone__c.field-meta.xml
<CustomField>
    <fullName>ConstructionZone__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>工区</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>対象の見積に属さない工事区分を選択しています。
選択し直してください。</errorMessage>
        <filterItems>
            <field>$Source.Quote__c</field>
            <operation>equals</operation>
            <valueField>ConstructionZone__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ConstructionZone__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Device_SmallCategory__c.field-meta.xml
<CustomField>
    <fullName>Device_SmallCategory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>細別</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>対象の見積に属さない細別を選択しています。
選択し直してください。</errorMessage>
        <filterItems>
            <field>$Source.Quote__c</field>
            <operation>equals</operation>
            <valueField>Device_SmallCategory__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Device_SmallCategory__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Device_SmallCategories</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/EquipmentCostExistence__c.field-meta.xml
<CustomField>
    <fullName>EquipmentCostExistence__c</fullName>
    <label>国土交通省機器管理費有無</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>あり</fullName>
            </value>
            <value>
                <fullName>なし</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RecordTypeOfQuote__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeOfQuote__c</fullName>
    <label>見積レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/SectionExistence__c.field-meta.xml
<CustomField>
    <fullName>SectionExistence__c</fullName>
    <label>工区有無</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>なし</fullName>
            </value>
            <value>
                <fullName>あり</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device_LargeCategory__c/Device_LargeCategory__c.object-meta.xml
<CustomObject>
    <label>工種</label>
    <nameField>
        <label>工種名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device_LargeCategory__c/fields/ConstructionZone__c.field-meta.xml
<CustomField>
    <fullName>ConstructionZone__c</fullName>
    <label>工区</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>対象の見積に属さない工区を選択しています。
選択し直してください。</errorMessage>
        <filterItems>
            <field>$Source.Quote__c</field>
            <operation>startsWith</operation>
            <valueField>ConstructionZone__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>ConstructionZone__c</referenceTo>
    <relationshipLabel>工種</relationshipLabel>
    <relationshipName>Device_LargeCategorys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device_LargeCategory__c/fields/Device_LargeCategoryNo__c.field-meta.xml
<CustomField>
    <fullName>Device_LargeCategoryNo__c</fullName>
    <label>工種No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_LargeCategory__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>自動計算で入る項目になります。</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>工種</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device_MiddleCategory__c/Device_MiddleCategory__c.object-meta.xml
<CustomObject>
    <label>種別</label>
    <nameField>
        <label>種別名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device_MiddleCategory__c/fields/Device_LargeCategory__c.field-meta.xml
<CustomField>
    <fullName>Device_LargeCategory__c</fullName>
    <label>工種</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>対象の見積に属さない工種を選択しています。
選択し直してください。</errorMessage>
        <filterItems>
            <field>$Source.Quote__c</field>
            <operation>equals</operation>
            <valueField>Device_LargeCategory__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Device_LargeCategory__c</referenceTo>
    <relationshipLabel>種別</relationshipLabel>
    <relationshipName>Device_MiddleCategorys</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device_MiddleCategory__c/fields/Device_MiddleCategoryNo__c.field-meta.xml
<CustomField>
    <fullName>Device_MiddleCategoryNo__c</fullName>
    <label>種別No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_MiddleCategory__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>自動計算で入る項目になります。</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>種別</relationshipLabel>
    <relationshipName>MiddleQuote</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device_SmallCategory__c/Device_SmallCategory__c.object-meta.xml
<CustomObject>
    <label>細別</label>
    <nameField>
        <label>細別名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Device_SmallCategory__c/fields/Device_MiddleCategory__c.field-meta.xml
<CustomField>
    <fullName>Device_MiddleCategory__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>種別</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>対象の見積に属さない種別を選択しています。
選択し直してください。</errorMessage>
        <filterItems>
            <field>$Source.Quote__c</field>
            <operation>equals</operation>
            <valueField>Device_MiddleCategory__c.Quote__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Device_MiddleCategory__c</referenceTo>
    <relationshipLabel>細別</relationshipLabel>
    <relationshipName>Device_SmallCategorys</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device_SmallCategory__c/fields/Device_SmallCategoryNo__c.field-meta.xml
<CustomField>
    <fullName>Device_SmallCategoryNo__c</fullName>
    <label>細別No</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_SmallCategory__c/fields/EquipmentCostExistence__c.field-meta.xml
<CustomField>
    <fullName>EquipmentCostExistence__c</fullName>
    <formula>TEXT(Device_MiddleCategory__r.Device_LargeCategory__r.ConstructionZone__r.Quote__r.EquipmentCostExistence__c )</formula>
    <label>機器管理費有無</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_SmallCategory__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>自動計算で入る項目になります。</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>細別</relationshipLabel>
    <relationshipName>Device_SmallCategorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device_SmallCategory__c/fields/SectionExistence__c.field-meta.xml
<CustomField>
    <fullName>SectionExistence__c</fullName>
    <formula>TEXT(Device_MiddleCategory__r.Device_LargeCategory__r.ConstructionZone__r.Quote__r.SectionExistence__c)</formula>
    <label>工区有無</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/EquipmentCostExistence__c.field-meta.xml
<CustomField>
    <fullName>EquipmentCostExistence__c</fullName>
    <inlineHelpText>機器管理費有無で「あり」を選択した場合は工区有無も選択してください。</inlineHelpText>
    <label>国土交通省機器管理費有無</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>なし</fullName>
                <default>true</default>
                <label>機器管理費なし</label>
            </value>
            <value>
                <fullName>あり</fullName>
                <label>機器管理費あり</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SectionExistence__c.field-meta.xml
<CustomField>
    <fullName>SectionExistence__c</fullName>
    <label>工区有無</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>あり</fullName>
                <label>工区あり</label>
            </value>
            <value>
                <fullName>なし</fullName>
                <default>true</default>
                <label>工区なし</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConstructionZoneTriggerTest.cls
@isTest
private class ConstructionZoneTriggerTest {
    @testSetup
    static void constructionDataCreation() {
        Id recTypeOfficialDemandId = Schema.SObjectType.Quote__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();

        List<Quote__c> qtList = new List<Quote__c>();
        Quote__c quote1 = new Quote__c(
            PowerFrequency__c = '50Hz',
            RecordTypeId = recTypeOfficialDemandId,
            QuoteNumber__c = '1',
            EquipmentCostExistence__c='あり',
            SectionExistence__c='あり'
        );
        qtList.add(quote1);
        
        insert qtList;

        List<ConstructionZone__c> conList = new List<ConstructionZone__c>();
        ConstructionZone__c con = new ConstructionZone__c(
            Name = 'テスト工事区分',    
            Quote__c = quote1.Id,
            ConstructionZoneNo__c = 1    
        );
        conList.add(con);

        insert conList;

        Device_LargeCategory__c largeCategory = new Device_LargeCategory__c(
            Quote__c = quote1.Id,    
            ConstructionZone__c = con.Id,
            Name = '◯◯工事_工種',
            Device_LargeCategoryNo__c = '1'
        );
        insert largeCategory;

        Device_MiddleCategory__c middleCategory = new Device_MiddleCategory__c(
            Quote__c = quote1.Id,    
            Device_LargeCategory__c = largeCategory.Id,
            Name = '◯◯工事_種別',
            Device_MiddleCategoryNo__c = '1'
        );
        insert middleCategory;

        Device_SmallCategory__c smallCategory = new Device_SmallCategory__c(
            Quote__c = quote1.Id,    
            Device_MiddleCategory__c = middleCategory.Id,
            Name = '◯◯工事_細別',
            Device_SmallCategoryNo__c = '1'
        );
        insert smallCategory;
    }

    @IsTest
    private static void equipManageCostCalculationTest_Below14million() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();

        Quote__c updateQt = [SELECT Id FROM Quote__c LIMIT 1];
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];
        Device_SmallCategory__c updateSmallCate = [SELECT Id FROM Device_SmallCategory__c WHERE Name = '◯◯工事_細別' LIMIT 1];

        Device__c dvEX = new Device__c(
            QuoteSpecificationNumber__c = '007',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=14000000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        insert dvEX;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(14000000, AssertCon.MachineUnitAmount__c);
        System.assertEquals(2550800, AssertCon.MachineControlAmount__c);
        System.assertEquals(18.22, AssertCon.MachineControlRate__c);
        System.assertEquals(0, AssertCon.SystemIntegrationFee__c);

    }

    @IsTest
    private static void updateQuoteAndRelatedRecordsTest_Over14million() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();
        
        Quote__c updateQt = [SELECT Id FROM Quote__c LIMIT 1];
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];
        Device_SmallCategory__c updateSmallCate = [SELECT Id FROM Device_SmallCategory__c WHERE Name = '◯◯工事_細別' LIMIT 1];

        Device__c dvEX = new Device__c(
            QuoteSpecificationNumber__c = '007',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=14000001,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        insert dvEX;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(14000001, AssertCon.MachineUnitAmount__c);
        System.assertEquals(2550800.1822, AssertCon.MachineControlAmount__c);
        System.assertEquals(18.22, AssertCon.MachineControlRate__c);
        System.assertEquals(0, AssertCon.SystemIntegrationFee__c);

    }

    @IsTest
    private static void updateQuoteAndRelatedRecordsTest_Below200million() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();
        
        Quote__c updateQt = [SELECT Id FROM Quote__c LIMIT 1];
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];
        Device_SmallCategory__c updateSmallCate = [SELECT Id FROM Device_SmallCategory__c WHERE Name = '◯◯工事_細別' LIMIT 1];

        Device__c dvEX = new Device__c(
            QuoteSpecificationNumber__c = '007',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=200000000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        insert dvEX;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(200000000, AssertCon.MachineUnitAmount__c);
        System.assertEquals(10420000, AssertCon.MachineControlAmount__c);
        System.assertEquals(5.21, AssertCon.MachineControlRate__c);
        System.assertEquals(0, AssertCon.SystemIntegrationFee__c);

    }

    @IsTest
    private static void updateQuoteAndRelatedRecordsTest_Over200million() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();
        
        Quote__c updateQt = [SELECT Id FROM Quote__c LIMIT 1];
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];
        Device_SmallCategory__c updateSmallCate = [SELECT Id FROM Device_SmallCategory__c WHERE Name = '◯◯工事_細別' LIMIT 1];

        Device__c dvEX = new Device__c(
            QuoteSpecificationNumber__c = '007',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=200000001,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        insert dvEX;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(200000001, AssertCon.MachineUnitAmount__c);
        System.assertEquals(10420000.0521, AssertCon.MachineControlAmount__c);
        System.assertEquals(5.21, AssertCon.MachineControlRate__c);
        System.assertEquals(0, AssertCon.SystemIntegrationFee__c);

    }

    @IsTest
    private static void updateQuoteAndRelatedRecordsTest_InSupplies() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();
        
        Quote__c updateQt = [SELECT Id FROM Quote__c LIMIT 1];
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];
        Device_SmallCategory__c updateSmallCate = [SELECT Id FROM Device_SmallCategory__c WHERE Name = '◯◯工事_細別' LIMIT 1];

        List<Device__c> deList = new List<Device__c>();
        Device__c dvEX = new Device__c(
            QuoteSpecificationNumber__c = '007',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=10000000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        deList.add(dvEX);

        Device__c dvEX2 = new Device__c(
            QuoteSpecificationNumber__c = '008',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=10000000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='支給品'
        );
        deList.add(dvEX2);

        Device__c dvEX3 = new Device__c(
            QuoteSpecificationNumber__c = '009',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=5000000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象(製作のみ)'
        );
        deList.add(dvEX3);

        Device__c dvEX4 = new Device__c(
            QuoteSpecificationNumber__c = '010',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='システムインテグレーション費',
            Note__c ='テスト',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=2000000,
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        deList.add(dvEX4);
        insert deList;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(25000000, AssertCon.MachineUnitAmount__c);
        System.assertEquals(1456500, AssertCon.MachineControlAmount__c);
        System.assertEquals(9.71, AssertCon.MachineControlRate__c);
        System.assertEquals(2000000, AssertCon.SystemIntegrationFee__c);

    }

    @IsTest
    private static void updateQuoteAndRelatedRecordsTest_InNotApplicable() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();
        
        Quote__c updateQt = [SELECT Id FROM Quote__c LIMIT 1];
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];
        Device_SmallCategory__c updateSmallCate = [SELECT Id FROM Device_SmallCategory__c WHERE Name = '◯◯工事_細別' LIMIT 1];

        List<Device__c> deList = new List<Device__c>();
        Device__c dvEX = new Device__c(
            QuoteSpecificationNumber__c = '007',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=10000000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象'
        );
        deList.add(dvEX);

        Device__c dvEX2 = new Device__c(
            QuoteSpecificationNumber__c = '008',
            RecordTypeId=recTypeOfficialDemandIdForDevice,
            RecordTypeOfQuote__c='官需',
            Name = '品名',
            MajorClassification__c ='テレメータ装置[国交省本省宛て提出機器単体費]',
            MinorClassification__c='2量型観測局装置',
            Quote__c = updateQt.Id,
            PriceCoefficient__c=1,
            Quantity__c = '1',
            ClientAnswerAmount_free__c=4100000,
            Note__c ='テスト',
            EquipManageCostTarget__c=true,
            ConstructionZone__c = updateCon.Id,
            Device_SmallCategory__c = updateSmallCate.Id,
            QuoteTarget__c='見積対象外'
        );
        deList.add(dvEX2);

        insert deList;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(14100000, AssertCon.MachineUnitAmount__c);
        System.assertEquals(1816000, AssertCon.MachineControlAmount__c);
        System.assertEquals(18.16, AssertCon.MachineControlRate__c);
        System.assertEquals(0, AssertCon.SystemIntegrationFee__c);

    }

    @IsTest
    private static void updateQuoteAndRelatedRecordsTestForNone() {
        Id recTypeOfficialDemandIdForDevice = Schema.SObjectType.Device__c.getRecordTypeInfosByName().get('官需').getRecordTypeId();
        //テスト実行
        Test.startTest();
        constructionDataCreation();
        
        ConstructionZone__c updateCon = [SELECT Id FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        update updateCon;
        
        Test.stopTest();

        ConstructionZone__c AssertCon = [SELECT Id,MachineUnitAmount__c,MachineControlAmount__c,MachineControlRate__c,SystemIntegrationFee__c FROM ConstructionZone__c WHERE Name = 'テスト工事区分' LIMIT 1];

        System.assertEquals(null, AssertCon.MachineUnitAmount__c);
        System.assertEquals(null, AssertCon.MachineControlAmount__c);
        System.assertEquals(null, AssertCon.MachineControlRate__c);
        System.assertEquals(null, AssertCon.SystemIntegrationFee__c);

    }
}