force-app/main/default/objects/CompanyAddress__c/CompanyAddress__c.object-meta.xml
<CustomObject>
    <label>メール送信先</label>
    <nameField>
        <label>メール送信先名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CompanyAddress__c/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>チェックを外した社内送信先はメールの宛先として利用できなくなります</inlineHelpText>
    <label>有効</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CompanyAddress__c/fields/Mail__c.field-meta.xml
<CustomField>
    <fullName>Mail__c</fullName>
    <label>メールアドレス</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/RequestTask__c.object-meta.xml
<CustomObject>
    <label>依頼タスク</label>
    <nameField>
        <label>依頼タスク件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestTask__c/fields/CompanyAddress01__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress01__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社内送信先1</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CompanyAddress__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CompanyAddress__c</referenceTo>
    <relationshipLabel>依頼タスク</relationshipLabel>
    <relationshipName>CompanyAddress_RequestTasks1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/CompanyAddress02__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress02__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社内送信先2</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CompanyAddress__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CompanyAddress__c</referenceTo>
    <relationshipLabel>依頼タスク (社内送信先2)</relationshipLabel>
    <relationshipName>CompanyAddress_RequestTasks2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/CompanyAddress03__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress03__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社内送信先3</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CompanyAddress__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CompanyAddress__c</referenceTo>
    <relationshipLabel>依頼タスク (社内送信先3)</relationshipLabel>
    <relationshipName>CompanyAddress_RequestTasks3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/CompanyAddress04__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress04__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社内送信先4</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CompanyAddress__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CompanyAddress__c</referenceTo>
    <relationshipLabel>依頼タスク (社内送信先4)</relationshipLabel>
    <relationshipName>CompanyAddress_RequestTasks4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/CompanyAddress05__c.field-meta.xml
<CustomField>
    <fullName>CompanyAddress05__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>社内送信先5</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>CompanyAddress__c.IsActive__c</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>CompanyAddress__c</referenceTo>
    <relationshipLabel>依頼タスク (社内送信先5)</relationshipLabel>
    <relationshipName>CompanyAddress_RequestTasks5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>希望回答期限</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>案件</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>依頼タスク</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <defaultValue>$User.Division</defaultValue>
    <label>依頼元</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>本社　通シ</fullName>
            </value>
            <value>
                <fullName>本社　通シ・管理</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ一</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ二</fullName>
            </value>
            <value>
                <fullName>本社　施設</fullName>
            </value>
            <value>
                <fullName>本社　施設・一</fullName>
            </value>
            <value>
                <fullName>本社　施設・二</fullName>
            </value>
            <value>
                <fullName>本社　施設・三</fullName>
            </value>
            <value>
                <fullName>本社　施設・DC</fullName>
            </value>
            <value>
                <fullName>本社　施設・販企</fullName>
            </value>
            <value>
                <fullName>本社　社シ一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・P推</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・二</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・三</fullName>
            </value>
            <value>
                <fullName>本社　社シ二</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・企政</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・建防</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・道路</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・S監</fullName>
            </value>
            <value>
                <fullName>本社　官公</fullName>
            </value>
            <value>
                <fullName>本社　官公・一</fullName>
            </value>
            <value>
                <fullName>本社　官公・二</fullName>
            </value>
            <value>
                <fullName>本社　海Ｆシ</fullName>
            </value>
            <value>
                <fullName>本社　社環計</fullName>
            </value>
            <value>
                <fullName>本社　社環計・企画</fullName>
            </value>
            <value>
                <fullName>本社　社環計・業務</fullName>
            </value>
            <value>
                <fullName>本社　社環計・品証</fullName>
            </value>
            <value>
                <fullName>本社　社環計・輸管</fullName>
            </value>
            <value>
                <fullName>本社　事管推</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/SharePoint_URL__c.field-meta.xml
<CustomField>
    <fullName>SharePoint_URL__c</fullName>
    <label>SharePoint URL</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/SkipRequestApproval__c.field-meta.xml
<CustomField>
    <fullName>SkipRequestApproval__c</fullName>
    <defaultValue>false</defaultValue>
    <label>依頼先の承認省略</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>依頼作成</fullName>
                <default>true</default>
                <label>依頼作成</label>
            </value>
            <value>
                <fullName>自部門承認中</fullName>
            </value>
            <value>
                <fullName>自部門承認済/依頼発信</fullName>
            </value>
            <value>
                <fullName>依頼先対応中</fullName>
            </value>
            <value>
                <fullName>依頼先対応済/依頼完了</fullName>
            </value>
            <value>
                <fullName>一時保存</fullName>
                <isActive>false</isActive>
                <label>一時保存</label>
            </value>
            <value>
                <fullName>完了済</fullName>
                <isActive>false</isActive>
                <label>完了済</label>
            </value>
            <value>
                <fullName>対応中</fullName>
                <isActive>false</isActive>
                <label>対応中</label>
            </value>
            <value>
                <fullName>新規</fullName>
                <isActive>false</isActive>
                <label>新規</label>
            </value>
            <value>
                <fullName>資料変更依頼</fullName>
                <isActive>false</isActive>
                <label>資料変更依頼</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/TaskCategory__c.field-meta.xml
<CustomField>
    <fullName>TaskCategory__c</fullName>
    <label>依頼区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>提案書作成依頼</fullName>
            </value>
            <value>
                <fullName>見積照会</fullName>
            </value>
            <value>
                <fullName>原低依頼</fullName>
            </value>
            <value>
                <fullName>写真撮影依頼</fullName>
            </value>
            <value>
                <fullName>搬入依頼</fullName>
            </value>
            <value>
                <fullName>技派依頼</fullName>
            </value>
            <value>
                <fullName>製作所技術者選定依頼</fullName>
            </value>
            <value>
                <fullName>先行手配依頼</fullName>
            </value>
            <value>
                <fullName>技術者配置依頼</fullName>
            </value>
            <value>
                <fullName>その他依頼</fullName>
                <isActive>false</isActive>
                <label>その他依頼</label>
            </value>
            <value>
                <fullName>仕様承諾通知</fullName>
                <isActive>false</isActive>
                <label>仕様承諾通知</label>
            </value>
            <value>
                <fullName>原低依頼(工事)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(工事)</label>
            </value>
            <value>
                <fullName>原低依頼(製作所)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(製作所)</label>
            </value>
            <value>
                <fullName>図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>図面作成依頼</label>
            </value>
            <value>
                <fullName>完成図書作成依頼</fullName>
                <isActive>false</isActive>
                <label>完成図書作成依頼</label>
            </value>
            <value>
                <fullName>工事コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>工事コスト積算依頼</label>
            </value>
            <value>
                <fullName>工事図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>工事図面作成依頼</label>
            </value>
            <value>
                <fullName>工場立会検査調整</fullName>
                <isActive>false</isActive>
                <label>工場立会検査調整</label>
            </value>
            <value>
                <fullName>搬入調整依頼</fullName>
                <isActive>false</isActive>
                <label>搬入調整依頼</label>
            </value>
            <value>
                <fullName>搬入連絡</fullName>
                <isActive>false</isActive>
                <label>搬入連絡</label>
            </value>
            <value>
                <fullName>施工図作成依頼</fullName>
                <isActive>false</isActive>
                <label>施工図作成依頼</label>
            </value>
            <value>
                <fullName>機器搬入依頼</fullName>
                <isActive>false</isActive>
                <label>機器搬入依頼</label>
            </value>
            <value>
                <fullName>現地作業員調整依頼</fullName>
                <isActive>false</isActive>
                <label>現地作業員調整依頼</label>
            </value>
            <value>
                <fullName>現地試験成績書作成依頼</fullName>
                <isActive>false</isActive>
                <label>現地試験成績書作成依頼</label>
            </value>
            <value>
                <fullName>納入仕様書・竣工図修正依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書・竣工図修正依頼</label>
            </value>
            <value>
                <fullName>納入仕様書作成依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書作成依頼</label>
            </value>
            <value>
                <fullName>納期変更依頼</fullName>
                <isActive>false</isActive>
                <label>納期変更依頼</label>
            </value>
            <value>
                <fullName>製作所コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>製作所コスト積算依頼</label>
            </value>
            <value>
                <fullName>試験要領書作成依頼</fullName>
                <isActive>false</isActive>
                <label>試験要領書作成依頼</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/TaskDetail__c.field-meta.xml
<CustomField>
    <fullName>TaskDetail__c</fullName>
    <description>依頼/変更依頼コメントから依頼コメントに変更_202404</description>
    <label>依頼コメント</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/SendEmailFromRequestTask.cls
public class SendEmailFromRequestTask {

    /**
     * メール送信（社内送信先1～10宛）
     * 以下から呼び出し
     * ・依頼タスクメール送信用フロー(SendEmailFromRequestTask)から起動
     */
    @InvocableMethod(label='Send Email from request Task')
    public static void sendEmails(List<Id> requestTaskIds){
        sendRequestTaskEmails(requestTaskIds);
    }

    /**
     * メール送信
     * @param requestTaskIds 依頼タスクのIDリスト
     */
    public static void sendRequestTaskEmails(List<Id> requestTaskIds){

        //メールテンプレートを取得
        EmailTemplate template = [SELECT Id, Subject, Body, HtmlValue FROM EmailTemplate WHERE name = '依頼タスクメール'];
        System.debug(template.Id);

        for(RequestTask__c req : getRequestTaskRecord(requestTaskIds)){
            // 宛先を取得
            List<String> emailAddresses = new List<String>();
            // 依頼先承認省略の場合は依頼先通知者1～4を追加
            if (req.SkipRequestApproval__c && req.Status__c == '依頼先対応済/依頼完了') {
                emailAddresses.addAll(getRequestNotificationList(req));
            }
            // 社内送信先1～10を追加
            emailAddresses.addAll(getEmailAddressesList(req));

            // 宛先がある場合のみメール送信
            if (emailAddresses.size() > 0) {
                sendEmail(req, emailAddresses, template);
            }
        }
    }

    /**
     * メールを送信する
     */
    public static void SendEmail(RequestTask__c req, List<String> emailAddresses, EmailTemplate template) {

        //依頼タスクコメントの改行を<BR/>に変換
        String taskDetail = '';
        if(req.TaskDetail__c != null) {
            taskDetail = req.TaskDetail__c.replaceAll( '[\\r\\n]+', '<br/>' );
        }

        //文字色が白になってしまうためテキストスタイルを適用
        String ownerName = '<span style="color: black;">'+ req.Owner.Name + '</span>';
        String commentTytle =  '<span style="color: black;">'+ '依頼コメント：' + '</span>';
        String comment =  '<span style="color: black;">'+ taskDetail + '</span>';
        String sharePointTytle =  '<span style="color: black;">'+ 'SharePoint URL：' + '</span>';
        String sharePoint =  '<span style="color: black;">'+ req.SharePoint_URL__c + '</span>';

        //メール本文をカスタム
        String emailSubject =  '「' + String.valueOf(req.Name) + '」が発信されました';
        String emailBody = template.Body;
        emailBody = replaceMessgae(emailBody, '#RequestTaskName#', req.Name);
        emailBody = replaceMessgae(emailBody, '#TaskCategory#', req.TaskCategory__c);
        emailBody = replaceMessgae(emailBody, '#DueDate#', String.valueOf(req.DueDate__c));
        emailBody = replaceMessgae(emailBody, '#OpportunityName#', req.Opportunity__r.Name);
        emailBody = replaceMessgae(emailBody, '#Requester#', String.valueOf(req.Requester__c));
        emailBody = replaceMessgae(emailBody, '#OwnerId#', ownerName);
        emailBody = replaceMessgae(emailBody, '依頼コメント：', commentTytle);
        emailBody = replaceMessgae(emailBody, '#TaskDetail#', comment);
        emailBody = replaceMessgae(emailBody, 'SharePoint URL：', sharePointTytle);
        emailBody = replaceMessgae(emailBody, '#SharepointURL#', sharePoint);
        /*
        emailBody = emailBody.replace('#RequestTaskName#', req.Name);
        emailBody = emailBody.replace('#TaskCategory#', req.TaskCategory__c);
        emailBody = emailBody.replace('#DueDate#', String.valueOf(req.DueDate__c));
        emailBody = emailBody.replace('#OpportunityName#', req.Opportunity__r.Name);
        emailBody = emailBody.replace('#Requester#', String.valueOf(req.Requester__c));
        emailBody = emailBody.replace('#OwnerId#', ownerName);
        emailBody = emailBody.replace('依頼コメント：', commentTytle);
        emailBody = emailBody.replace('#TaskDetail#', comment);
        emailBody = emailBody.replace('SharePoint URL：', sharePointTytle);
        emailBody = emailBody.replace('#SharepointURL#', sharePoint);
        */

        //メールメッセージを設定
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        //mail.setTargetObjectId(requestTaskId);
        mail.setTemplateId(template.Id);
        mail.setSubject(emailSubject);
        mail.setToAddresses(emailAddresses); // 宛先を設定
        mail.setCcAddresses(new List<String>{req.OwnerId}); // CCに所有者を追加
        mail.setHtmlBody(emailBody);

        //メール送信
        try {
            Messaging.sendEmail(new List <Messaging.SingleEmailMessage>{ mail });
            System.debug('メール送信成功');
        } catch (Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'メール送信失敗しました。'));
            System.debug(e.getMessage() + e.getStackTraceString());
            return ;
        }
    }

    /**
     * メール本文のキーワードを置換
     */
    public static String replaceMessgae(String msg, String key, String str) {
        if (str == null) {
            str = '';
        }
        return msg.replace(key, str);
    }

    /**
     * 社内送信先1～10のメールアドレスを取得
     */
    public static List<String> getEmailAddressesList(RequestTask__c req) {
        // 社内送信先のリスト作成（有効な社内送信先のみ送信対象とする）
        List<String> emailAddresses = new List<String>();
        if(req.CompanyAddress01__c != null && req.CompanyAddress01__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress01__r.Mail__c);
        if(req.CompanyAddress02__c != null && req.CompanyAddress02__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress02__r.Mail__c);
        if(req.CompanyAddress03__c != null && req.CompanyAddress03__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress03__r.Mail__c);
        if(req.CompanyAddress04__c != null && req.CompanyAddress04__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress04__r.Mail__c);
        if(req.CompanyAddress05__c != null && req.CompanyAddress05__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress05__r.Mail__c);
        if(req.CompanyAddress06__c != null && req.CompanyAddress06__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress06__r.Mail__c);
        if(req.CompanyAddress07__c != null && req.CompanyAddress07__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress07__r.Mail__c);
        if(req.CompanyAddress08__c != null && req.CompanyAddress08__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress08__r.Mail__c);
        if(req.CompanyAddress09__c != null && req.CompanyAddress09__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress09__r.Mail__c);
        if(req.CompanyAddress10__c != null && req.CompanyAddress10__r.IsActive__c)
            emailAddresses.add(req.CompanyAddress10__r.Mail__c);
        System.debug(emailAddresses);
        return emailAddresses;
    }

    /**
     * 依頼先通知者1～4のメールアドレスを取得
     */
    public static List<String> getRequestNotificationList(RequestTask__c req) {
        // 社内送信先のリスト作成（有効な社内送信先のみ送信対象とする）
        List<String> emailAddresses = new List<String>();
        if(req.RequestNotification1__c != null)
            emailAddresses.add(req.RequestNotification1__c);
        if(req.RequestNotification2__c != null)
            emailAddresses.add(req.RequestNotification2__c);
        if(req.RequestNotification3__c != null)
            emailAddresses.add(req.RequestNotification3__c);
        if(req.RequestNotification4__c != null)
            emailAddresses.add(req.RequestNotification4__c);
        System.debug(emailAddresses);
        return emailAddresses;
    }

    /**
     * 依頼タスクの取得
     */
    public static List<RequestTask__c> getRequestTaskRecord(List<Id> requestTaskIds) {
        return [ SELECT Id
                , Name
                , Status__c
                , TaskCategory__c
                , DueDate__c
                , Requester__c
                , TaskDetail__c
                , CompanyAddress01__r.Mail__c
                , CompanyAddress02__r.Mail__c
                , CompanyAddress03__r.Mail__c
                , CompanyAddress04__r.Mail__c
                , CompanyAddress05__r.Mail__c
                , CompanyAddress06__r.Mail__c
                , CompanyAddress07__r.Mail__c
                , CompanyAddress08__r.Mail__c
                , CompanyAddress09__r.Mail__c
                , CompanyAddress10__r.Mail__c
                , CompanyAddress01__r.IsActive__c
                , CompanyAddress02__r.IsActive__c
                , CompanyAddress03__r.IsActive__c
                , CompanyAddress04__r.IsActive__c
                , CompanyAddress05__r.IsActive__c
                , CompanyAddress06__r.IsActive__c
                , CompanyAddress07__r.IsActive__c
                , CompanyAddress08__r.IsActive__c
                , CompanyAddress09__r.IsActive__c
                , CompanyAddress10__r.IsActive__c
                , SkipRequestApproval__c
                , RequestNotification1__c
                , RequestNotification2__c
                , RequestNotification3__c
                , RequestNotification4__c
                , Opportunity__r.Name
                , OwnerId
                , Owner.Name
                , SharePoint_URL__c
            FROM RequestTask__c
            WHERE Id IN :requestTaskIds];
    }
}