force-app/main/default/objects/RequestTask__c/RequestTask__c.object-meta.xml
<CustomObject>
    <label>依頼タスク</label>
    <nameField>
        <label>依頼タスク件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestTask__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>希望回答期限</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/RequestDestination__c.field-meta.xml
<CustomField>
    <fullName>RequestDestination__c</fullName>
    <label>依頼先</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TaskCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>神電</fullName>
            </value>
            <value>
                <fullName>伊電</fullName>
            </value>
            <value>
                <fullName>配電</fullName>
            </value>
            <value>
                <fullName>プラ建</fullName>
            </value>
            <value>
                <fullName>C電</fullName>
            </value>
            <value>
                <fullName>力電</fullName>
            </value>
            <value>
                <fullName>系電</fullName>
            </value>
            <value>
                <fullName>通電</fullName>
            </value>
            <value>
                <fullName>鎌電</fullName>
            </value>
            <value>
                <fullName>IS統</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
                <isActive>false</isActive>
                <label>その他</label>
            </value>
            <value>
                <fullName>・・・</fullName>
                <isActive>false</isActive>
                <label>・・・</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <defaultValue>$User.Division</defaultValue>
    <label>依頼元</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>本社　通シ</fullName>
            </value>
            <value>
                <fullName>本社　通シ・管理</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ一</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ二</fullName>
            </value>
            <value>
                <fullName>本社　施設</fullName>
            </value>
            <value>
                <fullName>本社　施設・一</fullName>
            </value>
            <value>
                <fullName>本社　施設・二</fullName>
            </value>
            <value>
                <fullName>本社　施設・三</fullName>
            </value>
            <value>
                <fullName>本社　施設・DC</fullName>
            </value>
            <value>
                <fullName>本社　施設・販企</fullName>
            </value>
            <value>
                <fullName>本社　社シ一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・P推</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・二</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・三</fullName>
            </value>
            <value>
                <fullName>本社　社シ二</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・企政</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・建防</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・道路</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・S監</fullName>
            </value>
            <value>
                <fullName>本社　官公</fullName>
            </value>
            <value>
                <fullName>本社　官公・一</fullName>
            </value>
            <value>
                <fullName>本社　官公・二</fullName>
            </value>
            <value>
                <fullName>本社　海Ｆシ</fullName>
            </value>
            <value>
                <fullName>本社　社環計</fullName>
            </value>
            <value>
                <fullName>本社　社環計・企画</fullName>
            </value>
            <value>
                <fullName>本社　社環計・業務</fullName>
            </value>
            <value>
                <fullName>本社　社環計・品証</fullName>
            </value>
            <value>
                <fullName>本社　社環計・輸管</fullName>
            </value>
            <value>
                <fullName>本社　事管推</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/TaskCategory__c.field-meta.xml
<CustomField>
    <fullName>TaskCategory__c</fullName>
    <label>依頼区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>提案書作成依頼</fullName>
            </value>
            <value>
                <fullName>見積照会</fullName>
            </value>
            <value>
                <fullName>原低依頼</fullName>
            </value>
            <value>
                <fullName>写真撮影依頼</fullName>
            </value>
            <value>
                <fullName>搬入依頼</fullName>
            </value>
            <value>
                <fullName>技派依頼</fullName>
            </value>
            <value>
                <fullName>製作所技術者選定依頼</fullName>
            </value>
            <value>
                <fullName>先行手配依頼</fullName>
            </value>
            <value>
                <fullName>技術者配置依頼</fullName>
            </value>
            <value>
                <fullName>その他依頼</fullName>
                <isActive>false</isActive>
                <label>その他依頼</label>
            </value>
            <value>
                <fullName>仕様承諾通知</fullName>
                <isActive>false</isActive>
                <label>仕様承諾通知</label>
            </value>
            <value>
                <fullName>原低依頼(工事)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(工事)</label>
            </value>
            <value>
                <fullName>原低依頼(製作所)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(製作所)</label>
            </value>
            <value>
                <fullName>図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>図面作成依頼</label>
            </value>
            <value>
                <fullName>完成図書作成依頼</fullName>
                <isActive>false</isActive>
                <label>完成図書作成依頼</label>
            </value>
            <value>
                <fullName>工事コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>工事コスト積算依頼</label>
            </value>
            <value>
                <fullName>工事図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>工事図面作成依頼</label>
            </value>
            <value>
                <fullName>工場立会検査調整</fullName>
                <isActive>false</isActive>
                <label>工場立会検査調整</label>
            </value>
            <value>
                <fullName>搬入調整依頼</fullName>
                <isActive>false</isActive>
                <label>搬入調整依頼</label>
            </value>
            <value>
                <fullName>搬入連絡</fullName>
                <isActive>false</isActive>
                <label>搬入連絡</label>
            </value>
            <value>
                <fullName>施工図作成依頼</fullName>
                <isActive>false</isActive>
                <label>施工図作成依頼</label>
            </value>
            <value>
                <fullName>機器搬入依頼</fullName>
                <isActive>false</isActive>
                <label>機器搬入依頼</label>
            </value>
            <value>
                <fullName>現地作業員調整依頼</fullName>
                <isActive>false</isActive>
                <label>現地作業員調整依頼</label>
            </value>
            <value>
                <fullName>現地試験成績書作成依頼</fullName>
                <isActive>false</isActive>
                <label>現地試験成績書作成依頼</label>
            </value>
            <value>
                <fullName>納入仕様書・竣工図修正依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書・竣工図修正依頼</label>
            </value>
            <value>
                <fullName>納入仕様書作成依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書作成依頼</label>
            </value>
            <value>
                <fullName>納期変更依頼</fullName>
                <isActive>false</isActive>
                <label>納期変更依頼</label>
            </value>
            <value>
                <fullName>製作所コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>製作所コスト積算依頼</label>
            </value>
            <value>
                <fullName>試験要領書作成依頼</fullName>
                <isActive>false</isActive>
                <label>試験要領書作成依頼</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SvfOutputLogicTest.cls
@isTest
public with sharing class SvfOutputLogicTest {
    /**
     * @description アクセスートークン取得テスト 200 OK
     */
    @isTest private static void getSvfTokenTest200OK() {
        // preparation
        String result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfTokenHttpCalloutMock(false, 200));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfToken();
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(SvfTokenHttpCalloutMock.TEST_TOKEN, result, 'アクセストークンが不正です。');
        System.assertEquals(false, hasException, '例外が発生しています。');
        System.assertEquals(null, errorMessage, 'エラーメッセージが設定されています。');
    }

    /**
     * @description アクセスートークン取得テスト OK以外の共通メソッド
     * @param responseCode レスポンスとして返却させるコード
     */
    static void getSvfTokenTestNotOK(Integer responseCode) {
        // preparation
        String result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfTokenHttpCalloutMock(false, responseCode));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfToken();
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(null, result, 'アクセストークンが不正です。');
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertEquals('認証時HTTPステータス=' + responseCode, errorMessage, 'エラーメッセージが不正です。');
    }

    /**
     * @description アクセスートークン取得テスト 401 Unauthorized
     */
    @isTest static void getSvfTokenTest401Unauthorized() {
        getSvfTokenTestNotOK(401);
    }

    /**
     * @description アクセスートークン取得テスト 403 Forbidden
     */
    @isTest static void getSvfTokenTest403Forbidden() {
        getSvfTokenTestNotOK(403);
    }

    /**
     * @description アクセスートークン取得テスト 429 Too many Requests
     */
    @isTest static void getSvfTokenTest429TooManyRequests() {
        getSvfTokenTestNotOK(429);
    }

    /**
     * @description アクセスートークン取得テスト 503 Service Unavailable
     */
    @isTest static void getSvfTokenTest503ServiceUnavailable() {
        getSvfTokenTestNotOK(503);
    }

    /**
    * @description アクセスートークン取得テスト 例外
    */
    @isTest static void getSvfTokenTestCalloutException() {
        // preparation
        String result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfTokenHttpCalloutMock(true, null));
        
        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfToken();
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(null, result, 'アクセストークンが不正です。');
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertEquals('通信エラー', errorMessage, 'エラーメッセージが不正です。');
    }

    /**
     * JWTベアラトークン作成テスト
     */
    @isTest
    private static void generateTokenTest(){
        // preparation
        String resultHeader;
        String resultClaims;
        String resultSignature;
        String userName = UserInfo.getUserName();

        // execution
        Test.startTest();
        List<String> resultList = SvfOutputLogic.generateToken().split('\\.');
        resultHeader = EncodingUtil.base64Decode(resultList[0]).toString();
        resultClaims = EncodingUtil.base64Decode(resultList[1]).toString();
        resultSignature = resultList[2];
        Test.stopTest();

        // assertion
        System.assertEquals('{"alg":"RS256"}', resultHeader, 'JWTヘッダーが不正です。');
        System.assert(resultClaims.contains('"iss":"' + SvfOutputLogic.CLIENT_ID), 'JWT要求セットのissフィールドが不正です。');
        System.assert(resultClaims.contains('"sub":"' + userName), 'JWT要求セットのsubフィールドが不正です。');
        System.assert(resultClaims.contains('"exp":"' + SvfOutputLogic.UNIXTIME_1HOUR_AFTER_EXECUTE), 'JWT要求セットのexpフィールドが不正です。');
        System.assert(resultClaims.contains('"userName":"　"'), 'JWT要求セットのuserNameフィールドが不正です。');
        System.assertNotEquals(null, resultSignature, '署名が設定されていません。');
    }

    /**
     * Base64 URL エンコードテスト
     */
    @isTest
    private static void encodeUrlsafeBase64Test(){
        // preparation
        String resultUnsafe;
        String resultSafe;
        Blob testBlob = Blob.valueOf('<base64>? ｖ');

        // execution
        Test.startTest();
        resultUnsafe = EncodingUtil.base64Encode(testBlob);
        resultSafe = SvfOutputLogic.encodeUrlsafeBase64(testBlob);
        Test.stopTest();

        // assertion
        System.assertEquals('PGJhc2U2ND4/IO+9lg==', resultUnsafe, 'Base64エンコード結果が不正です。');
        System.assertEquals('PGJhc2U2ND4_IO-9lg', resultSafe, 'Base64 URL エンコード結果が不正です。');
    }

    /**
     * @description 印刷実行テスト 正常実行共通メソッド
     * @param responseCode レスポンスとして返却させるコード
     */
    private static void execSvfPrintTestSuccess(Integer responseCode) {
        // preparation
        String result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(false, responseCode));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.execSvfPrint(SvfArtifactsHttpCalloutMock.TEST_TOKEN, 'testfile', 'testdata', 'EXCEL');
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(SvfArtifactsHttpCalloutMock.TEST_LOCATION, result, '印刷データ取得URLが不正です。');
        System.assertEquals(false, hasException, '例外が発生しています。');
        System.assertEquals(null, errorMessage, 'エラーメッセージが設定されています。');
    }

    /**
     * @description 印刷実行テスト 202 Accepted
     */
    @isTest static void execSvfPrintTest202Accepted() {
        execSvfPrintTestSuccess(202);
    }

    /**
     * @description 印刷実行テスト 303 See Other
     */
    @isTest static void execSvfPrintTest303SeeOther() {
        execSvfPrintTestSuccess(303);
    }

    /**
     * @description 印刷実行テスト 正常実行以外共通メソッド
     * @param responseCode レスポンスとして返却させるコード
     */
    private static void execSvfPrintTestError(Integer responseCode) {
        // preparation
        String result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(false, responseCode));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.execSvfPrint(SvfArtifactsHttpCalloutMock.TEST_TOKEN, 'testfile', 'testdata', 'EXCEL');
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(null, result, '印刷データ取得URLが不正です。');
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertEquals('印刷実行時HTTPステータス=' + responseCode, errorMessage, 'エラーメッセージが不正です。');
    }

    /**
     * @description 印刷実行テスト 400 Bad Request
     */
    @isTest static void execSvfPrintTest400BadRequest() {
        execSvfPrintTestError(400);
    }

    /**
     * @description 印刷実行テスト 401 Unauthorized
     */
    @isTest static void execSvfPrintTest401Unauthorized() {
        execSvfPrintTestError(401);
    }

    /**
     * @description 印刷実行テスト 403 Forbidden
     */
    @isTest static void execSvfPrintTest403Forbidden() {
        execSvfPrintTestError(403);
    }

    /**
     * @description 印刷実行テスト 429 Too many Requests
     */
    @isTest static void execSvfPrintTestError429TooManyRequests() {
        execSvfPrintTestError(429);
    }

    /**
     * @description 印刷実行テスト 503 Service Unavailable
     */
    @isTest static void execSvfPrintTest503ServiceUnavailable() {
        execSvfPrintTestError(503);
    }


    /*
     * @description 印刷実行テスト 例外
     */
    @isTest private static void execSvfPrintTestException() {
        // preparation
        String result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(true, null));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.execSvfPrint(SvfArtifactsHttpCalloutMock.TEST_TOKEN, 'testfile', 'testdata', 'EXCEL');
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(null, result, '印刷データ取得URLが不正です。');
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertEquals('通信エラー', errorMessage, 'エラーメッセージが不正です。');
    }

    /**
     * HTTPリクエスト作成時の汎用処理（通常）テスト
     */
    @isTest
    private static void writeFormDataTest(){
        // preparation
        String result;

        // execution
        Test.startTest();
        result = SvfOutputLogic.writeFormData('name', 'value');
        Test.stopTest();

        // assertion
        System.assert(result.contains('-------------------------------102852708831426\r\nContent-Disposition: form-data; name="name";\r\n\r\nvalue'), '\r\n');
    }

    /**
     * HTTPリクエスト作成時の汎用処理（ファイル系）テスト
     */
    @isTest
    private static void writeFileDataTest(){
        // preparation
        String result;

        // execution
        Test.startTest();
        result = SvfOutputLogic.writeFileData('name', 'value');
        Test.stopTest();

        // assertion
        System.assert(result.contains('-------------------------------102852708831426\r\nContent-Disposition: form-data; name="name"; filename="Print.csv";\r\nContent-Type: application/octet-stream\r\n\r\nvalue\r\n'), '\r\n');
    }

    /**
     * @description 成果物ダウンロードテスト 200 OK
     */
    @isTest private static void getSvfPrintdataTest200OK() {
        // preparation
        Blob result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(false, 200));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfPrintdata(SvfArtifactsHttpCalloutMock.TEST_TOKEN, SvfArtifactsHttpCalloutMock.TEST_LOCATION);
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(SvfArtifactsHttpCalloutMock.TEST_OUTPUT, result.toString(), '成果物ダウンロード結果が不正です。');
        System.assertEquals(false, hasException, '例外が発生しています。');
        System.assertEquals(null, errorMessage, 'エラーメッセージが設定されています。');
    }

    /**
     * @description 成果物ダウンロードテスト 303 See Other
     */
    @isTest private static void getSvfPrintdataTest303SeeOther() {
        // preparation
        Blob result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(false, 303));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfPrintdata(SvfArtifactsHttpCalloutMock.TEST_TOKEN, SvfArtifactsHttpCalloutMock.TEST_LOCATION);
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(SvfArtifactsHttpCalloutMock.TEST_OUTPUT_REDIRECT, result.toString(), '成果物ダウンロード結果が不正です。');
        System.assertEquals(false, hasException, '例外が発生しています。');
        System.assertEquals(null, errorMessage, 'エラーメッセージが設定されています。');
    }

    /**
     * @description 成果物ダウンロードテスト OK以外共通メソッド
     * @param responseCode レスポンスとして返却させるコード
     */
    private static void getSvfPrintdataTestNotOk(Integer responseCode) {
        // preparation
        Blob result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(false, responseCode));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfPrintdata(SvfArtifactsHttpCalloutMock.TEST_TOKEN, SvfArtifactsHttpCalloutMock.TEST_LOCATION);
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(null, result, '成果物ダウンロード結果が不正です。');
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertEquals('成果物ダウンロード時HTTPステータス=' + responseCode, errorMessage, 'エラーメッセージが不正です。');
    }

    /**
     * @description 成果物ダウンロードテスト 400 Bad Request
     */
    @isTest static void getSvfPrintdataTest400BadRequest() {
        getSvfPrintdataTestNotOk(400);
    }

    /**
     * @description 成果物ダウンロードテスト 401 Unauthorized
     */
    @isTest static void getSvfPrintdataTest401Unauthorized() {
        getSvfPrintdataTestNotOk(401);
    }

    /**
     * @description 成果物ダウンロードテスト 403 Forbidden
     */
    @isTest static void getSvfPrintdataTest403Forbidden() {
        getSvfPrintdataTestNotOk(403);
    }

    /**
     * @description 成果物ダウンロードテスト 404 Not Found
     */
    @isTest static void getSvfPrintdataTest404NotFound() {
        getSvfPrintdataTestNotOk(404);
    }

    /**
     * @description 成果物ダウンロードテスト 408 Request Timeout
     */
    @isTest static void getSvfPrintdataTest408RequestTimeout() {
        getSvfPrintdataTestNotOk(408);
    }

    /**
     * @description 成果物ダウンロードテスト 429 Too many Requests
     */
    @isTest static void getSvfPrintdataTest429TooManyRequests() {
        getSvfPrintdataTestNotOk(429);
    }

    /**
     * @description 成果物ダウンロードテスト 503 Service Unavailable
     */
    @isTest static void getSvfPrintdataTest503ServiceUnavailable() {
        getSvfPrintdataTestNotOk(503);
    }


    /*
    * @description 成果物ダウンロードテスト 例外
    */
    @isTest private static void getSvfPrintdataTestException() {
        // preparation
        Blob result;
        Boolean hasException = false;
        String errorMessage;

        Test.setMock(HttpCalloutMock.class, new SvfArtifactsHttpCalloutMock(true, null));

        // execution
        Test.startTest();
        try {
            result = SvfOutputLogic.getSvfPrintdata(SvfArtifactsHttpCalloutMock.TEST_TOKEN, SvfArtifactsHttpCalloutMock.TEST_LOCATION);
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(null, result, '成果物ダウンロード結果が不正です。');
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertEquals('通信エラー', errorMessage, 'エラーメッセージが不正です。');
    }

    /**
     * コンテンツバージョンレコード登録テスト
     */
    @isTest private static void insertContentVersionTest(){
        // preparation
        Id executedResult;
        Id expectResult;

        // execution
        Test.startTest();
        executedResult = SvfOutputLogic.insertContentVersion('filename', Blob.valueOf('filedata'), 'extension');
        expectResult = [SELECT
                ContentDocumentId
            FROM
                ContentVersion
            WHERE
                ContentLocation = 'S'
                AND PathOnClient = :('filename' + 'extension')
                AND Title = 'filename'
                // field 'VersionData' can not be filtered in a query call
                // AND VersionData = :Blob.valueOf('filedata')
        ].ContentDocumentId;
        Test.stopTest();

        // assertion
        System.assertEquals(expectResult, executedResult, 'コンテンツバージョンレコードが登録できていません。');
    }

    /**
     * コンテンツバージョンレコード登録テスト DML例外
     */
    @isTest private static void insertContentVersionTestDMLException(){
        // preparation
        Id executedResult;
        Boolean hasException = false;
        String errorMessage;
        
        // execution
        Test.startTest();
        try {
            executedResult = SvfOutputLogic.insertContentVersion(null, null, null);
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertNotEquals(null, errorMessage, 'エラーメッセージが設定されています。');
    }

    /**
     * コンテンツドキュメントリンクレコード登録テスト
     */
    @isTest private static void insertContentDocumentLinkTest(){
        // preparation
        ContentDocumentLink cdl;
        RequestTask__c rt = new RequestTask__c(
            TaskCategory__c = '提案書作成依頼'
            , DueDate__c = Date.today()
            , RequestDestination__c = '神電'
            , Requester__c = '本社　施設'
        );
        insert rt;

        ContentVersion cv = new ContentVersion(
            Title = 'test'
            , PathOnClient = 'test'
            , VersionData = Blob.valueOf('test')
        );
        insert cv;
        Id cvid = [SELECT ContentDocumentId FROM ContentVersion WHERE Id = :cv.Id].ContentDocumentId;

        // execution
        Test.startTest();
        SvfOutputLogic.insertContentDocumentLink(rt.Id, cvid);
        cdl = [SELECT
                Id
            FROM
                ContentDocumentLink
            WHERE
                ContentDocumentId = :cvid
                AND LinkedEntityId = :rt.Id
                AND ShareType = 'V'
        ];
        Test.stopTest();

        // assertion
        System.assertNotEquals(null, cdl, 'コンテンツドキュメントリンクレコードが登録できていません。');
    }

    /**
     * コンテンツドキュメントリンクレコード登録テスト DML例外
     */
    @isTest private static void insertContentDocumentLinkTestDMLException(){
        // preparation
        Boolean hasException = false;
        String errorMessage;

        // execution
        Test.startTest();
        try {
            SvfOutputLogic.insertContentDocumentLink(null, null);
        } catch(Exception e) {
            hasException = true;
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assertEquals(true, hasException, '例外が発生していません。');
        System.assertNotEquals(null, errorMessage, 'エラーメッセージが設定されています。');
    }
}