force-app/main/default/objects/RequestTask__c/RequestTask__c.object-meta.xml
<CustomObject>
    <label>依頼タスク</label>
    <nameField>
        <label>依頼タスク件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestTask__c/fields/ApplicantEmail__c.field-meta.xml
<CustomField>
    <fullName>ApplicantEmail__c</fullName>
    <label>申請者のメールアドレス</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/ApprovalPattern__c.field-meta.xml
<CustomField>
    <fullName>ApprovalPattern__c</fullName>
    <label>承認パターン</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>承認者自動設定</fullName>
            </value>
            <value>
                <fullName>承認者手動設定</fullName>
                <default>true</default>
                <label>承認者手動設定</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Approver2__c.field-meta.xml
<CustomField>
    <fullName>Approver2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>自部門承認者2</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestTasks7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Approver3__c.field-meta.xml
<CustomField>
    <fullName>Approver3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>自部門承認者3</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestTasks8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Approver4__c.field-meta.xml
<CustomField>
    <fullName>Approver4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>自部門承認者4</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestTasks9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Approver5__c.field-meta.xml
<CustomField>
    <fullName>Approver5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>承認者5</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestTasks10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/DocumentOutputFlag__c.field-meta.xml
<CustomField>
    <fullName>DocumentOutputFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>帳票出力済みフラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>状況</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>依頼作成</fullName>
                <default>true</default>
                <label>依頼作成</label>
            </value>
            <value>
                <fullName>自部門承認中</fullName>
            </value>
            <value>
                <fullName>自部門承認済/依頼発信</fullName>
            </value>
            <value>
                <fullName>依頼先対応中</fullName>
            </value>
            <value>
                <fullName>依頼先対応済/依頼完了</fullName>
            </value>
            <value>
                <fullName>一時保存</fullName>
                <isActive>false</isActive>
                <label>一時保存</label>
            </value>
            <value>
                <fullName>完了済</fullName>
                <isActive>false</isActive>
                <label>完了済</label>
            </value>
            <value>
                <fullName>対応中</fullName>
                <isActive>false</isActive>
                <label>対応中</label>
            </value>
            <value>
                <fullName>新規</fullName>
                <isActive>false</isActive>
                <label>新規</label>
            </value>
            <value>
                <fullName>資料変更依頼</fullName>
                <isActive>false</isActive>
                <label>資料変更依頼</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/UnapprovedRemindNumber__c.field-meta.xml
<CustomField>
    <fullName>UnapprovedRemindNumber__c</fullName>
    <defaultValue>0</defaultValue>
    <description>承認プロセス内の自動更新でインクリメントし、フローをトリガする。</description>
    <label>未承認アラート番号</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/RequestTaskTriggerHandler.cls
public without sharing class RequestTaskTriggerHandler {

    // 例外発生テスト時のみ使用するフラグ
    public static Boolean errorHappenFlg = false;

    public void isAfterUpdate(List<RequestTask__c> triggerNew, Map<Id, RequestTask__c> triggerOldMap){

        Savepoint sp = Database.setSavepoint();
        try{
            List<Id> targetIdList = new List<Id>();
            for(RequestTask__c rt : triggerNew){
                // 帳票出力時に依頼タスク.帳票出力済みフラグをtrueに更新する場合はレコードロック解除対象としない。
                if(!triggerOldMap.get(rt.Id).DocumentOutputFlag__c && rt.DocumentOutputFlag__c){
                    system.debug('@@帳票出力時に依頼タスク.帳票出力済みフラグをtrueに更新する場合はレコードロック解除対象としない。');
                    continue;
                }
                // 未承認アラート番号が値ありからnullに更新される、かつ更新後のレコード.状況が「」の場合はレコードロック解除対象としない。
                if(triggerOldMap.get(rt.Id).UnapprovedRemindNumber__c != null && rt.UnapprovedRemindNumber__c == null && rt.Status__c == '依頼先対応済/依頼完了'){
                    system.debug('@@未承認アラート番号が値ありからnullに更新される、かつ更新後のレコード.状況が「」の場合はレコードロック解除対象としない。');
                    continue;
                }
                
                if(rt.ApprovalPattern__c == '承認者手動設定' &&
                    (
                        (String.isBlank(rt.Approver2__c) && triggerOldMap.get(rt.Id).UnapprovedRemindNumber__c == 1 && rt.UnapprovedRemindNumber__c == 2) ||
                        (String.isBlank(rt.Approver3__c) && triggerOldMap.get(rt.Id).UnapprovedRemindNumber__c == 2 && rt.UnapprovedRemindNumber__c == 3) ||
                        (String.isBlank(rt.Approver4__c) && triggerOldMap.get(rt.Id).UnapprovedRemindNumber__c == 3 && rt.UnapprovedRemindNumber__c == 4) ||
                        (String.isBlank(rt.Approver5__c) && triggerOldMap.get(rt.Id).UnapprovedRemindNumber__c == 4 && rt.UnapprovedRemindNumber__c == 5)
                    )){
                        system.debug('@@手動設定のときのスキップ');
                        continue;
                }
                // 製作所・プラ建対応: 承認申請時に項目自動更新で依頼タスク.申請者のメールアドレスが入力され、却下/取下時には空白値となる。
                if((String.isBlank(triggerOldMap.get(rt.Id).ApplicantEmail__c) && !String.isBlank(rt.ApplicantEmail__c)) ||
                    (triggerOldMap.get(rt.Id).UnapprovedRemindNumber__c != rt.UnapprovedRemindNumber__c && rt.UnapprovedRemindNumber__c != null && rt.Status__c != '依頼先対応済/依頼完了')){
                        system.debug('@@targetIdListにIDを追加');
                        targetIdList.add(rt.Id);
                }
                system.debug('@@targetIdList: ' + targetIdList);
            }
            if(!targetIdList.isEmpty()){
                doUnlock(targetIdList);
            }
            // テスト実行時、かつ例外発生フラグがtrueのときに例外発生
            if(Test.isRunningTest() && errorHappenFlg){
                throw new  ApprovalProcessException();
            }
        } catch (Exception e){
            Database.rollback(sp);
            triggerNew[0].addError('エラーが発生しました。承認申請を再度実行してください。エラーが繰り返す場合はシステム管理者に連絡してください。', false);
        }
    }

    /**
     * レコードロック解除処理メソッド
     * @param List<Id> targetIdList レコードロック解除処理対象依頼タスクIDリスト
     */
    @future
    private static void doUnlock(List<Id> targetIdList){

        Approval.UnLockResult[] results = Approval.unlock(targetIdList, true);
        System.debug('非同期処理によるロック解除操作の対象件数 = ' + results.size());
    }
}