force-app/main/default/objects/RequestTask__c/RequestTask__c.object-meta.xml
<CustomObject>
    <label>依頼タスク</label>
    <nameField>
        <label>依頼タスク件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestTask__c/fields/CurrentApprover__c.field-meta.xml
<CustomField>
    <fullName>CurrentApprover__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>承認申請が現在割り当てられているユーザを表示</description>
    <label>現在の承認者</label>
    <referenceTo>User</referenceTo>
    <relationshipName>RequestTaskUser</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/UpdateCurrentApproverHandler.cls
public class UpdateCurrentApproverHandler {
    public static void updateApprovalUserOnProcessStart(List<Id> requestTaskIds) {
        List<RequestTask__c> tasksToUpdate = new List<RequestTask__c>();
        RequestTask__c task = [SELECT Id FROM RequestTask__c WHERE Id IN :requestTaskIds];
        List<ProcessInstanceStep> approvalInstances = [Select
                                                        ProcessInstance.ProcessDefinitionId,
                                                        ProcessInstance.TargetobjectId,
                                                        OriginalActor.Name,
                                                        Actor.Id
                                                        FROM ProcessInstanceStep
                                                        WHERE ProcessInstance.TargetobjectId =: requestTaskIds LIMIT 1
                                                        ];

        for (ProcessInstanceStep instance : approvalInstances) {
            task.CurrentApprover__c = instance.Actor.Id;
            tasksToUpdate.add(task);
        }
        if (!tasksToUpdate.isEmpty()) {
            update tasksToUpdate;
        }
    }
}