force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ConstructionDistinction__c.field-meta.xml
<CustomField>
    <fullName>ConstructionDistinction__c</fullName>
    <label>工事区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新設</fullName>
            </value>
            <value>
                <fullName>更新（自社既設）</fullName>
            </value>
            <value>
                <fullName>更新（他社既設）</fullName>
            </value>
            <value>
                <fullName>更新（蓄電池）</fullName>
            </value>
            <value>
                <fullName>増設</fullName>
            </value>
            <value>
                <fullName>修繕・改造</fullName>
            </value>
            <value>
                <fullName>保守</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>新設（建屋新設）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋新設）</label>
            </value>
            <value>
                <fullName>新設（建屋既存）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋既存）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EstablishedCompany__c.field-meta.xml
<CustomField>
    <fullName>EstablishedCompany__c</fullName>
    <label>既設社</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>ConstructionDistinction__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>三菱</fullName>
            </value>
            <value>
                <fullName>日立</fullName>
            </value>
            <value>
                <fullName>東芝</fullName>
            </value>
            <value>
                <fullName>富士電機</fullName>
            </value>
            <value>
                <fullName>明電舎</fullName>
            </value>
            <value>
                <fullName>日新電機</fullName>
            </value>
            <value>
                <fullName>東光高岳</fullName>
            </value>
            <value>
                <fullName>安川電機</fullName>
            </value>
            <value>
                <fullName>シンフォニア</fullName>
            </value>
            <value>
                <fullName>メタウォーター</fullName>
            </value>
            <value>
                <fullName>横河電機</fullName>
            </value>
            <value>
                <fullName>GSユアサ</fullName>
            </value>
            <value>
                <fullName>ヤンマー</fullName>
            </value>
            <value>
                <fullName>川崎重工業</fullName>
            </value>
            <value>
                <fullName>IHI原動機</fullName>
            </value>
            <value>
                <fullName>アズビル</fullName>
            </value>
            <value>
                <fullName>ジョンソンコントロールズ</fullName>
            </value>
            <value>
                <fullName>パナソニック</fullName>
            </value>
            <value>
                <fullName>ソニー</fullName>
            </value>
            <value>
                <fullName>ダクトロニクス</fullName>
            </value>
            <value>
                <fullName>JRC</fullName>
            </value>
            <value>
                <fullName>富士通</fullName>
            </value>
            <value>
                <fullName>NEC</fullName>
            </value>
            <value>
                <fullName>国際電気</fullName>
            </value>
            <value>
                <fullName>荏原電産</fullName>
            </value>
            <value>
                <fullName>愛知時計</fullName>
            </value>
            <value>
                <fullName>沖電気工業</fullName>
            </value>
            <value>
                <fullName>コイト</fullName>
            </value>
            <value>
                <fullName>名古屋電機工業</fullName>
            </value>
            <value>
                <fullName>星和電機</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの案件をコピーする場合は注意してください</inlineHelpText>
    <label>案件</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>見積</relationshipLabel>
    <relationshipName>Quotations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>件名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/RedirectToParentQuoteTest.cls
@isTest
public class RedirectToParentQuoteTest {

    @isTest
    static void success(){
        Date dt = Date.today();
        Opportunity opp = new Opportunity(
            Name = 'TestOpportunity1'
            ,StageName = '基本計画'
            ,ConstructionDistinction__c = '更新（自社既設）'
            ,EstablishedCompany__c = '三菱'
            ,CloseDate = dt
        );
        insert opp;
        Quote__c qu = new Quote__c(
            QuoteNumber__c = 'Test01'
            ,Opportunity__c = opp.Id
            ,Subject__c = 'Test用'
            ,PowerFrequency__c = '50Hz'
        );
        insert qu;
        List<Device__c> deList = new List<Device__c>();
        for(Integer i = 0; i < 10; i++){
            Device__c de = new Device__c(
                Name = 'Test' + i
                ,QuoteSpecificationNumber__c = '0' + i
                ,Quote__c = qu.Id
                ,MajorClassification__c = '特高'
            );
            deList.add(de);
        }
        insert deList;
        List<RedirectToParentQuote.Parameter> rpList = new List<RedirectToParentQuote.Parameter>();
        RedirectToParentQuote.Parameter rp = new RedirectToParentQuote.Parameter();
        rp.input_ParentRecordId = deList[0].Quote__c;
        rpList.add(rp);

        Test.startTest();
        RedirectToParentQuote.RedirectTo(rpList);
        Test.stopTest();
    }

    @isTest
    static void failed(){
        Date dt = Date.today();
        Opportunity opp = new Opportunity(
            Name = 'TestOpportunity1'
            ,StageName = '基本計画'
            ,ConstructionDistinction__c = '更新（自社既設）'
            ,EstablishedCompany__c = '三菱'
            ,CloseDate = dt
        );
        insert opp;
        Quote__c qu = new Quote__c(
            QuoteNumber__c = 'Test01'
            ,Opportunity__c = opp.Id
            ,Subject__c = 'Test用'
            ,PowerFrequency__c = '50Hz'
        );
        insert qu;
        List<Device__c> deList = new List<Device__c>();
        for(Integer i = 0; i < 10; i++){
            Device__c de = new Device__c(
                Name = 'Test' + i
                ,QuoteSpecificationNumber__c = '0' + i
                ,Quote__c = qu.Id
                ,MajorClassification__c = '特高'
            );
            deList.add(de);
        }
        insert deList;
        List<RedirectToParentQuote.Parameter> rpList = new List<RedirectToParentQuote.Parameter>();
        RedirectToParentQuote.Parameter rp = new RedirectToParentQuote.Parameter();
        rp.input_ParentRecordId = null;
        rpList.add(rp);

        Test.startTest();
        RedirectToParentQuote.RedirectTo(rpList);
        Test.stopTest();
    }
}