force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/RedirectToParentQuote2.cls
global virtual class RedirectToParentQuote2 {

    @RemoteAction
    global static void RedirectTo(String recordId){
        Device__c d = [SELECT Id, Quote__c from Device__c WHERE Id =:recordId];
        String parentId = d.Quote__c;
        String redirectUrl = URL.getOrgDomainURL().toExternalForm() + '/' + parentId;
        RedirectoToRecordPage(redirectUrl);
    }

    @AuraEnabled
    global static void RedirectoToRecordPage(String url){
        PageReference pageRef = new PageReference(url);
        System.Aura.redirect(pageRef);
    }

}