force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <formula>IF( GeneralAdminExpensesExistence__c ,PriceSum__c *  GeneralAdministrativeExpensesCopy__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般管理費</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <defaultValue>1</defaultValue>
    <label>価格係数</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <defaultValue>IF ($RecordType.Name = &quot;施設&quot;, &quot;0&quot;, &quot;&quot;)</defaultValue>
    <label>一般管理費率</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeviceCloneControllerTest.cls
@isTest
private class DeviceCloneControllerTest {

    @isTest
    static void testExecuteMethodSuccess() {
        // テスト用の見積を作成
        Quote__c testQuote = new Quote__c();
        testQuote.QuoteNumber__c= '1';
        testQuote.GeneralAdministrativeExpenses__c = '10';
        testQuote.PowerFrequency__c = '50Hz';
        insert testQuote;

        // テスト用の見積項目を作成
        List<Device__c> testDevices = new List<Device__c>();
        for (Integer i = 0; i < 2; i++) {
            Device__c device = new Device__c();
            device.Name = '見積項目 ' + i;
            device.QuoteSpecificationNumber__c = 'Test'+i;
            device.MajorClassification__c = '高圧受配電盤';
            device.PriceCoefficient__c = 1.00;
            device.Quote__c = testQuote.Id;
            testDevices.add(device);
        }
        insert testDevices;
        System.debug('testDevices= '+testDevices);
        System.debug('testQuote= '+testQuote);

        // テスト見積項目のための標準セットコントローラを作成
        ApexPages.StandardSetController setController = new ApexPages.StandardSetController(testDevices);
        setController.setSelected(testDevices);

        // コントローラーのインスタンス化
        DeviceCloneController controller = new DeviceCloneController(setController);
        // copySetを有効な値に設定
        controller.copySet = '1';

        // executeメソッドを呼び出す
    Test.startTest();
    PageReference result = controller.execute();
    Test.stopTest();

    // 実行後の見積項目IDを取得
    List<Device__c> copiedDevices = [SELECT Id FROM Device__c WHERE QuoteSpecificationNumber__c LIKE '%_コピー%'];
    System.debug('copiedDevices='+copiedDevices);
    
    // アサーション
    System.assertEquals(testDevices.size() * Integer.valueOf(controller.copySet), copiedDevices.size());
    }

    @isTest
    static void testExecuteMethodWithInvalidInput() {
        // テスト用の見積もりを作成
        Quote__c testQuote = new Quote__c();
        testQuote.QuoteNumber__c= '1';
        testQuote.GeneralAdministrativeExpenses__c = '10';
        testQuote.PowerFrequency__c = '50Hz';
        insert testQuote;

        // テスト用の見積項目を作成
        List<Device__c> testDevices = new List<Device__c>();
        for (Integer i = 0; i < 2; i++) {
            Device__c device = new Device__c();
            device.Name = '見積項目 ' + i;
            device.QuoteSpecificationNumber__c = 'Test'+i;
            device.MajorClassification__c = '高圧受配電盤';
            device.PriceCoefficient__c = 1.00;
            device.Quote__c = testQuote.Id;
            testDevices.add(device);
        }
        insert testDevices;

        // テスト見積項目のための標準セットコントローラを作成
        ApexPages.StandardSetController setController = new ApexPages.StandardSetController(testDevices);
        setController.setSelected(testDevices);

        // コントローラのインスタンスを作成
        DeviceCloneController controller = new DeviceCloneController(setController);

        // copySetを無効な値に設定
        controller.copySet = '0';

        // executeメソッドを呼び出す
        Test.startTest();
        PageReference result = controller.execute();
        Test.stopTest();

        // エラーメッセージが設定されたことをアサート
        System.assertNotEquals(null, controller.errorMessage);
        // 実行が失敗したことをアサート（resultがnullであること）
        System.assertEquals(null, result);
    }
}