force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <formula>IF( GeneralAdminExpensesExistence__c ,PriceSum__c *  GeneralAdministrativeExpensesCopy__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般管理費</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MinorClassification__c.field-meta.xml
<CustomField>
    <fullName>MinorClassification__c</fullName>
    <label>小分類名</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MajorClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>66kV C-GIS</fullName>
            </value>
            <value>
                <fullName>22kV C-GIS</fullName>
            </value>
            <value>
                <fullName>ブロック(気中)キュービクル</fullName>
            </value>
            <value>
                <fullName>特高監視盤</fullName>
            </value>
            <value>
                <fullName>特高変圧器</fullName>
            </value>
            <value>
                <fullName>高圧変圧器</fullName>
            </value>
            <value>
                <fullName>変圧器収納盤</fullName>
            </value>
            <value>
                <fullName>バスダクト</fullName>
            </value>
            <value>
                <fullName>高圧コンビ盤</fullName>
            </value>
            <value>
                <fullName>高圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧盤</fullName>
            </value>
            <value>
                <fullName>現場盤</fullName>
            </value>
            <value>
                <fullName>リレー盤</fullName>
            </value>
            <value>
                <fullName>ACB盤</fullName>
            </value>
            <value>
                <fullName>200V</fullName>
            </value>
            <value>
                <fullName>400V</fullName>
            </value>
            <value>
                <fullName>共通</fullName>
            </value>
            <value>
                <fullName>3.0kV/3.3kV</fullName>
            </value>
            <value>
                <fullName>6.0kV/6.6kV</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>計装盤</fullName>
            </value>
            <value>
                <fullName>記録計</fullName>
            </value>
            <value>
                <fullName>ラック･パネル計器</fullName>
            </value>
            <value>
                <fullName>流量計</fullName>
            </value>
            <value>
                <fullName>水位計</fullName>
            </value>
            <value>
                <fullName>濃度計</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ACG</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量（数量×合計の計算式有り）</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RecordTypeOfQuote__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeOfQuote__c</fullName>
    <label>見積レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <defaultValue>IF ($RecordType.Name = &quot;施設&quot;, &quot;0&quot;, &quot;&quot;)</defaultValue>
    <label>一般管理費率</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DeviceTriggerTest.cls
@isTest
private class DeviceTriggerTest {
    @isTest
    private static void convertFullToHalfTest(){
        //事前準備
        List<RecordType> recType_Quote = [SELECT Id FROM RecordType WHERE SobjectType = 'Quote__c' and name = '施設'];
        List<Quote__c> qList = new List<Quote__c>();
        Quote__c quote = new Quote__c(
            QuoteNumber__c = '見積_事前準備',
            GeneralAdministrativeExpenses__c = '1',
            PowerFrequency__c = '50Hz',
            RecordTypeId = recType_Quote[0].Id
        );
        qList.add(quote);
        insert qList;

        List<Device__c> dList = new List<Device__c>();
        List<RecordType> recType_Device = [SELECT Id FROM RecordType WHERE SobjectType = 'Device__c' and name = '施設'];
        //数量が半角の場合
        Device__c d1 = new Device__c(
            Name = '全角入力テスト_半角ver',
            QuoteSpecificationNumber__c = '001',
            Quantity__c = '1',//半角数字
            Quote__c = quote.Id,
            RecordTypeOfQuote__c = '施設',
            MajorClassification__c = '変圧器',
            MinorClassification__c = '',
            RecordTypeId = recType_Device[0].Id
        );
        dList.add(d1);
        //数量が全角の場合
        Device__c d2 = new Device__c(
            Name = '全角入力テスト_全角ver',
            QuoteSpecificationNumber__c = '002',
            Quantity__c = '１',//全角数字
            Quote__c = quote.Id,
            RecordTypeOfQuote__c = '施設',
            MajorClassification__c = '変圧器',
            MinorClassification__c = '',
            RecordTypeId = recType_Device[0].Id
        );
        dList.add(d2);
        //数量が半角・全角複合の場合
        Device__c d3 = new Device__c(
            Name = '全角入力テスト_半角全角複合ver',
            QuoteSpecificationNumber__c = '003',
            Quantity__c = '1２',//半角数字、全角数字複合
            Quote__c = quote.Id,
            RecordTypeOfQuote__c = '施設',
            MajorClassification__c = '変圧器',
            MinorClassification__c = '',
            RecordTypeId = recType_Device[0].Id
        );
        dList.add(d3);
        //数量が空白の場合
        Device__c d4 = new Device__c(
            Name = '全角入力テスト_空白ver',
            QuoteSpecificationNumber__c = '004',
            Quantity__c = '',//空白
            Quote__c = quote.Id,
            RecordTypeOfQuote__c = '施設',
            MajorClassification__c = '変圧器',
            MinorClassification__c = '',
            RecordTypeId = recType_Device[0].Id
        );
        dList.add(d4);
        //テスト実行
        Test.startTest();

        insert dList;

        Test.stopTest();

        List<Device__c> dResult1 = [SELECT Id
                                        , Name
                                        , QuoteSpecificationNumber__c
                                        , Quantity__c
                                        FROM Device__c WHERE Id = :d1.Id];
        List<Device__c> dResult2 = [SELECT Id
                                        , Name
                                        , QuoteSpecificationNumber__c
                                        , Quantity__c
                                        FROM Device__c WHERE Id = :d2.Id];
        List<Device__c> dResult3 = [SELECT Id
                                        , Name
                                        , QuoteSpecificationNumber__c
                                        , Quantity__c
                                        FROM Device__c WHERE Id = :d3.Id];

        List<Device__c> dResult4 = [SELECT Id
                                        , Name
                                        , QuoteSpecificationNumber__c
                                        , Quantity__c
                                        FROM Device__c WHERE Id = :d4.Id];

        System.assertEquals('1', dResult1[0].Quantity__c);
        System.assertEquals('1', dResult2[0].Quantity__c);
        System.assertEquals('12', dResult3[0].Quantity__c);
        System.assertEquals(null, dResult4[0].Quantity__c);

    }
}