force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MinorClassification__c.field-meta.xml
<CustomField>
    <fullName>MinorClassification__c</fullName>
    <label>小分類名</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MajorClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>66kV C-GIS</fullName>
            </value>
            <value>
                <fullName>22kV C-GIS</fullName>
            </value>
            <value>
                <fullName>ブロック(気中)キュービクル</fullName>
            </value>
            <value>
                <fullName>特高監視盤</fullName>
            </value>
            <value>
                <fullName>特高変圧器</fullName>
            </value>
            <value>
                <fullName>高圧変圧器</fullName>
            </value>
            <value>
                <fullName>変圧器収納盤</fullName>
            </value>
            <value>
                <fullName>バスダクト</fullName>
            </value>
            <value>
                <fullName>高圧コンビ盤</fullName>
            </value>
            <value>
                <fullName>高圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧盤</fullName>
            </value>
            <value>
                <fullName>現場盤</fullName>
            </value>
            <value>
                <fullName>リレー盤</fullName>
            </value>
            <value>
                <fullName>ACB盤</fullName>
            </value>
            <value>
                <fullName>200V</fullName>
            </value>
            <value>
                <fullName>400V</fullName>
            </value>
            <value>
                <fullName>共通</fullName>
            </value>
            <value>
                <fullName>3.0kV/3.3kV</fullName>
            </value>
            <value>
                <fullName>6.0kV/6.6kV</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>計装盤</fullName>
            </value>
            <value>
                <fullName>記録計</fullName>
            </value>
            <value>
                <fullName>ラック･パネル計器</fullName>
            </value>
            <value>
                <fullName>流量計</fullName>
            </value>
            <value>
                <fullName>水位計</fullName>
            </value>
            <value>
                <fullName>濃度計</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ACG</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>機器事業部 低圧コンデンサ/リアクトル</fullName>
                <isActive>false</isActive>
                <label>機器事業部 低圧コンデンサ/リアクトル</label>
            </value>
            <value>
                <fullName>機器事業部 変圧器</fullName>
                <isActive>false</isActive>
                <label>機器事業部 変圧器</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RecordTypeOfQuote__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeOfQuote__c</fullName>
    <label>見積レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/PricingTable__c.object-meta.xml
<CustomObject>
    <label>価格表</label>
    <nameField>
        <displayFormat>K-{00000000}</displayFormat>
        <label>価格表番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PricingTable__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>S：施設、M：水環境、K：官需</description>
    <inlineHelpText>S：施設、M：水環境、K：官需</inlineHelpText>
    <label>BU</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>種類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/CategoryName__c.field-meta.xml
<CustomField>
    <fullName>CategoryName__c</fullName>
    <label>種類名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>周波数</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MajorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationCode__c</fullName>
    <label>大分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MajorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationName__c</fullName>
    <label>大分類名</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MasterCode__c.field-meta.xml
<CustomField>
    <fullName>MasterCode__c</fullName>
    <externalId>true</externalId>
    <label>マスタコード</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MinorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationCode__c</fullName>
    <label>小分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MinorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationName__c</fullName>
    <label>小分類名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name3__c.field-meta.xml
<CustomField>
    <fullName>Name3__c</fullName>
    <label>名称3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name4__c.field-meta.xml
<CustomField>
    <fullName>Name4__c</fullName>
    <description>既存マスタに109文字のデータが存在するため名称4のみ最大文字数を拡張</description>
    <label>名称4</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name7__c.field-meta.xml
<CustomField>
    <fullName>Name7__c</fullName>
    <label>名称7</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name8__c.field-meta.xml
<CustomField>
    <fullName>Name8__c</fullName>
    <label>名称8</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/RECNo__c.field-meta.xml
<CustomField>
    <fullName>RECNo__c</fullName>
    <label>RECNo</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/WC__c.field-meta.xml
<CustomField>
    <fullName>WC__c</fullName>
    <label>WC単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/WcCalculationRate__c.field-meta.xml
<CustomField>
    <fullName>WcCalculationRate__c</fullName>
    <label>WC算出レート</label>
    <precision>2</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DetailControllerTest.cls
/**
 * 明細入力A画面コントローラーのテスト
 */
@isTest
public with sharing class DetailControllerTest {
    private static final String RECORDTYPE_NAME_DETAIL = '明細';
    private static final String RECORDTYPE_NAME_CHSSIS = '筐体';
    private static final String Frequency_50Hz = '50Hz';
    private static final String Frequency_60Hz = '60Hz';
    private static final String CATEGORYCODE_50Hz = '01';
    private static final String CATEGORYCODE_60Hz = '02';
    private static final List<String> BU_LIST = new List<String>{'S','K','M'};

    private static Quote__c quote;//見積
    private static Device__c dv;//見積項目
    private static List<PricingTable__c> tables;

    //価格表データ作成
    private static void createDate(String qRtName,String major, String minor, String powerFrequency){
        List<RecordType> recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Quote__c' and name = :qRtName];
        List<RecordType> dvType = [SELECT Id FROM RecordType WHERE SobjectType = 'Device__c' and name = :qRtName];

        quote = new Quote__c(
            QuoteNumber__c = '1',
            PowerFrequency__c = powerFrequency,
            RecordTypeId = recType[0].Id
        );
        insert quote;

        dv = new Device__c(
            // QuoteSpecificationNumber__c = '001',
            Name = qRtName+ major,
            RecordTypeOfQuote__c = qRtName,
            MajorClassification__c = major,
            MinorClassification__c = minor,
            Quote__c =quote.Id,
            RecordTypeId = dvType[0].Id
        );
        insert dv;

        // レコードタイプ（価格表）取得
        Map<String, Id> pricingRecordTypeByName = new Map<String, Id>();
        for (RecordType rt : [SELECT Id,Name FROM RecordType WHERE SobjectType = 'PricingTable__c']) {
            pricingRecordTypeByName.put(rt.Name, rt.Id);
        }
        tables = new List<PricingTable__c>();
        Integer index = 1;
        for (String bu: BU_LIST){
            for (String rtName  : pricingRecordTypeByName.keyset()) {
                Id rtId = pricingRecordTypeByName.get(rtName);
                // 価格表
                PricingTable__c table = new PricingTable__c(
                    RecordTypeId = rtId 
                    , BU__c = bu
                    , MajorClassificationCode__c = '01'
                    , MajorClassificationName__c = major
                    , MinorClassificationCode__c = '11'
                    , MinorClassificationName__c = minor
                    , CategoryCode__c = (powerFrequency==Frequency_60Hz?'02':'01')
                    , Frequency__c = powerFrequency
                    , Name1__c = 'Name1'
                    , Name2__c = 'Name2'
                    , Name3__c = 'Name3'
                    , Name4__c = 'Name4'
                    , Name5__c = 'Name5'
                    , Name6__c = 'Name6'
                    , Name7__c = 'Name7'
                    , Name8__c = 'Name8'
                    , Name9__c = 'Name9'
                    , MasterCode__c = 'MasterCode'
                    , RECNo__c = index
                );
                index = index + 1;
                tables.add(table);
                if (rtName == RECORDTYPE_NAME_CHSSIS) {
                    PricingTable__c table03 = new PricingTable__c(
                        RecordTypeId = rtId
                        , BU__c = bu
                        , MajorClassificationCode__c = '01'
                        , MajorClassificationName__c = major
                        , MinorClassificationCode__c = '11'
                        , MinorClassificationName__c = '変圧器収納盤'
                        , CategoryCode__c = '00'
                        , CategoryName__c ='変圧器収納盤'
                        , Frequency__c = powerFrequency
                        , Name1__c = '変圧器収納盤(高圧)'
                        , Name2__c = 'Name2'
                        , Name3__c = 'Name3'
                        , Name4__c = 'Name4'
                        , Name5__c = 'Name5'
                        , Name6__c = 'Name6'
                        , Name7__c = 'Name7'
                        , Name8__c = 'Name8'
                        , Name9__c = 'Name9'
                        , WC__c = 1
                        , WcCalculationRate__c = 1
                        , MasterCode__c = 'MasterCode'
                        , RECNo__c = 9
                    );
                tables.add(table03);
                }
            }
        }
        if (tables.size() > 0) insert tables;
    }
    //変圧器　パターン
    @isTest static void picklistTest1() {
        String qRtName='施設';
        String major='変圧器';
        String minor='機器事業部 変圧器';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
            //ラベル設定
            Map<String, List<Map<String, String>>> initMap =  DetailController.getUniqueNamePicklist(dv.Id,'');

            //ラベル設定
            Map<String, List<Map<String, String>>> nameChangedMap =  DetailController.getUniqueNamePicklist(dv.Id,'Name1');
        Test.stopTest();

        System.assertEquals(9, initMap.get('label').size());
        System.assertNotEquals(null, initMap.get('name1'));
        System.assertNotEquals(null, initMap.get('board1'));
        System.assertNotEquals(null, initMap.get('board2'));
        // System.assertNotEquals(null, initMap.get('board3'));
        // System.assertNotEquals(null, initMap.get('board4'));
        System.assertEquals(0, initMap.get('name2').size());
        System.assertEquals(0, initMap.get('name3').size());
        System.assertEquals(0, initMap.get('name4').size());
        System.assertEquals(0, initMap.get('name5').size());
        System.assertEquals(0, initMap.get('name6').size());

        System.assertEquals(9, nameChangedMap.get('label').size());
        System.assertNotEquals(null, nameChangedMap.get('name1'));
        System.assertNotEquals(null, nameChangedMap.get('name2'));
        System.assertNotEquals(null, nameChangedMap.get('name3'));
        System.assertNotEquals(null, nameChangedMap.get('name4'));
        System.assertNotEquals(null, nameChangedMap.get('name5'));
        System.assertNotEquals(null, nameChangedMap.get('name6'));

    }
    //名称９まで取得
    @isTest static void picklistTest2_1() {
        String qRtName='施設';
        String major='進相コンデンサ/リアクトル';
        String minor='機器事業部 低圧コンデンサ/リアクトル';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);
        Test.startTest();
            //ラベル設定
            Map<String, List<Map<String, String>>> initMap =  DetailController.getUniqueNamePicklist(dv.Id,'');            //ラベル設定
            Map<String, List<Map<String, String>>> nameChangedMap =  DetailController.getUniqueNamePicklist(dv.Id,'Name1');
        Test.stopTest();

        System.assertEquals(10, initMap.get('label').size());
        System.assertEquals(10, nameChangedMap.get('label').size());

    }
    //MELFLEX
    @isTest static void picklistTest2_2() {
        String qRtName='官需';
        String major='MELFLEX';
        String minor='';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);
        Test.startTest();
            //ラベル設定
            Map<String, List<Map<String, String>>> initMap =  DetailController.getUniqueNamePicklist(dv.Id,'');
        Test.stopTest();

        System.assertEquals(7, initMap.get('label').size());

    }
    //MACTUS
    @isTest static void picklistTest2() {
        String qRtName='水環境';
        String major='MACTUS';
        String minor='OPS';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);
        Test.startTest();
            //ラベル設定
            Map<String, List<Map<String, String>>> initMap =  DetailController.getUniqueNamePicklist(dv.Id,'');
        Test.stopTest();

        System.assertEquals(10, initMap.get('label').size());
        System.assertNotEquals(null, initMap.get('metadata1'));

    }

    //明細に既存がなし　基本パターン１
    @isTest static void searchTest1() {
        String qRtName='施設';
        String major='変圧器';
        String minor='特高変圧器';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        DetailController.PricingTableInputOnly intensify = new DetailController.PricingTableInputOnly();
        DetailController.PricingTableInputOnly  newIntensify = new DetailController.PricingTableInputOnly();
        intensify.Id = tables.get(0).Id;
        intensify.Quantity = 1;
        intensify.WCCoefficient = 1;
        intensify.CreditWC = 1;
        intensify.UnitPriceCoefficient = 1;
        intensify.ProvisionUnitPrice = 1;
        intensify.UnitWeight = 1;
        DetailController.PricingTableNewRowObj newRow = new DetailController.PricingTableNewRowObj();
        newRow.isCreate  =true;
        newRow.Id = '1rowIndex1';
        newRow.Name1 = 'Name1'; //名称１
        newRow.Name2  = 'Name2'; ///名称２
        newRow.Name3  = 'Name3'; ///名称３
        newRow.CreditWC = 1; //単位WC ※入力
        newRow.WCCoefficient = 1; //WC係数※入力
        newRow.UnitPrice = 1;//単価
        newRow.UnitPriceCoefficient = 1; //単価係数※入力
        newRow.ProvisionUnitPrice = 1; //提供単価※入力
        newRow.UnitWeight = 1; //単位重量
        newRow.Quantity = 1; //数量※入力
        newRow.WC  = 1;//WC
        newRow.Price = 1; //価格
        newRow.ProvisionPrice = 1; //提供価格
        newRow.Weight = 1; //重量
        newRow.Note = '備考';//備考
        newRow.Name4 = 'Name4';//名称４
    
        newIntensify.Id = newRow.Id;
        newIntensify.Quantity = newRow.Quantity;
        newIntensify.WCCoefficient = newRow.WCCoefficient;
        newIntensify.CreditWC = newRow.CreditWC;
        newIntensify.UnitPriceCoefficient = newRow.UnitPriceCoefficient;
        newIntensify.ProvisionUnitPrice = newRow.ProvisionUnitPrice;
        newIntensify.UnitWeight = newRow.UnitWeight;
        List<DetailController.PricingTableInputOnly> intensifyRecords 
                        = new List<DetailController.PricingTableInputOnly>{intensify,newIntensify};
        List<DetailController.PricingTableNewRowObj> newRowRecords 
                = new List<DetailController.PricingTableNewRowObj>{newRow};

        List<String> specificationNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> boardNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> searchCodes = new List<String>{'MasterCode'};
        List<String> searchName = new List<String>{'Name'};
        
        Map<String, List<String>>  searchConditions = new Map<String, List<String>>();

        Test.startTest();
        //ラベル設定
        Map<String, List<Map<String, String>>> labelMap =  DetailController.getUniqueNamePicklist(dv.Id,'');

        //初期検索
        String rtnStr1 =  DetailController.getPricingTableRecords(
                                '',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                '',
                                ''
                                );
        //画面条件指定
        searchConditions.put('specificationNames',specificationNames);
        searchConditions.put('boardNames',boardNames);
        //仕様検索
        String rtnStr2 =  DetailController.getPricingTableRecords(
                                'SpecSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchCodes',searchCodes);
        //コード検索
        String rtnStr3 =  DetailController.getPricingTableRecords(
                                'CodeSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchName',searchName);
        //名称検索
        String rtnStr4 =  DetailController.getPricingTableRecords(
                                'NameSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        //集約対象を検索する
        String rtnStr5 =  DetailController.getPricingTableByintensify(
            JSON.serialize(intensifyRecords),
            JSON.serialize(newRowRecords));

        //登録処理
       String rtnStr6 =  DetailController.setDetail(
                JSON.serialize(intensifyRecords),
                JSON.serialize(newRowRecords),
                '',
                dv.Id,
                true);
        Test.stopTest();

        System.assertNotEquals(null, rtnStr1);
        System.assertNotEquals(null, rtnStr2);
        System.assertNotEquals(null, rtnStr3);
        System.assertNotEquals(null, rtnStr4);
        System.assertNotEquals(null, rtnStr5);
        System.assertEquals(String.valueof(quote.Id), rtnStr6);


    }
    //明細に既存が存在　
    @isTest static void searchTest2() {
        String qRtName='施設';
        String major='変圧器';
        String minor='特高変圧器';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        DetailController.PricingTableInputOnly intensify = new DetailController.PricingTableInputOnly();

        intensify.Id = tables.get(0).Id;
        intensify.Quantity = 1;
        intensify.WCCoefficient = 1;
        intensify.CreditWC = 1;
        intensify.UnitPriceCoefficient = 1;
        intensify.ProvisionUnitPrice = 1;
        intensify.UnitWeight = 1;
        DetailController.PricingTableNewRowObj newRow = new DetailController.PricingTableNewRowObj();
        DetailController.PricingTableInputOnly newIntensify = new DetailController.PricingTableInputOnly();
        newRow.isCreate  =true;
        newRow.Id = '1rowIndex1';
        newRow.Name1 = 'Name1'; //名称１
        newRow.Name2  = 'Name2'; ///名称２
        newRow.Name3  = 'Name3'; ///名称３
        newRow.CreditWC = 1; //単位WC ※入力
        newRow.WCCoefficient = 1; //WC係数※入力
        newRow.UnitPrice = 1;//単価
        newRow.UnitPriceCoefficient = 1; //単価係数※入力
        newRow.ProvisionUnitPrice = 1; //提供単価※入力
        newRow.UnitWeight = 1; //単位重量
        newRow.Quantity = 1; //数量※入力
        newRow.WC  = 1;//WC
        newRow.Price = 1; //価格
        newRow.ProvisionPrice = 1; //提供価格
        newRow.Weight = 1; //重量
        newRow.Note = '備考';//備考
        newRow.Name4 = 'Name4';//名称４

        newIntensify.Id = newRow.Id;
        newIntensify.Quantity = newRow.Quantity;
        newIntensify.WCCoefficient = newRow.WCCoefficient;
        newIntensify.CreditWC = newRow.CreditWC;
        newIntensify.UnitPriceCoefficient = newRow.UnitPriceCoefficient;
        newIntensify.ProvisionUnitPrice = newRow.ProvisionUnitPrice;
        newIntensify.UnitWeight = newRow.UnitWeight;
        List<DetailController.PricingTableInputOnly> intensifyRecords 
                        = new List<DetailController.PricingTableInputOnly>{intensify,newIntensify};
        List<DetailController.PricingTableNewRowObj> newRowRecords 
                = new List<DetailController.PricingTableNewRowObj>{newRow};

        List<String> specificationNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> boardNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> searchCodes = new List<String>{'MasterCode'};
        List<String> searchName = new List<String>{'Name'};
        
        Map<String, List<String>>  searchConditions = new Map<String, List<String>>();

        Test.startTest();
        //登録処理
        String rtnStr6 =  DetailController.setDetail(
                            JSON.serialize(intensifyRecords),
                            JSON.serialize(newRowRecords),
                            '',
                            dv.Id,
                            true);

        //初期検索
        String rtnStr1 =  DetailController.getPricingTableRecords(
                                '',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                '',
                                ''
                                );
        //画面条件指定
        searchConditions.put('specificationNames',specificationNames);
        searchConditions.put('boardNames',boardNames);
        //仕様検索
        String rtnStr2 =  DetailController.getPricingTableRecords(
                                'SpecSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchCodes',searchCodes);
        //コード検索
        String rtnStr3 =  DetailController.getPricingTableRecords(
                                'CodeSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchName',searchName);
        //名称検索
        String rtnStr4 =  DetailController.getPricingTableRecords(
                                'NameSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        //集約対象を検索する
        String rtnStr5 =  DetailController.getPricingTableByintensify(
            JSON.serialize(intensifyRecords),
            JSON.serialize(newRowRecords));

        Test.stopTest();
        System.assertNotEquals(null, rtnStr1);
        System.assertNotEquals(null, rtnStr2);
        System.assertNotEquals(null, rtnStr3);
        System.assertNotEquals(null, rtnStr4);
        System.assertNotEquals(null, rtnStr5);
        System.assertEquals(String.valueof(quote.Id), rtnStr6);
    }

    //MACTUS 明細に既存が存在　
    @isTest static void searchTest3() {
        String qRtName='水環境';
        String major='MACTUS';
        String minor='OPS';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        DetailController.PricingTableInputOnly intensify = new DetailController.PricingTableInputOnly();

        intensify.Id = tables.get(0).Id;
        intensify.Quantity = 1;
        intensify.WCCoefficient = 1;
        intensify.CreditWC = 1;
        intensify.UnitPriceCoefficient = 1;
        intensify.ProvisionUnitPrice = 1;
        intensify.UnitWeight = 1;
        DetailController.PricingTableNewRowObj newRow = new DetailController.PricingTableNewRowObj();
        DetailController.PricingTableInputOnly newIntensify = new DetailController.PricingTableInputOnly();
        newRow.isCreate  =true;
        newRow.Id = '1rowIndex1';
        newRow.Name1 = 'Name1'; //名称１
        newRow.Name2  = 'Name2'; ///名称２
        newRow.Name3  = 'Name3'; ///名称３
        newRow.CreditWC = 1; //単位WC ※入力
        newRow.WCCoefficient = 1; //WC係数※入力
        newRow.UnitPrice = 1;//単価
        newRow.UnitPriceCoefficient = 1; //単価係数※入力
        newRow.ProvisionUnitPrice = 1; //提供単価※入力
        newRow.UnitWeight = 1; //単位重量
        newRow.Quantity = 1; //数量※入力
        newRow.WC  = 1;//WC
        newRow.Price = 1; //価格
        newRow.ProvisionPrice = 1; //提供価格
        newRow.Weight = 1; //重量
        newRow.Note = '備考';//備考
        newRow.Name4 = 'Name4';//名称４

        newIntensify.Id = newRow.Id;
        newIntensify.Quantity = newRow.Quantity;
        newIntensify.WCCoefficient = newRow.WCCoefficient;
        newIntensify.CreditWC = newRow.CreditWC;
        newIntensify.UnitPriceCoefficient = newRow.UnitPriceCoefficient;
        newIntensify.ProvisionUnitPrice = newRow.ProvisionUnitPrice;
        newIntensify.UnitWeight = newRow.UnitWeight;
        List<DetailController.PricingTableInputOnly> intensifyRecords 
                        = new List<DetailController.PricingTableInputOnly>{intensify,newIntensify};
        List<DetailController.PricingTableNewRowObj> newRowRecords 
                = new List<DetailController.PricingTableNewRowObj>{newRow};



        DetailController.HeaderMetaData deta = new DetailController.HeaderMetaData();
        deta.meta1 = 'Web';
        deta.meta2 = '1台';
        deta.meta3 = 'meta3';
        deta.meta4 = 'meta4';
        deta.meta5 = 'meta5';
        deta.meta6 = 'meta6';
        deta.meta7 = 'meta7';
        deta.meta8 = 'meta8';
        deta.meta9 = 'meta9';

        List<String> specificationNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> boardNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> searchCodes = new List<String>{'MasterCode'};
        List<String> searchName = new List<String>{'Name'};
        
        Map<String, List<String>>  searchConditions = new Map<String, List<String>>();

        
        Test.startTest();
        //登録処理
        String rtnStr6 =  DetailController.setDetail(
                            JSON.serialize(intensifyRecords),
                            JSON.serialize(newRowRecords),
                            JSON.serialize(deta),
                            dv.Id,
                            true);

        //初期検索
        String rtnStr1 =  DetailController.getPricingTableRecords(
                                '',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                '',
                                ''
                                );
        //画面条件指定
        searchConditions.put('specificationNames',specificationNames);
        searchConditions.put('boardNames',boardNames);
        //仕様検索
        String rtnStr2 =  DetailController.getPricingTableRecords(
                                'SpecSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchCodes',searchCodes);
        //コード検索
        String rtnStr3 =  DetailController.getPricingTableRecords(
                                'CodeSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchName',searchName);
        //名称検索
        String rtnStr4 =  DetailController.getPricingTableRecords(
                                'NameSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        //集約対象を検索する
        String rtnStr5 =  DetailController.getPricingTableByintensify(
            JSON.serialize(intensifyRecords),
            JSON.serialize(newRowRecords));

        Test.stopTest();
        System.assertNotEquals(null, rtnStr1);
        System.assertNotEquals(null, rtnStr2);
        System.assertNotEquals(null, rtnStr3);
        System.assertNotEquals(null, rtnStr4);
        System.assertNotEquals(null, rtnStr5);
        System.assertEquals(String.valueof(quote.Id), rtnStr6);
    }

    //明細に既存が存在　
    @isTest static void searchTest2_1() {
        String qRtName='施設';
        String major='変圧器';
        String minor='機器事業部 変圧器';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        DetailController.PricingTableInputOnly intensify = new DetailController.PricingTableInputOnly();

        intensify.Id = tables.get(0).Id;
        intensify.Quantity = 1;
        intensify.WCCoefficient = 1;
        intensify.CreditWC = 1;
        intensify.UnitPriceCoefficient = 1;
        intensify.ProvisionUnitPrice = 1;
        intensify.UnitWeight = 1;
        DetailController.PricingTableNewRowObj newRow = new DetailController.PricingTableNewRowObj();
        DetailController.PricingTableInputOnly newIntensify = new DetailController.PricingTableInputOnly();
        newRow.isCreate  =true;
        newRow.Id = '1rowIndex1';
        newRow.Name1 = 'Name1'; //名称１
        newRow.Name2  = 'Name2'; ///名称２
        newRow.Name3  = 'Name3'; ///名称３
        newRow.CreditWC = 1; //単位WC ※入力
        newRow.WCCoefficient = 1; //WC係数※入力
        newRow.UnitPrice = 1;//単価
        newRow.UnitPriceCoefficient = 1; //単価係数※入力
        newRow.ProvisionUnitPrice = 1; //提供単価※入力
        newRow.UnitWeight = 1; //単位重量
        newRow.Quantity = 1; //数量※入力
        newRow.WC  = 1;//WC
        newRow.Price = 1; //価格
        newRow.ProvisionPrice = 1; //提供価格
        newRow.Weight = 1; //重量
        newRow.Note = '備考';//備考
        newRow.Name4 = 'Name4';//名称４

        newIntensify.Id = newRow.Id;
        newIntensify.Quantity = newRow.Quantity;
        newIntensify.WCCoefficient = newRow.WCCoefficient;
        newIntensify.CreditWC = newRow.CreditWC;
        newIntensify.UnitPriceCoefficient = newRow.UnitPriceCoefficient;
        newIntensify.ProvisionUnitPrice = newRow.ProvisionUnitPrice;
        newIntensify.UnitWeight = newRow.UnitWeight;
        List<DetailController.PricingTableInputOnly> intensifyRecords 
                        = new List<DetailController.PricingTableInputOnly>{intensify,newIntensify};
        List<DetailController.PricingTableNewRowObj> newRowRecords 
                = new List<DetailController.PricingTableNewRowObj>{newRow};

        List<String> specificationNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> boardNames = new List<String>{'Name1','Name2','Name3','Name4'};
        List<String> searchCodes = new List<String>{'MasterCode'};
        List<String> searchName = new List<String>{'Name'};
        
        Map<String, List<String>>  searchConditions = new Map<String, List<String>>();

        Test.startTest();
        //登録処理
        String rtnStr6 =  DetailController.setDetail(
                            JSON.serialize(intensifyRecords),
                            JSON.serialize(newRowRecords),
                            '',
                            dv.Id,
                            true);

        //初期検索
        String rtnStr1 =  DetailController.getPricingTableRecords(
                                '',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                '',
                                ''
                                );
        //画面条件指定
        searchConditions.put('specificationNames',specificationNames);
        searchConditions.put('boardNames',boardNames);
        //仕様検索
        String rtnStr2 =  DetailController.getPricingTableRecords(
                                'SpecSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchCodes',searchCodes);
        //コード検索
        String rtnStr3 =  DetailController.getPricingTableRecords(
                                'CodeSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        searchConditions.put('searchName',searchName);
        //名称検索
        String rtnStr4 =  DetailController.getPricingTableRecords(
                                'NameSearch',
                                dv.Id,
                                200, 
                                1,
                                searchConditions,
                                JSON.serialize(intensifyRecords),
                                JSON.serialize(newRowRecords)
                                );
        //集約対象を検索する
        String rtnStr5 =  DetailController.getPricingTableByintensify(
            JSON.serialize(intensifyRecords),
            JSON.serialize(newRowRecords));

        Test.stopTest();
        System.assertNotEquals(null, rtnStr1);
        System.assertNotEquals(null, rtnStr2);
        System.assertNotEquals(null, rtnStr3);
        System.assertNotEquals(null, rtnStr4);
        System.assertNotEquals(null, rtnStr5);
        System.assertEquals(String.valueof(quote.Id), rtnStr6);
    }




}