force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MinorClassification__c.field-meta.xml
<CustomField>
    <fullName>MinorClassification__c</fullName>
    <label>小分類名</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MajorClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>66kV C-GIS</fullName>
            </value>
            <value>
                <fullName>22kV C-GIS</fullName>
            </value>
            <value>
                <fullName>ブロック(気中)キュービクル</fullName>
            </value>
            <value>
                <fullName>特高監視盤</fullName>
            </value>
            <value>
                <fullName>特高変圧器</fullName>
            </value>
            <value>
                <fullName>高圧変圧器</fullName>
            </value>
            <value>
                <fullName>変圧器収納盤</fullName>
            </value>
            <value>
                <fullName>バスダクト</fullName>
            </value>
            <value>
                <fullName>高圧コンビ盤</fullName>
            </value>
            <value>
                <fullName>高圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧盤</fullName>
            </value>
            <value>
                <fullName>現場盤</fullName>
            </value>
            <value>
                <fullName>リレー盤</fullName>
            </value>
            <value>
                <fullName>ACB盤</fullName>
            </value>
            <value>
                <fullName>200V</fullName>
            </value>
            <value>
                <fullName>400V</fullName>
            </value>
            <value>
                <fullName>共通</fullName>
            </value>
            <value>
                <fullName>3.0kV/3.3kV</fullName>
            </value>
            <value>
                <fullName>6.0kV/6.6kV</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>計装盤</fullName>
            </value>
            <value>
                <fullName>記録計</fullName>
            </value>
            <value>
                <fullName>ラック･パネル計器</fullName>
            </value>
            <value>
                <fullName>流量計</fullName>
            </value>
            <value>
                <fullName>水位計</fullName>
            </value>
            <value>
                <fullName>濃度計</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ACG</fullName>
            </value>
            <value>
                <fullName>屋内</fullName>
            </value>
            <value>
                <fullName>屋外</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RecordTypeOfQuote__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeOfQuote__c</fullName>
    <label>見積レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/PricingTable__c.object-meta.xml
<CustomObject>
    <label>価格表</label>
    <nameField>
        <displayFormat>K-{00000000}</displayFormat>
        <label>価格表番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PricingTable__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>S：施設、M：水環境、K：官需</description>
    <inlineHelpText>S：施設、M：水環境、K：官需</inlineHelpText>
    <label>BU</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/CategoryName__c.field-meta.xml
<CustomField>
    <fullName>CategoryName__c</fullName>
    <label>種類名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/DisplayName__c.field-meta.xml
<CustomField>
    <fullName>DisplayName__c</fullName>
    <label>表示用テキスト</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>周波数</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MajorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationName__c</fullName>
    <label>大分類名</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MasterCode__c.field-meta.xml
<CustomField>
    <fullName>MasterCode__c</fullName>
    <externalId>true</externalId>
    <label>マスタコード</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MinorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationCode__c</fullName>
    <label>小分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MinorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationName__c</fullName>
    <label>小分類名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name10__c.field-meta.xml
<CustomField>
    <fullName>Name10__c</fullName>
    <label>名称10</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name3__c.field-meta.xml
<CustomField>
    <fullName>Name3__c</fullName>
    <label>名称3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name4__c.field-meta.xml
<CustomField>
    <fullName>Name4__c</fullName>
    <description>既存マスタに109文字のデータが存在するため名称4のみ最大文字数を拡張</description>
    <label>名称4</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name7__c.field-meta.xml
<CustomField>
    <fullName>Name7__c</fullName>
    <label>名称7</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name8__c.field-meta.xml
<CustomField>
    <fullName>Name8__c</fullName>
    <label>名称8</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/RECNo__c.field-meta.xml
<CustomField>
    <fullName>RECNo__c</fullName>
    <label>RECNo</label>
    <precision>4</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/RECNOforRelayBoardB_Attachment__c.field-meta.xml
<CustomField>
    <fullName>RECNOforRelayBoardB_Attachment__c</fullName>
    <label>リレー盤B画面用RECNO</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DetailsInputForRelayBoardTest.cls
/**
 * 明細入力B画面_リレー盤のコントローラーのテスト
 */

@isTest
private class DetailsInputForRelayBoardTest {
    private static final String RECORDTYPE_NAME_DETAIL = '明細';
    private static final String RECORDTYPE_NAME_CHSSIS = '筐体';
    private static final String Frequency_50Hz = '50Hz';
    private static final String Frequency_60Hz = '60Hz';
    private static final List<String> BU_LIST = new List<String>{'S','K','M'};

    private static Quote__c quote;//見積
    private static Device__c dv;//見積項目
    private static List<PricingTable__c> tables;

    //価格表データ作成
    private static void createDate(String qRtName){
        List<RecordType> recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Quote__c' and name = :qRtName];
        List<RecordType> dvType = [SELECT Id FROM RecordType WHERE SobjectType = 'Device__c' and name = :qRtName];

        quote = new Quote__c(
            QuoteNumber__c = '1',
            PowerFrequency__c = Frequency_60Hz,
            RecordTypeId = recType[0].Id
        );
        insert quote;

        dv = new Device__c(
            QuoteSpecificationNumber__c = '001',
            Name = qRtName+'DeviceTest',
            RecordTypeOfQuote__c = qRtName,
            MajorClassification__c = '低圧・現場・リレー・ACB盤',
            MinorClassification__c = 'リレー盤',
            Quote__c =quote.Id,
            RecordTypeId = dvType[0].Id
        );
        insert dv;

        // レコードタイプ（価格表）取得
        Map<String, Id> pricingRecordTypeByName = new Map<String, Id>();
        for (RecordType rt : [SELECT Id,Name FROM RecordType WHERE SobjectType = 'PricingTable__c']) {
            pricingRecordTypeByName.put(rt.Name, rt.Id);
        }
        tables = new List<PricingTable__c>();
        List<String> lst = new List<String>{'100','200','300'};
        Map<String,List<String>> commonDetails = new Map<String,List<String>>{
            // 大分類名「共通機器」かつ、低圧盤B画面取付器具類用RECNOがnull以外
            'RECNO'=>new List<String>{'1'}
        };
        // 大分類名「低圧・現場・リレー・ACB盤」かつ、小分類名「低圧盤」
        Integer index = 1;
        for (String bu: BU_LIST){
            //筐体
            for (String namex : lst) {
                // 価格表
                PricingTable__c table = new PricingTable__c(
                    RecordTypeId = pricingRecordTypeByName.get('筐体') 
                    , BU__c = bu
                    , MajorClassificationName__c = '低圧・現場・リレー・ACB盤'
                    , MinorClassificationCode__c = '11'
                    , MinorClassificationName__c = '低圧盤'
                    , Frequency__c = Frequency_60Hz
                    , DisplayName__c = 'TEST'
                    , Name1__c = (bu=='S'?'屋内':'低圧盤　屋内')
                    , Name2__c = '自立SS'
                    , Name3__c = namex
                    , Name4__c = namex
                    , Name5__c = namex
                    , Name6__c = '観音開き'
                    , Name7__c = '7'
                    , Name8__c = '8'
                    , Name9__c = '9'
                    , MasterCode__c = 'MasterCode'
                    , RECNo__c = index
                );
                index = index + 1;
                tables.add(table);
            }
            PricingTable__c table_Special = new PricingTable__c(
                RecordTypeId = pricingRecordTypeByName.get('筐体') 
                , BU__c = bu
                , MajorClassificationName__c = '低圧・現場・リレー・ACB盤'
                , MinorClassificationCode__c = '11'
                , MinorClassificationName__c = '低圧盤'
                , Frequency__c = Frequency_60Hz
                , DisplayName__c = 'Test'
                , Name1__c = (bu=='S'?'屋内':'低圧盤　屋内')
                , Name2__c = '自立SS'
                , Name3__c = '800W'
                , Name4__c = '2,300H'
                , Name5__c = '600D'
                , Name6__c = '観音開き'
                , Name7__c = '7'
                , Name8__c = '8'
                , Name9__c = '9'
                , MasterCode__c = 'MasterCode'
                , RECNo__c = index
                , Price__c = 9999
            );
            index = index + 1;
            tables.add(table_Special);
            for(String mapKey:commonDetails.keySet()){
                List<String> keys = commonDetails.get(mapKey);
                for (String key:keys){
                    // 価格表
                    PricingTable__c table = new PricingTable__c(
                        RecordTypeId = pricingRecordTypeByName.get('明細') 
                        , BU__c = bu
                        , MajorClassificationName__c = '共通機器'
                        , MinorClassificationName__c = 'minor'
                        , Frequency__c = Frequency_60Hz
                        , CategoryName__c = Frequency_60Hz
                        , DisplayName__c = '配線材料費'
                        , Name1__c = (mapKey=='name1'?key:'name1Test')
                        , Name2__c = '自立SS'
                        , Name3__c = '3333333'
                        , Name4__c = '4444444'
                        , Name5__c = '5555555'
                        , Name6__c = '観音開き'
                        , Name7__c = '777777'
                        , Name8__c = '888888'
                        , Name9__c = (mapKey=='name9'?key:'name9est')
                        , Name10__c = (mapKey=='name10'?key:'name10est')
                        , RECNOforRelayBoardB_Attachment__c = (mapKey=='RECNO'?Decimal.valueof(key):null)
                        , MasterCode__c = 'MasterCode'
                        , RECNo__c = index
                    );
                    index = index + 1;
                    tables.add(table);
                }
            }
            for(String mapKey:commonDetails.keySet()){
                List<String> keys = commonDetails.get(mapKey);
                for (String key:keys){
                    // 価格表
                    PricingTable__c table_detail = new PricingTable__c(
                        RecordTypeId = pricingRecordTypeByName.get('明細') 
                        , BU__c = bu
                        , MajorClassificationName__c = '共通機器'
                        , MinorClassificationName__c = 'minor'
                        , Frequency__c = Frequency_60Hz
                        , CategoryName__c = Frequency_60Hz
                        , DisplayName__c = 'TEST01'
                        , Name1__c = (mapKey=='name1'?key:'name1Test')
                        , Name2__c = '自立SS'
                        , Name3__c = '3333333'
                        , Name4__c = '4444444'
                        , Name5__c = '5555555'
                        , Name6__c = '観音開き'
                        , Name7__c = '777777'
                        , Name8__c = '888888'
                        , Name9__c = (mapKey=='name9'?key:'name9est')
                        , Name10__c = (mapKey=='name10'?key:'name10est')
                        , RECNOforRelayBoardB_Attachment__c = (mapKey=='RECNO'?Decimal.valueof(key):null)
                        , MasterCode__c = 'MasterCode'
                        , RECNo__c = index
                    );
                    index = index + 1;
                    tables.add(table_detail);
                }
            }
        }
        if (tables.size() > 0) insert tables;
    }

    /**
     *内訳入力B_低圧配電盤 画面情報を取得 施設テスト
     * 
     */
    @isTest static void getInitScreenInfoSTest() {
        String qRtName='施設';
        createDate(qRtName);

        Test.startTest();
        String rtn = DetailsInputForRelayBoardController.getInitScreenInfo(true,
                                            dv.Id,
                                            '屋内',
                                            '自立SS',
                                            '観音開き');
        Test.stopTest();
        System.assertNotEquals(rtn, null);//
        Map<String, Object> jsonDes = (Map<String, Object>)JSON.deserializeUntyped(rtn);
        Map<String, Object> auxiliaryRelayTable= (Map<String, Object>)jsonDes.get('auxiliaryRelayTable'); //補助継電器盤標準筐体
        List<Object> tbls = (List<Object>)jsonDes.get('classicTables');//メイン一覧ヘッダー
        Map<String, Object> installEquipTypeTable= (Map<String, Object>)jsonDes.get('installEquipTypeTable'); //取付器具類

        System.assertEquals(jsonDes.size()>0, true);
        System.assertEquals(auxiliaryRelayTable.size()>0, true);
        System.assertEquals(tbls.size()>0, true);
        System.assertEquals(installEquipTypeTable.size()>0, true);
    }

    /**
     *明細入力B_リレー盤 画面情報を取得 データなしテスト
     *
     */
    @isTest static void getInitScreenInfoNodataTest() {
        String qRtName='施設';
        createDate(qRtName);

        Test.startTest();
        String rtn = DetailsInputForRelayBoardController.getInitScreenInfo(true,
                                            dv.Id,
                                            '屋外',
                                            '自立SS',
                                            '1枚扉');
        Test.stopTest();
        System.debug('rtn='+rtn);
        System.assertNotEquals(rtn, null);//
        
        Map<String, Object> jsonDes = (Map<String, Object>)JSON.deserializeUntyped(rtn);
        List<Object> tbls = (List<Object>)jsonDes.get('classicTables');//メイン一覧データ
        System.assertEquals(tbls.size(), 0);
    }

    /**
     *内訳入力B_全画面 登録のテスト
     * 明細登録ありの検索テスト
     */
    @isTest static void submitDetailsTest() {
        String qRtName='施設';
        createDate(qRtName);

        Test.startTest();

        //Optデータを準備
        List<DetailsInputForRelayBoardController.QuantityObject> optRecords 
        = new List<DetailsInputForRelayBoardController.QuantityObject>();

        for(PricingTable__c tmp:tables){
            if (tmp.BU__c=='S') {
                DetailsInputForRelayBoardController.QuantityObject opt = new DetailsInputForRelayBoardController.QuantityObject();
                opt.Id=tmp.Id;
                opt.Price=11111;
                opt.Quantity=1;
                optRecords.add(opt);
            }
        }
        //登録
        String strSubmitDetails = DetailsInputForRelayBoardController.submitDetailsForRelayBoard(
                                            dv.Id,
                                            tables.get(0).Id,
                                            JSON.serialize(optRecords));

        //登録データあり場合　検索を行う
        String rtn = DetailsInputForRelayBoardController.getInitScreenInfo(true,
                                            dv.Id,
                                            'test',
                                            'test',
                                            'test');
        Test.stopTest();
        System.debug('strSubmitDetails'+strSubmitDetails);
        System.debug('dv.Quote__c'+dv.Quote__c);
        System.assertEquals(strSubmitDetails, dv.Quote__c);
        System.assertNotEquals(rtn, null);//
        
        Map<String, Object> jsonDes = (Map<String, Object>)JSON.deserializeUntyped(rtn);
        System.assertEquals(jsonDes.get('installationLocation'), '屋内');
        System.assertEquals(jsonDes.get('housingSpecifications'), '自立SS');
        System.assertEquals(jsonDes.get('doorSpecifications'), '観音開き');
        
    } 

}