force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量（数量×合計の計算式有り）</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/DeviceTriggerHandler.cls
public class DeviceTriggerHandler {
    DeviceTriggerLogic logic = new DeviceTriggerLogic();
    List<Device__c> dList =new List<Device__c>();

    public void onAfterInsert(List<Device__c> newList){
        logic.cloneDeviceAndRelatedRecords(newList);
        logic.updateConstructionZone(newList,new List<Device__c>());
        // List<Device__c> deviceTargetList = logic.getDeviceTargetRectype(newList);
        // if(deviceTargetList.isEmpty()) return;
        // deviceTargetList = logic.getDeviceTragetCheckedList(deviceTargetList);
        // if(deviceTargetList.isEmpty()) return;
        // Map<Id, List<Device__c>> quoteIdMap = logic.getQuoteIdByDevice(deviceTargetList);
        //logic.equipManageCostCalculation(newList,new List<Device__c>());
    }

    public void onAfterUpdate (Map<Id, Device__c> oldMap, Map<Id, Device__c> newMap) {
        logic.updateConstructionZone(newMap.values(),oldMap.values());
        // List<Device__c> deviceTargetList = logic.getDeviceTargetRectype(newMap.values());
        // if(deviceTargetList.isEmpty()) return;
        // deviceTargetList = logic.getDeviceValueChangedList(deviceTargetList, oldMap, newMap);
        // if(deviceTargetList.isEmpty()) return;
        // Map<Id, List<Device__c>> quoteIdMap = logic.getQuoteIdByDevice(deviceTargetList);
        //logic.equipManageCostCalculation(newMap.values(),oldMap.values());
    }

    public void onAfterDelete(List<Device__c> oldList){
        logic.updateConstructionZone(new List<Device__c>(),oldList);
        // List<Device__c> deviceTargetList = logic.getDeviceTargetRectype(oldList);
        // if(deviceTargetList.isEmpty()) return;
        // Map<Id, List<Device__c>> quoteIdMap = logic.getQuoteIdByDevice(deviceTargetList);
        //logic.equipManageCostCalculation(new List<Device__c>(),oldList);
    }

    /**
     * 全角→半角変換
     *
     * @param value 変換元文字列
     * @return 半角文字列
     */
    public void onBeforeInsert(List<Device__c> deviceList){
        Map<Id,List<Device__c>> quotemap = new Map<Id,List<Device__c>>();
        for (Device__c d : deviceList) {
            String value = d.Quantity__c;
            System.debug('value'+value);
            //logic.convertFullToHalf(value);
            d.Quantity__c = logic.convertFullToHalf(value);
            System.debug('d='+d.Quantity__c);
            if(quotemap.containskey(d.Quote__c)){
                quotemap.get(d.Quote__c).add(d);
            }else{
                quotemap.put(d.Quote__c,new List<Device__c>());
                quotemap.get(d.Quote__c).add(d);
            }
        }
        logic.quoteSpecificationNumberCheck(quotemap);
        logic.updateOfficialDemandField(deviceList);
        logic.deviceConstructionZoneSetting(deviceList);
    }

    /**
     * 全角→半角変換
     *
     * @param value 変換元文字列
     * @return 半角文字列
     */
    public void onBeforeUpdate(List<Device__c> deviceList){
        Map<Id,List<Device__c>> quotemap = new Map<Id,List<Device__c>>();
        for (Device__c d : deviceList) {
            String value = d.Quantity__c;
            System.debug('value'+value);
            //logic.convertFullToHalf(value);
            d.Quantity__c = logic.convertFullToHalf(value);
            System.debug('d='+d.Quantity__c);
            if(quotemap.containskey(d.Quote__c)){
                quotemap.get(d.Quote__c).add(d);
            }else{
                quotemap.put(d.Quote__c,new List<Device__c>());
                quotemap.get(d.Quote__c).add(d);
            }
        }
        logic.quoteSpecificationNumberCheck(quotemap);
        logic.deviceConstructionZoneSetting(deviceList);
        logic.updateFieldFromQuoteValues(deviceList);
        logic.updateOfficialDemandField(deviceList);
    }
}