force-app/main/default/objects/Account/fields/OfficeName__c.field-meta.xml
<CustomField>
    <fullName>OfficeName__c</fullName>
    <label>事業所名</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <defaultValue>$User.BUFormula__c</defaultValue>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
            <value>
                <fullName>官公情報</fullName>
            </value>
            <value>
                <fullName>海Ｆシ</fullName>
            </value>
            <value>
                <fullName>通シ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ConstructionDistinction__c.field-meta.xml
<CustomField>
    <fullName>ConstructionDistinction__c</fullName>
    <label>工事区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新設</fullName>
            </value>
            <value>
                <fullName>更新（自社既設）</fullName>
            </value>
            <value>
                <fullName>更新（他社既設）</fullName>
            </value>
            <value>
                <fullName>更新（蓄電池）</fullName>
            </value>
            <value>
                <fullName>増設</fullName>
            </value>
            <value>
                <fullName>修繕・改造</fullName>
            </value>
            <value>
                <fullName>保守</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>新設（建屋新設）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋新設）</label>
            </value>
            <value>
                <fullName>新設（建屋既存）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋既存）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DemanDepartment__c.field-meta.xml
<CustomField>
    <fullName>DemanDepartment__c</fullName>
    <label>需要部門</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>官公庁</fullName>
            </value>
            <value>
                <fullName>地方自治体</fullName>
            </value>
            <value>
                <fullName>下水道事業団</fullName>
            </value>
            <value>
                <fullName>金融</fullName>
            </value>
            <value>
                <fullName>通信</fullName>
            </value>
            <value>
                <fullName>IDC</fullName>
                <label>IDC（通信キャリア系）</label>
            </value>
            <value>
                <fullName>IDC2</fullName>
                <label>IDC（通信キャリア以外：国内系）</label>
            </value>
            <value>
                <fullName>IDC3</fullName>
                <label>IDC（通信キャリア以外：外資系）</label>
            </value>
            <value>
                <fullName>不動産</fullName>
            </value>
            <value>
                <fullName>放送・報道</fullName>
            </value>
            <value>
                <fullName>製造業</fullName>
            </value>
            <value>
                <fullName>病院</fullName>
            </value>
            <value>
                <fullName>学校</fullName>
            </value>
            <value>
                <fullName>公営競技</fullName>
            </value>
            <value>
                <fullName>スタジアム・アリーナ</fullName>
            </value>
            <value>
                <fullName>エネルギー事業</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DemandOf__c.field-meta.xml
<CustomField>
    <fullName>DemandOf__c</fullName>
    <label>官需／民需</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>官需</fullName>
            </value>
            <value>
                <fullName>民需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ExportCategory__c.field-meta.xml
<CustomField>
    <fullName>ExportCategory__c</fullName>
    <label>輸出区分</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>0 国内</fullName>
                <default>true</default>
                <label>0 国内</label>
            </value>
            <value>
                <fullName>1 直輸為替無</fullName>
            </value>
            <value>
                <fullName>2 間接輸出</fullName>
            </value>
            <value>
                <fullName>3 直輸為替有</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Handling__c.field-meta.xml
<CustomField>
    <fullName>Handling__c</fullName>
    <label>扱方</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>直扱</fullName>
            </value>
            <value>
                <fullName>委嘱</fullName>
            </value>
            <value>
                <fullName>協力</fullName>
            </value>
            <value>
                <fullName>仕切</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InformationFrom__c.field-meta.xml
<CustomField>
    <fullName>InformationFrom__c</fullName>
    <label>【削除予定】情報入手先</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施主</fullName>
            </value>
            <value>
                <fullName>設計事務所</fullName>
            </value>
            <value>
                <fullName>ゼネコン</fullName>
            </value>
            <value>
                <fullName>サブコン</fullName>
            </value>
            <value>
                <fullName>代理店</fullName>
            </value>
            <value>
                <fullName>MPEC</fullName>
            </value>
            <value>
                <fullName>維持管理会社</fullName>
            </value>
            <value>
                <fullName>公開情報（新聞・WEB・官報等）</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KOUJI_SYU__c.field-meta.xml
<CustomField>
    <fullName>KOUJI_SYU__c</fullName>
    <label>工事種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>電気工事</fullName>
            </value>
            <value>
                <fullName>電気通信工事</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
                <label>その他（物品・役務）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NeedConstruction__c.field-meta.xml
<CustomField>
    <fullName>NeedConstruction__c</fullName>
    <label>工事有無</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>無</fullName>
            </value>
            <value>
                <fullName>有（技術者配置：要）</fullName>
            </value>
            <value>
                <fullName>有（技術者配置：不要）</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OrderExpectation__c.field-meta.xml
<CustomField>
    <fullName>OrderExpectation__c</fullName>
    <label>受注見込</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <color>#A53711</color>
                <label>1 決定</label>
            </value>
            <value>
                <fullName>2</fullName>
                <color>#FF99FF</color>
                <label>2 有望</label>
            </value>
            <value>
                <fullName>3</fullName>
                <color>#F3D904</color>
                <label>3 努力</label>
            </value>
            <value>
                <fullName>4C</fullName>
                <color>#B6E32E</color>
                <label>4C チャレンジ</label>
            </value>
            <value>
                <fullName>4</fullName>
                <color>#66E9BD</color>
                <label>4 希望</label>
            </value>
            <value>
                <fullName>5</fullName>
                <color>#0B6FCE</color>
                <label>5 需要</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prefecture__c.field-meta.xml
<CustomField>
    <fullName>Prefecture__c</fullName>
    <formula>Region__r.Prefecture__c</formula>
    <label>都道府県名</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>地域が不明・未定の場合は「不明」項目を登録下さい。</inlineHelpText>
    <label>地域・住所</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>Opps01</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/RegionCode__c.field-meta.xml
<CustomField>
    <fullName>RegionCode__c</fullName>
    <formula>Region__r.RegionCode__c</formula>
    <label>地域コード</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SalesTax__c.field-meta.xml
<CustomField>
    <fullName>SalesTax__c</fullName>
    <label>消費税率</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>10</fullName>
                <default>true</default>
                <label>10%</label>
            </value>
            <value>
                <fullName>8</fullName>
                <label>8%</label>
            </value>
            <value>
                <fullName>免税</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ScheduledSalesDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledSalesDate__c</fullName>
    <label>売上予定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UKE_KBN__c.field-meta.xml
<CustomField>
    <fullName>UKE_KBN__c</fullName>
    <label>元請／下請</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>元請</fullName>
            </value>
            <value>
                <fullName>JV</fullName>
            </value>
            <value>
                <fullName>下請</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Region__c/Region__c.object-meta.xml
<CustomObject>
    <description>地域マスタ</description>
    <label>地域</label>
    <nameField>
        <label>地域名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Region__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>市区町村群名</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/City_kana__c.field-meta.xml
<CustomField>
    <fullName>City_kana__c</fullName>
    <label>市区町村郡名（カナ）</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Prefecture__c.field-meta.xml
<CustomField>
    <fullName>Prefecture__c</fullName>
    <label>都道府県名</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Prefecture_kana__c.field-meta.xml
<CustomField>
    <fullName>Prefecture_kana__c</fullName>
    <label>都道府県名（カナ）</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/Region_key__c.field-meta.xml
<CustomField>
    <fullName>Region_key__c</fullName>
    <externalId>true</externalId>
    <label>県名＋市町村名（外部キー）</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Region__c/fields/RegionCode__c.field-meta.xml
<CustomField>
    <fullName>RegionCode__c</fullName>
    <label>地域コード</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
            <value>
                <fullName>官公情報</fullName>
            </value>
            <value>
                <fullName>海Fシ</fullName>
            </value>
            <value>
                <fullName>通シ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Department__c.field-meta.xml
<CustomField>
    <fullName>Department__c</fullName>
    <label>所属部</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SRInfoTriggerHandlerTest.cls
@isTest
private class SRInfoTriggerHandlerTest {

    /**
     * テストケース　testOnAfterInsert_01
     * 
     * 【準備】
     *  部門管理者ユーザで操作する
     *  取引先（事業所）、地域、案件を作成する
     * 
     * 【テスト実行】
     *  SR情報.案件に作成した案件を設定する
     *  SR情報を作成する
     * 
     * 【期待値】
     *  案件.最終SR集計日時が更新されていること
     * 
     */
    @isTest
    static void testOnAfterInsert_01() {

        Profile prof = [SELECT Id FROM Profile WHERE Name = '部門管理者' LIMIT 1];
        UserRole role = [SELECT Id FROM UserRole WHERE Name = '01_社会環境事業部' LIMIT 1];
        User user = createUser(prof.Id, role.Id, 'terrasky-melco-admin', '官需', '01_社会環境事業部', '施設環境部', '第一課');
        insert user;

        System.runAs(user) {

            // 取引先（事業所）
            RecordType recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' and name = '事業所' LIMIT 1];

            Account acc = new Account(
                Name = 'Test Account',
                Phone = '09011111111',
                RecordTypeId = recType.Id,
                OfficeName__c = 'acc1'
            );
            insert acc;

            // 地域
            Region__c region = new Region__c(
                Prefecture_kana__c = 'ホッカイドウ',
                Prefecture__c = '北海道',
                RegionCode__c = 'A1210',
                City_kana__c = 'サッポロシ',
                City__c = '札幌市',
                Region_key__c = '北海道札幌市',
                Name = '北海道札幌市'
            );
            insert region;

            // 案件
            Opportunity opp = new Opportunity(
                Name = 'Test Opp1',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-1)
            );
            insert opp;

            // テスト開始
            Test.startTest();

            // SR情報を作成する
            SRInfo__c sr = new SRInfo__c();
            sr.SR_Number__c = 'A9999V9990';
            sr.J_Number__c = '001';
            sr.Opportunity__c = opp.Id;
            insert sr;

            // テスト終了
            Test.stopTest();

            List<Opportunity> oppList = [SELECT Id, LastSRAggregateDate__c FROM Opportunity WHERE Id =: opp.Id];

            // 検証
            System.assertEquals(1, oppList.size());
            System.assertNotEquals(null, oppList[0].LastSRAggregateDate__c);
            System.assertNotEquals(opp.LastSRAggregateDate__c, oppList[0].LastSRAggregateDate__c);
        }
    }

    /**
     * テストケース　testOnAfterInsert_02
     * 
     * 【準備】
     *  部門管理者ユーザで操作する
     *  取引先（事業所）、地域を作成する
     *  案件を２件作成する
     * 
     * 【テスト実行】
     *  SR情報.案件に作成した案件を各々設定する
     *  SR情報を２件作成する
     * 
     * 【期待値】
     *  各案件.最終SR集計日時が更新されていること
     * 
     */
    @isTest
    static void testOnAfterInsert_02() {

        Profile prof = [SELECT Id FROM Profile WHERE Name = '部門管理者' LIMIT 1];
        UserRole role = [SELECT Id FROM UserRole WHERE Name = '01_社会環境事業部' LIMIT 1];
        User user = createUser(prof.Id, role.Id, 'terrasky-melco-admin', '官需', '01_社会環境事業部', '施設環境部', '第一課');
        insert user;

        System.runAs(user) {
            // 取引先（事業所）
            RecordType recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' and name = '事業所' LIMIT 1];

            Account acc = new Account(
                Name = 'Test Account',
                Phone = '09011111111',
                RecordTypeId = recType.Id,
                OfficeName__c = 'acc1'
            );
            insert acc;

            // 地域
            Region__c region = new Region__c(
                Prefecture_kana__c = 'ホッカイドウ',
                Prefecture__c = '北海道',
                RegionCode__c = 'A1210',
                City_kana__c = 'サッポロシ',
                City__c = '札幌市',
                Region_key__c = '北海道札幌市',
                Name = '北海道札幌市'
            );
            insert region;

            // 案件
            List<Opportunity> oppList = new List<Opportunity>();

            Opportunity opp1 = new Opportunity(
                Name = 'Test Opp1',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-1)
            );
            oppList.add(opp1);

            Opportunity opp2 = new Opportunity(
                Name = 'Test Opp2',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-2)
            );
            oppList.add(opp2);

            insert oppList;

            // テスト開始
            Test.startTest();

            // SR情報を作成する
            List<SRInfo__c> srList = new List<SRInfo__c>();

            SRInfo__c sr1 = new SRInfo__c(
                SR_Number__c = 'A9999V9990',
                J_Number__c = '001',
                Opportunity__c = opp1.Id
            );
            srList.add(sr1);

            SRInfo__c sr2 = new SRInfo__c(
                SR_Number__c = 'A9999V9991',
                J_Number__c = '002',
                Opportunity__c = opp2.Id
            );
            srList.add(sr2);

            insert srList;

            // テスト終了
            Test.stopTest();

            List<Opportunity> oppList2 = [SELECT Id, LastSRAggregateDate__c FROM Opportunity WHERE Id IN: oppList ORDER BY Name];

            // 検証
            System.assertEquals(2, oppList2.size());
            System.assertNotEquals(null, oppList2[0].LastSRAggregateDate__c);
            System.assertNotEquals(oppList[0].LastSRAggregateDate__c, oppList2[0].LastSRAggregateDate__c);
            System.assertNotEquals(null, oppList2[1].LastSRAggregateDate__c);
            System.assertNotEquals(oppList[1].LastSRAggregateDate__c, oppList2[1].LastSRAggregateDate__c);
        }
    }

    /**
     * テストケース　testOnAfterUpdate_01
     * 
     * 【準備】
     *  部門管理者ユーザで操作する
     *  取引先（事業所）、地域、案件を作成する
     *  SR情報.案件に作成した案件を設定する
     *  SR情報を作成する
     * 
     * 【テスト実行】
     *  SR情報を更新する
     * 
     * 【期待値】
     *  案件.最終SR集計日時が更新されていること
     */
    @isTest
    static void testOnAfterUpdate_01() {

        Profile prof = [SELECT Id FROM Profile WHERE Name = '部門管理者' LIMIT 1];
        UserRole role = [SELECT Id FROM UserRole WHERE Name = '01_社会環境事業部' LIMIT 1];
        User user = createUser(prof.Id, role.Id, 'terrasky-melco-admin', '官需', '01_社会環境事業部', '施設環境部', '第一課');
        insert user;

        System.runAs(user) {

            // 取引先（事業所）
            RecordType recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' and name = '事業所' LIMIT 1];

            Account acc = new Account(
                Name = 'Test Account',
                Phone = '09011111111',
                RecordTypeId = recType.Id,
                OfficeName__c = 'acc1'
            );
            insert acc;

            // 地域
            Region__c region = new Region__c(
                Prefecture_kana__c = 'ホッカイドウ',
                Prefecture__c = '北海道',
                RegionCode__c = 'A1210',
                City_kana__c = 'サッポロシ',
                City__c = '札幌市',
                Region_key__c = '北海道札幌市',
                Name = '北海道札幌市'
            );
            insert region;

            // 案件
            Opportunity opp = new Opportunity(
                Name = 'Test Opp1',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-1)
            );
            insert opp;

            // SR情報
            SRInfo__c sr = new SRInfo__c(
                SR_Number__c = 'A9999V9990',
                J_Number__c = '001',
                Opportunity__c = opp.Id
            );
            insert sr;   

            // テスト開始
            Test.startTest();

            // SR情報を更新する
            sr.AffiliationName__c = 'test';
            update sr;

            // テスト終了
            Test.stopTest();

            List<Opportunity> oppList = [SELECT Id, LastSRAggregateDate__c FROM Opportunity WHERE Id =: opp.Id];

            // 検証
            System.assertEquals(1, oppList.size());
            System.assertNotEquals(null, oppList[0].LastSRAggregateDate__c);
            System.assertNotEquals(opp.LastSRAggregateDate__c, oppList[0].LastSRAggregateDate__c);
        }
    }

    /**
     * テストケース　testOnAfterUpdate_02
     * 
     * 【準備】
     *  部門管理者ユーザで操作する
     *  取引先（事業所）、地域、案件を作成する
     *  SR情報.案件に作成した案件を設定しない
     *  SR情報を作成する
     * 
     * 【テスト実行】
     *  SR情報を更新する
     * 
     * 【期待値】
     *  案件.最終SR集計日時が更新されていないこと
     */
    @isTest
    static void testOnAfterUpdate_02() {

        Profile prof = [SELECT Id FROM Profile WHERE Name = '部門管理者' LIMIT 1];
        UserRole role = [SELECT Id FROM UserRole WHERE Name = '01_社会環境事業部' LIMIT 1];
        User user = createUser(prof.Id, role.Id, 'terrasky-melco-admin', '官需', '01_社会環境事業部', '施設環境部', '第一課');
        insert user;

        System.runAs(user) {

            // 取引先（事業所）
            RecordType recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' and name = '事業所' LIMIT 1];

            Account acc = new Account(
                Name = 'Test Account',
                Phone = '09011111111',
                RecordTypeId = recType.Id,
                OfficeName__c = 'acc1'
            );
            insert acc;

            // 地域
            Region__c region = new Region__c(
                Prefecture_kana__c = 'ホッカイドウ',
                Prefecture__c = '北海道',
                RegionCode__c = 'A1210',
                City_kana__c = 'サッポロシ',
                City__c = '札幌市',
                Region_key__c = '北海道札幌市',
                Name = '北海道札幌市'
            );
            insert region;

            // 案件
            Opportunity opp = new Opportunity(
                Name = 'Test Opp1',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-1)
            );
            insert opp;

            // SR情報（案件を設定しない）
            SRInfo__c sr = new SRInfo__c(
                SR_Number__c = 'A9999V9990',
                J_Number__c = '001',
                Opportunity__c = null
            );
            insert sr;

            // テスト開始
            Test.startTest();

            // SR情報を更新する
            sr.AffiliationName__c = 'test';
            update sr;

            // テスト終了
            Test.stopTest();

            List<Opportunity> oppList = [SELECT Id, LastSRAggregateDate__c FROM Opportunity WHERE Id =: opp.Id];

            // 検証
            System.assertEquals(1, oppList.size());
            System.assertEquals(opp.LastSRAggregateDate__c, oppList[0].LastSRAggregateDate__c);
        }
    }

    /**
     * テストケース　testOnAfterUpdate_03
     * 
     * 【準備】
     *  システム管理者ユーザで操作する
     *  取引先（事業所）、地域、案件を作成する
     *  SR情報.案件に作成した案件を設定する
     *  SR情報を作成する
     * 
     * 【テスト実行】
     *  SR情報を更新する
     * 
     * 【期待値】
     *  販事、部門管理者以外のユーザが操作した為、案件.最終SR集計日時が更新されていないこと
     */
    @isTest
    static void testOnAfterUpdate_03() {

        Profile prof = [SELECT Id FROM Profile WHERE Name = 'システム管理者' LIMIT 1];
        UserRole role = [SELECT Id FROM UserRole WHERE Name = '01_社会環境事業部' LIMIT 1];
        User user = createUser(prof.Id, role.Id, 'terrasky-melco-admin', '官需', '01_社会環境事業部', '施設環境部', '第一課');
        insert user;

        System.runAs(user) {

            // 取引先（事業所）
            RecordType recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' and name = '事業所' LIMIT 1];

            Account acc = new Account(
                Name = 'Test Account',
                Phone = '09011111111',
                RecordTypeId = recType.Id,
                OfficeName__c = 'acc1'
            );
            insert acc;

            // 地域
            Region__c region = new Region__c(
                Prefecture_kana__c = 'ホッカイドウ',
                Prefecture__c = '北海道',
                RegionCode__c = 'A1210',
                City_kana__c = 'サッポロシ',
                City__c = '札幌市',
                Region_key__c = '北海道札幌市',
                Name = '北海道札幌市'
            );
            insert region;

            // 案件
            Opportunity opp = new Opportunity(
                Name = 'Test Opp1',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-1)
            );
            insert opp;

            // SR情報
            SRInfo__c sr = new SRInfo__c(
                SR_Number__c = 'A9999V9990',
                J_Number__c = '001',
                Opportunity__c = opp.Id
            );
            insert sr;   

            // テスト開始
            Test.startTest();

            // SR情報を更新する
            sr.AffiliationName__c = 'test';
            update sr;

            // テスト終了
            Test.stopTest();

            List<Opportunity> oppList = [SELECT Id, LastSRAggregateDate__c FROM Opportunity WHERE Id =: opp.Id];

            // 検証
            System.assertEquals(1, oppList.size());
            System.assertEquals(opp.LastSRAggregateDate__c, oppList[0].LastSRAggregateDate__c);
        }
    }

    /**
     * テストケース　testOnAfterDelete_01
     * 
     * 【準備】
     *  部門管理者ユーザで操作する
     *  取引先（事業所）、地域、案件を作成する
     *  SR情報.案件に作成した案件を設定する
     *  SR情報を作成する
     * 
     * 【テスト実行】
     *  SR情報を削除する
     * 
     * 【期待値】
     *  案件.最終SR集計日時が更新されていること
     * 
     */
    @isTest
    static void testOnAfterDelete_01() {

        Profile prof = [SELECT Id FROM Profile WHERE Name = '部門管理者' LIMIT 1];
        UserRole role = [SELECT Id FROM UserRole WHERE Name = '01_社会環境事業部' LIMIT 1];
        User user = createUser(prof.Id, role.Id, 'terrasky-melco-admin', '官需', '01_社会環境事業部', '施設環境部', '第一課');
        insert user;

        System.runAs(user) {

            // 取引先（事業所）
            RecordType recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' and name = '事業所' LIMIT 1];

            Account acc = new Account(
                Name = 'Test Account',
                Phone = '09011111111',
                RecordTypeId = recType.Id,
                OfficeName__c = 'acc1'
            );
            insert acc;

            // 地域
            Region__c region = new Region__c(
                Prefecture_kana__c = 'ホッカイドウ',
                Prefecture__c = '北海道',
                RegionCode__c = 'A1210',
                City_kana__c = 'サッポロシ',
                City__c = '札幌市',
                Region_key__c = '北海道札幌市',
                Name = '北海道札幌市'
            );
            insert region;

            // 案件
            Opportunity opp = new Opportunity(
                Name = 'Test Opp1',
                AccountId = acc.Id,
                StageName = '基本計画',
                OrderExpectation__c = '1', 
                Region__c = region.Id,
                BU__c = '',
                CloseDate = Date.today(),
                ScheduledSalesDate__c = Date.today(),
                NeedConstruction__c = '無',
                KOUJI_SYU__c = '電気工事',
                UKE_KBN__c = '元請',
                ConstructionDistinction__c = '新設',
                Handling__c = '直扱',
                InformationFrom__c = '施主',
                DemandOf__c = '官需',
                DemanDepartment__c = '官公庁',
                ExportCategory__c = '0',
                SalesTax__c = '10',
                Website__c = 1,
                Competitor__c = acc.Id,
                LastSRAggregateDate__c = Datetime.now().addMinutes(-1)
            );
            insert opp;

            // SR情報
            SRInfo__c sr = new SRInfo__c(
                SR_Number__c = 'A9999V9990',
                J_Number__c = '001',
                Opportunity__c = opp.Id
            );
            insert sr;

            // テスト開始
            Test.startTest();

            // SR情報を作成する
            delete sr;

            // テスト終了
            Test.stopTest();

            List<Opportunity> oppList = [SELECT Id, LastSRAggregateDate__c FROM Opportunity WHERE Id =: opp.Id];

            // 検証
            System.assertEquals(1, oppList.size());
            System.assertNotEquals(null, oppList[0].LastSRAggregateDate__c);
            System.assertNotEquals(opp.LastSRAggregateDate__c, oppList[0].LastSRAggregateDate__c);
        }
    }

    private static User createUser(Id profileId, Id roleId, String uNamePref, String BUVal, String division, String department, String division01) {
        String str = Datetime.now().format('yyyyMMddHHmmss');
        User u = new User(
            UserName = uNamePref + '-' + str + '@prot2.mc.example.com.3bu'
            , Email = uNamePref + '-' + str + '@prot2.mc.example.com.3bu'
            , LastName = 'test'
            , Alias = 'test'
            , TimeZoneSidKey = 'Asia/Tokyo'
            , LocaleSidKey = 'ja_JP'
            , EmailEncodingKey = 'ISO-2022-JP'
            , LanguageLocaleKey = 'ja'
            , ProfileId = profileId
            , UserRoleId = roleId
            , BU__c = BUVal
            , DepartmentAndDivision__c = division
            , Department__c = department
            , Division01__c = division01
        );
        return u;
    }
}