force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <defaultValue>IF ($RecordType.Name = &quot;施設&quot;, &quot;0&quot;, &quot;&quot;)</defaultValue>
    <label>一般管理費率</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerHandler.cls
public class QuoteTriggerHandler {
    QuoteTriggerLogic logic = new QuoteTriggerLogic();
    List<Quote__c> qList =new List<Quote__c>();

    public void onBeforeInsert(List<Quote__c> newList,Map<Id,Quote__c> oldMap){
        logic.calculateNETItem(newList,oldMap);
    }

    public void onBeforeUpdate(List<Quote__c> newList,Map<Id,Quote__c> oldMap){
        logic.calculateNETItem(newList,oldMap);
        logic.equipManageCostCalculation(newList);
    }

    public void onAfterInsert(List<Quote__c> newList){
        logic.cloneQuoteAndRelatedRecords(newList);
    }

    /**
     * 全角→半角変換
     *
     * @param value 変換元文字列
     * @return 半角文字列
     */
    public void onBeforeInsertUpdate(List<Quote__c> quoteList){
        for (Quote__c q : quoteList) {
            String value = q.GeneralAdministrativeExpenses__c;
            System.debug('value'+value);
            logic.convertFullToHalf(value);
            q.GeneralAdministrativeExpenses__c = logic.convertFullToHalf(value);
            System.debug('q='+q.GeneralAdministrativeExpenses__c);
            qList.add(new Quote__c ( QuoteNumber__c = q.QuoteNumber__c
                                    ,GeneralAdministrativeExpenses__c = q.GeneralAdministrativeExpenses__c
                                    ,PowerFrequency__c = q.PowerFrequency__c
                                    ,RecordTypeId = q.RecordTypeId
                                    ));
            System.debug('new'+qList);
        }
    }
}