force-app/main/default/objects/QuoteBiddingInquiry__c/QuoteBiddingInquiry__c.object-meta.xml
<CustomObject>
    <label>見積・応札・手数料伺い</label>
    <nameField>
        <label>伺い件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QuoteBiddingInquiry__c/fields/ContractAmountMax__c.field-meta.xml
<CustomField>
    <fullName>ContractAmountMax__c</fullName>
    <label>受注(見込)CP【MAX】</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteBiddingInquiry__c/fields/ContractAmountMin__c.field-meta.xml
<CustomField>
    <fullName>ContractAmountMin__c</fullName>
    <label>受注(見込)CP【MIN】</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/QuoteBiddingInquiry__c/fields/Creating__c.field-meta.xml
<CustomField>
    <fullName>Creating__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>入力完了後、チェックを外してWF開始ください。チェックを外して保存ボタンを押すと入力エラーが確認できます。</inlineHelpText>
    <label>伺い作成中</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QuoteBiddingInquiry__c/fields/DependentFeeInquiry__c.field-meta.xml
<CustomField>
    <fullName>DependentFeeInquiry__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>手数料伺いを紐づけて保存すると代理店情報セクションが更新されます</inlineHelpText>
    <label>参照先手数料伺い</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>QuoteBiddingInquiry__c.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>FeeInquiry</value>
        </filterItems>
        <filterItems>
            <field>QuoteBiddingInquiry__c.Opportunity__c</field>
            <operation>equals</operation>
            <valueField>$Source.Opportunity__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>QuoteBiddingInquiry__c</referenceTo>
    <relationshipLabel>見積・応札・手数料伺い (参照先手数料伺い)</relationshipLabel>
    <relationshipName>DependentFeeInquiryShip</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteBiddingInquiry__c/fields/NewChanged__c.field-meta.xml
<CustomField>
    <fullName>NewChanged__c</fullName>
    <label>新規・変更</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>新規</fullName>
            </value>
            <value>
                <fullName>変更</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BidAgencyDetailGetTableControllerTest.cls
@IsTest
public class BidAgencyDetailGetTableControllerTest {

    // 伺い数値明細画面 テスト
    @IsTest
    static void TestgetDetailTable1() {
        
        BidAgencyDetailGetTableController.getDetailTable(null);

        QuoteBiddingInquiry__c qbi = createTestQuoteBiddingInquiry('手数料伺い');
        // qbi.DetailAfterDesignSalesCommission__c = 123;
        insert qbi;

        BidAgencyDetailGetTableController.getDetailTable(qbi.Id );
    }

    @IsTest
    static void TestgetDetailTable2() {
        
        BidAgencyDetailGetTableController.getDetailTable(null);

        QuoteBiddingInquiry__c qbi2= createTestQuoteBiddingInquiry('手数料伺い');
        // qbi2.DetailAfterDesignSalesCommission__c = 123;
        insert qbi2;

        QuoteBiddingInquiry__c qbi = createTestQuoteBiddingInquiry('手数料伺い');
        // qbi.DetailAfterDesignSalesCommission__c = 123;
        qbi.DependentFeeInquiry__c = qbi2.Id;
        insert qbi;

        BidAgencyDetailGetTableController.getDetailTable(qbi.Id );
    }

    @IsTest
    static void TestgetDetailTable3() {
        
        BidAgencyDetailGetTableController.getDetailTable(null);

        QuoteBiddingInquiry__c qbi2= createTestQuoteBiddingInquiry('手数料伺い');
        // qbi2.DetailAfterDesignSalesCommission__c = 123;
        insert qbi2;

        QuoteBiddingInquiry__c qbi = createTestQuoteBiddingInquiry('手数料伺い');
        // qbi.DetailAfterDesignSalesCommission__c = 123;
        qbi.ContractAmountMax__c = 50000;
        qbi.ContractAmountMin__c = 10000;
        qbi.DependentFeeInquiry__c = qbi2.Id;
        insert qbi;

        BidAgencyDetailGetTableController.getDetailTable(qbi.Id );
    }

     // テスト用のQuoteBiddingInquiry__cレコードを作成するヘルパーメソッド
     private static QuoteBiddingInquiry__c createTestQuoteBiddingInquiry(String recordType) {

        // レコードタイプを取得
        Schema.SObjectType qbiType = QuoteBiddingInquiry__c.sObjectType;
        Schema.DescribeSObjectResult qbiDescribe = qbiType.getDescribe();
        Map<String, Schema.RecordTypeInfo> qbiRecordTypes = qbiDescribe.getRecordTypeInfosByName();
        Id qbiRecordTypeId = qbiRecordTypes.get(recordType).getRecordTypeId();

        QuoteBiddingInquiry__c qbi = new QuoteBiddingInquiry__c();
        qbi.Creating__c = true;
        qbi.NewChanged__c = '新規';
        qbi.RecordTypeId = qbiRecordTypeId;
        return qbi;
    }
}