force-app/main/default/objects/Opportunity/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <defaultValue>$User.BUFormula__c</defaultValue>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
            <value>
                <fullName>官公情報</fullName>
            </value>
            <value>
                <fullName>海Ｆシ</fullName>
            </value>
            <value>
                <fullName>通シ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ConstructionDistinction__c.field-meta.xml
<CustomField>
    <fullName>ConstructionDistinction__c</fullName>
    <label>工事区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新設</fullName>
            </value>
            <value>
                <fullName>更新（自社既設）</fullName>
            </value>
            <value>
                <fullName>更新（他社既設）</fullName>
            </value>
            <value>
                <fullName>更新（蓄電池）</fullName>
            </value>
            <value>
                <fullName>増設</fullName>
            </value>
            <value>
                <fullName>修繕・改造</fullName>
            </value>
            <value>
                <fullName>保守</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>新設（建屋新設）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋新設）</label>
            </value>
            <value>
                <fullName>新設（建屋既存）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋既存）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DemandOf__c.field-meta.xml
<CustomField>
    <fullName>DemandOf__c</fullName>
    <label>官需／民需</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>官需</fullName>
            </value>
            <value>
                <fullName>民需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Handling__c.field-meta.xml
<CustomField>
    <fullName>Handling__c</fullName>
    <label>扱方</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>直扱</fullName>
            </value>
            <value>
                <fullName>委嘱</fullName>
            </value>
            <value>
                <fullName>協力</fullName>
            </value>
            <value>
                <fullName>仕切</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/InformationFrom__c.field-meta.xml
<CustomField>
    <fullName>InformationFrom__c</fullName>
    <label>【削除予定】情報入手先</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施主</fullName>
            </value>
            <value>
                <fullName>設計事務所</fullName>
            </value>
            <value>
                <fullName>ゼネコン</fullName>
            </value>
            <value>
                <fullName>サブコン</fullName>
            </value>
            <value>
                <fullName>代理店</fullName>
            </value>
            <value>
                <fullName>MPEC</fullName>
            </value>
            <value>
                <fullName>維持管理会社</fullName>
            </value>
            <value>
                <fullName>公開情報（新聞・WEB・官報等）</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/KOUJI_SYU__c.field-meta.xml
<CustomField>
    <fullName>KOUJI_SYU__c</fullName>
    <label>工事種別</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>電気工事</fullName>
            </value>
            <value>
                <fullName>電気通信工事</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
                <label>その他（物品・役務）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NeedConstruction__c.field-meta.xml
<CustomField>
    <fullName>NeedConstruction__c</fullName>
    <label>工事有無</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>無</fullName>
            </value>
            <value>
                <fullName>有（技術者配置：要）</fullName>
            </value>
            <value>
                <fullName>有（技術者配置：不要）</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/OrderExpectation__c.field-meta.xml
<CustomField>
    <fullName>OrderExpectation__c</fullName>
    <label>受注見込</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>1</fullName>
                <color>#A53711</color>
                <label>1 決定</label>
            </value>
            <value>
                <fullName>2</fullName>
                <color>#FF99FF</color>
                <label>2 有望</label>
            </value>
            <value>
                <fullName>3</fullName>
                <color>#F3D904</color>
                <label>3 努力</label>
            </value>
            <value>
                <fullName>4C</fullName>
                <color>#B6E32E</color>
                <label>4C チャレンジ</label>
            </value>
            <value>
                <fullName>4</fullName>
                <color>#66E9BD</color>
                <label>4 希望</label>
            </value>
            <value>
                <fullName>5</fullName>
                <color>#0B6FCE</color>
                <label>5 需要</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <label>プラント</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>SBU__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>特高（110kV以上）</fullName>
            </value>
            <value>
                <fullName>特高（66/77kV）</fullName>
            </value>
            <value>
                <fullName>特高（22/33kV）</fullName>
            </value>
            <value>
                <fullName>特高（22kV・SNW）</fullName>
            </value>
            <value>
                <fullName>高圧（6.6kV・サブ変）</fullName>
            </value>
            <value>
                <fullName>電力監視</fullName>
            </value>
            <value>
                <fullName>受変電その他</fullName>
            </value>
            <value>
                <fullName>9000シリーズ</fullName>
            </value>
            <value>
                <fullName>2000シリーズ</fullName>
            </value>
            <value>
                <fullName>MPC</fullName>
            </value>
            <value>
                <fullName>UPSその他</fullName>
            </value>
            <value>
                <fullName>D/G</fullName>
            </value>
            <value>
                <fullName>GT/G</fullName>
            </value>
            <value>
                <fullName>常用発電機</fullName>
            </value>
            <value>
                <fullName>自家発その他</fullName>
            </value>
            <value>
                <fullName>BAS</fullName>
            </value>
            <value>
                <fullName>BMS</fullName>
            </value>
            <value>
                <fullName>セキュリティー</fullName>
            </value>
            <value>
                <fullName>ビルシステムその他</fullName>
            </value>
            <value>
                <fullName>LED屋外</fullName>
            </value>
            <value>
                <fullName>LED屋内</fullName>
            </value>
            <value>
                <fullName>レンタル</fullName>
            </value>
            <value>
                <fullName>液晶・DLP</fullName>
            </value>
            <value>
                <fullName>映像その他</fullName>
            </value>
            <value>
                <fullName>PV</fullName>
            </value>
            <value>
                <fullName>スマエネ</fullName>
            </value>
            <value>
                <fullName>直流配電</fullName>
            </value>
            <value>
                <fullName>PVスマエネその他</fullName>
            </value>
            <value>
                <fullName>電源その他</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>上水既存</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/PumpStation__c.field-meta.xml
<CustomField>
    <fullName>PumpStation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>水環境BUは入力必須です。</inlineHelpText>
    <label>機場名</label>
    <referenceTo>PumpStation__c</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>OppsPumpStation</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>地域が不明・未定の場合は「不明」項目を登録下さい。</inlineHelpText>
    <label>地域・住所</label>
    <referenceTo>Region__c</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>Opps01</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SBU__c.field-meta.xml
<CustomField>
    <fullName>SBU__c</fullName>
    <label>SBU</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>BU__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>上水</fullName>
            </value>
            <value>
                <fullName>下水</fullName>
            </value>
            <value>
                <fullName>オゾン</fullName>
            </value>
            <value>
                <fullName>受変電</fullName>
            </value>
            <value>
                <fullName>自家発</fullName>
            </value>
            <value>
                <fullName>ＵＰＳ</fullName>
            </value>
            <value>
                <fullName>映像</fullName>
            </value>
            <value>
                <fullName>ビルシ</fullName>
            </value>
            <value>
                <fullName>PVスマエネ</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>建設防災</fullName>
            </value>
            <value>
                <fullName>有料道路</fullName>
            </value>
            <value>
                <fullName>警察海保</fullName>
            </value>
            <value>
                <fullName>運輸</fullName>
            </value>
            <value>
                <fullName>中央</fullName>
            </value>
            <value>
                <fullName>アクセス・ホーム</fullName>
            </value>
            <value>
                <fullName>コアメトロ</fullName>
            </value>
            <value>
                <fullName>衛星</fullName>
            </value>
            <value>
                <fullName>ソリューション</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ScheduledSalesDate__c.field-meta.xml
<CustomField>
    <fullName>ScheduledSalesDate__c</fullName>
    <label>売上予定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/UKE_KBN__c.field-meta.xml
<CustomField>
    <fullName>UKE_KBN__c</fullName>
    <label>元請／下請</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>元請</fullName>
            </value>
            <value>
                <fullName>JV</fullName>
            </value>
            <value>
                <fullName>下請</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PumpStation__c/PumpStation__c.object-meta.xml
<CustomObject>
    <label>機場</label>
    <nameField>
        <label>機場名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PumpStation__c/fields/UniqueKey__c.field-meta.xml
<CustomField>
    <fullName>UniqueKey__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>一意キー</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/User/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
            <value>
                <fullName>官公情報</fullName>
            </value>
            <value>
                <fullName>海Fシ</fullName>
            </value>
            <value>
                <fullName>通シ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BulkApprovalActionTest.cls
@isTest private class  BulkApprovalActionTest {
    @isTest
    private static void testBulkApproval(){

        // テストデータの用意
        Account acc = createOfficeAccount();
        insert acc;

        Region__c region = createRegion();
        insert region;

        PumpStation__c ps = createPumpStation();
        ps.UniqueKey__c = String.valueOf(Datetime.now()) + 'testApprovalRequest001';
        insert ps;

        Opportunity opp = createOpportunity(acc, region, ps);
        insert opp;

        RequestTask__c rt = createRequestTask(opp);
        insert rt;

        BulkApprovalAction.Input param = new BulkApprovalAction.Input();
        param.recordIds = new List<Id>();
        param.recordIds.add(rt.Id);
        List<BulkApprovalAction.Result> result = new List<BulkApprovalAction.Result>();

        // 承認申請を実行
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(rt.Id);
        Approval.ProcessResult processResult = Approval.process(req);

        result = BulkApprovalAction.bulkApproval(new List<BulkApprovalAction.Input>{ param });
        Assert.areEqual(result.get(0).success, true);
    }

    // @isTest
    // private static void testBulkApprovalFail(){

    //     // テストデータの用意
    //     Account acc = createOfficeAccount();
    //     insert acc;

    //     Region__c region = createRegion();
    //     insert region;

    //     PumpStation__c ps = createPumpStation();
    //     ps.UniqueKey__c = String.valueOf(Datetime.now()) + 'testApprovalRequest001';
    //     insert ps;

    //     Opportunity opp = createOpportunity(acc, region, ps);
    //     insert opp;

    //     RequestTask__c rt = createRequestTask(opp);
    //     insert rt;

    //     BulkApprovalAction.Input param = new BulkApprovalAction.Input();
    //     param.recordIds = new List<Id>();
    //     // 例外を発生させるために違うオブジェクトのIDを設定
    //     param.recordIds.add(acc.Id);
    //     List<BulkApprovalAction.Result> result = new List<BulkApprovalAction.Result>();

    //     // 承認申請を実行
    //     Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
    //     req.setObjectId(rt.Id);
    //     Approval.ProcessResult processResult = Approval.process(req);

    //     result = BulkApprovalAction.bulkApproval(new List<BulkApprovalAction.Input>{ param });
    //     Assert.areEqual(result.get(0).success, false);
    // }

    /**
     * レコードタイプが事業所(Office)の取引先作成
     * @return 取引先
     */
    private static Account createOfficeAccount(){

        // レコードタイプIDを取得
        Schema.DescribeSObjectResult result = Account.SObjectType.getDescribe();
        List<Schema.RecordTypeInfo> recTypeInfo = result.getRecordTypeInfos();
        String recTypeOfficeId = '';
        for(Schema.RecordTypeInfo info : recTypeInfo){
            if(info.getDeveloperName() == 'Office'){
                recTypeOfficeId = info.getRecordTypeId();
            }
            if(!String.isBlank(recTypeOfficeId)){
                break;
            }
        }

        Account acc = new Account(
            Name = 'テスト取引先',
            RecordTypeId = recTypeOfficeId
        );
        return acc;
    }

    /**
     * 地域マスタ作成
     * @return 地域マスタ
     */
    private static Region__c createRegion(){

        Region__c region = new Region__c(
            Name = 'テスト地域マスタ'
        );
        return region;
    }

    /**
     * 機場作成
     * @return 機場
     */
    private static PumpStation__c createPumpStation(){

        PumpStation__c ps = new PumpStation__c(
            Name = '機場'
        );
        return ps;
    }

    /**
     * 案件作成
     * @param Account acc
     * @param Region__c region
     * @return 案件
     */
    private static Opportunity createOpportunity(Account acc, Region__c region, PumpStation__c ps){

        Opportunity opp = new Opportunity(
            Name = 'テスト案件',
            AccountId = acc.Id,
            StageName = '基本計画',
            OrderExpectation__c = '1',
            Region__c = region.Id,
            BU__c = '水環境',
            SBU__c = '上水',
            Plant__c = '上水既存',
            CloseDate = Date.today(),
            ScheduledSalesDate__c = Date.today(),
            NeedConstruction__c = '無',
            KOUJI_SYU__c = '電気工事',
            UKE_KBN__c = '元請',
            ConstructionDistinction__c = '新設',
            Handling__c = '直扱',
            DemandOf__c = '官需',
            InformationFrom__c = '施主',
            DemanDepartment__c = '官公庁',
            ExportCategory__c = '0 国内',
            PumpStation__c = ps.Id
        );
        return opp;
    }

    /**
     * 依頼タスク作成
     * @param Opportunity opp
     * @return 依頼タスク
     */
    private static RequestTask__c createRequestTask(Opportunity opp){
        // 販事ユーザを作成
        User u = createUser('販事');
        insert u;

        RequestTask__c rt = new RequestTask__c(
            Name = 'テスト依頼タスク件名',
            Status__c = '依頼作成',
            TaskCategory__c = '提案書作成依頼',
            DueDate__c = Date.today(),
            RequestDestination__c = '神電',
            DiscloseExceptRequestDestination__c = '開示不可',
            ApprovalPattern__c = '承認者手動設定',
            Opportunity__c = opp.Id,
            Requester__c = '本社　施設',
            UserDeptApproved__c = true,
            RequestApprover1__c = u.Id
        );
        return rt;
    }

    /**
     * ユーザの作成
     * @param profileName プロファイル名
     * @return ユーザ
     */
    private static User createUser(String profileName){

        // プロファイル
        Profile profile = [SELECT Id FROM Profile WHERE Name = :profileName LIMIT 1];

        // ユーザ
        User objUser = new User();
        objUser.FirstName = 'test';                                             // 名
        objUser.LastName = 'test';                                              // 姓
        objUser.Email = String.valueOf(Date.today()) + '@example.co.jp';      // メール
        objUser.UserName = objUser.Email;                                       // ユーザ名
        objUser.EmailEncodingKey = 'UTF-8';                                     // メールの文字コード
        objUser.Alias = 'test'+String.valueOf(Datetime.now().second());                    // 別名
        objUser.TimeZoneSidKey = 'Asia/Tokyo';                                  // タイムゾーン
        objUser.LocaleSidKey = 'ja_JP';                                         // 地域
        objUser.LanguageLocaleKey = 'ja';                                       // 言語
        objUser.ProfileId = profile.Id;                                         // プロファイルID
        objUser.isActive = true;
        objUser.Division = '本社　施設・二';
        return objUser;
    }
}