force-app/main/default/objects/Opportunity/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>最終顧客が不明の場合は「不明」、未定の場合は「未定」を選択ください。</inlineHelpText>
    <label>最終顧客</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>登録/選択した取引先が事業所レコードタイプではありません。
取引先を新規作成する場合は、事業所として登録してください。</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>事業所</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>案件 (最終顧客)</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ConstructionDistinction__c.field-meta.xml
<CustomField>
    <fullName>ConstructionDistinction__c</fullName>
    <label>工事区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新設</fullName>
            </value>
            <value>
                <fullName>更新（自社既設）</fullName>
            </value>
            <value>
                <fullName>更新（他社既設）</fullName>
            </value>
            <value>
                <fullName>更新（蓄電池）</fullName>
            </value>
            <value>
                <fullName>増設</fullName>
            </value>
            <value>
                <fullName>修繕・改造</fullName>
            </value>
            <value>
                <fullName>保守</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>新設（建屋新設）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋新設）</label>
            </value>
            <value>
                <fullName>新設（建屋既存）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋既存）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/RequestTask__c.object-meta.xml
<CustomObject>
    <label>依頼タスク</label>
    <nameField>
        <label>依頼タスク件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestTask__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>希望回答期限</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>案件</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>依頼タスク</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/RequestDestination__c.field-meta.xml
<CustomField>
    <fullName>RequestDestination__c</fullName>
    <label>依頼先</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TaskCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>神電</fullName>
            </value>
            <value>
                <fullName>伊電</fullName>
            </value>
            <value>
                <fullName>配電</fullName>
            </value>
            <value>
                <fullName>プラ建</fullName>
            </value>
            <value>
                <fullName>C電</fullName>
            </value>
            <value>
                <fullName>力電</fullName>
            </value>
            <value>
                <fullName>系電</fullName>
            </value>
            <value>
                <fullName>通電</fullName>
            </value>
            <value>
                <fullName>鎌電</fullName>
            </value>
            <value>
                <fullName>IS統</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
                <isActive>false</isActive>
                <label>その他</label>
            </value>
            <value>
                <fullName>・・・</fullName>
                <isActive>false</isActive>
                <label>・・・</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/RequestDestination_other__c.field-meta.xml
<CustomField>
    <fullName>RequestDestination_other__c</fullName>
    <label>依頼先場所（依頼先で「その他」を選択した場合は入力ください）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <defaultValue>$User.Division</defaultValue>
    <label>依頼元</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>本社　通シ</fullName>
            </value>
            <value>
                <fullName>本社　通シ・管理</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ一</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ二</fullName>
            </value>
            <value>
                <fullName>本社　施設</fullName>
            </value>
            <value>
                <fullName>本社　施設・一</fullName>
            </value>
            <value>
                <fullName>本社　施設・二</fullName>
            </value>
            <value>
                <fullName>本社　施設・三</fullName>
            </value>
            <value>
                <fullName>本社　施設・DC</fullName>
            </value>
            <value>
                <fullName>本社　施設・販企</fullName>
            </value>
            <value>
                <fullName>本社　社シ一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・P推</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・二</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・三</fullName>
            </value>
            <value>
                <fullName>本社　社シ二</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・企政</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・建防</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・道路</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・S監</fullName>
            </value>
            <value>
                <fullName>本社　官公</fullName>
            </value>
            <value>
                <fullName>本社　官公・一</fullName>
            </value>
            <value>
                <fullName>本社　官公・二</fullName>
            </value>
            <value>
                <fullName>本社　海Ｆシ</fullName>
            </value>
            <value>
                <fullName>本社　社環計</fullName>
            </value>
            <value>
                <fullName>本社　社環計・企画</fullName>
            </value>
            <value>
                <fullName>本社　社環計・業務</fullName>
            </value>
            <value>
                <fullName>本社　社環計・品証</fullName>
            </value>
            <value>
                <fullName>本社　社環計・輸管</fullName>
            </value>
            <value>
                <fullName>本社　事管推</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/TaskCategory__c.field-meta.xml
<CustomField>
    <fullName>TaskCategory__c</fullName>
    <label>依頼区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>提案書作成依頼</fullName>
            </value>
            <value>
                <fullName>見積照会</fullName>
            </value>
            <value>
                <fullName>原低依頼</fullName>
            </value>
            <value>
                <fullName>写真撮影依頼</fullName>
            </value>
            <value>
                <fullName>搬入依頼</fullName>
            </value>
            <value>
                <fullName>技派依頼</fullName>
            </value>
            <value>
                <fullName>製作所技術者選定依頼</fullName>
            </value>
            <value>
                <fullName>先行手配依頼</fullName>
            </value>
            <value>
                <fullName>技術者配置依頼</fullName>
            </value>
            <value>
                <fullName>その他依頼</fullName>
                <isActive>false</isActive>
                <label>その他依頼</label>
            </value>
            <value>
                <fullName>仕様承諾通知</fullName>
                <isActive>false</isActive>
                <label>仕様承諾通知</label>
            </value>
            <value>
                <fullName>原低依頼(工事)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(工事)</label>
            </value>
            <value>
                <fullName>原低依頼(製作所)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(製作所)</label>
            </value>
            <value>
                <fullName>図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>図面作成依頼</label>
            </value>
            <value>
                <fullName>完成図書作成依頼</fullName>
                <isActive>false</isActive>
                <label>完成図書作成依頼</label>
            </value>
            <value>
                <fullName>工事コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>工事コスト積算依頼</label>
            </value>
            <value>
                <fullName>工事図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>工事図面作成依頼</label>
            </value>
            <value>
                <fullName>工場立会検査調整</fullName>
                <isActive>false</isActive>
                <label>工場立会検査調整</label>
            </value>
            <value>
                <fullName>搬入調整依頼</fullName>
                <isActive>false</isActive>
                <label>搬入調整依頼</label>
            </value>
            <value>
                <fullName>搬入連絡</fullName>
                <isActive>false</isActive>
                <label>搬入連絡</label>
            </value>
            <value>
                <fullName>施工図作成依頼</fullName>
                <isActive>false</isActive>
                <label>施工図作成依頼</label>
            </value>
            <value>
                <fullName>機器搬入依頼</fullName>
                <isActive>false</isActive>
                <label>機器搬入依頼</label>
            </value>
            <value>
                <fullName>現地作業員調整依頼</fullName>
                <isActive>false</isActive>
                <label>現地作業員調整依頼</label>
            </value>
            <value>
                <fullName>現地試験成績書作成依頼</fullName>
                <isActive>false</isActive>
                <label>現地試験成績書作成依頼</label>
            </value>
            <value>
                <fullName>納入仕様書・竣工図修正依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書・竣工図修正依頼</label>
            </value>
            <value>
                <fullName>納入仕様書作成依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書作成依頼</label>
            </value>
            <value>
                <fullName>納期変更依頼</fullName>
                <isActive>false</isActive>
                <label>納期変更依頼</label>
            </value>
            <value>
                <fullName>製作所コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>製作所コスト積算依頼</label>
            </value>
            <value>
                <fullName>試験要領書作成依頼</fullName>
                <isActive>false</isActive>
                <label>試験要領書作成依頼</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RequestFormOutputControllerTest.cls
@isTest public with sharing class RequestFormOutputControllerTest {
    /**
     * 依頼タスク帳票出力処理テスト
     * @description Lightning コンポーネントから Apex メソッドへアクセスするためだけのクラス・メソッドにつき、コードカバーのみを目的とする。
     */
    @isTest private static void requestFormOutputTest() {
        // preparation
        String result;
        String errorMessage;

        Account account = new Account(
            Name = 'Test Account'
            , Type = 'エンドユーザー'

            // insertに必要な項目
            , RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND name = '事業所'].Id
        );
        insert account;

        Opportunity opportunity = new Opportunity(
            // insertに必要な項目
            AccountId = account.Id
            , CloseDate = Date.newInstance(2000, 1, 2)
            , Name = 'Test Opp'
            , Client__c = account.Id
            , StageName = '基本計画'
            , ConstructionDistinction__c = '新設'
        );
        insert opportunity;

        RequestTask__c requestTask = new RequestTask__c(
            // insertに必要な項目
            DueDate__c = Date.newInstance(2025, 5, 10)
            , Requester__c = '本社　施設'
            , RequestDestination__c = 'その他'
            , RequestDestination_other__c = 'テスト依頼先場所'
            , TaskCategory__c = '提案書作成依頼'
            , Opportunity__c = opportunity.Id
        );
        insert requestTask;

        Test.setMock(HttpCalloutMock.class, new SvfTokenHttpCalloutMock(false, 401));

        // execution
        Test.startTest();
        try {
            result = RequestFormOutputController.requestFormOutput(requestTask.Id);
        } catch(Exception e) {
            errorMessage = e.getMessage();
        }
        Test.stopTest();

        // assertion
        System.assert(String.isNotEmpty(errorMessage), '例外が発生するようにテストメソッドを修正してください。');
    }
}