force-app/main/default/objects/Opportunity/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>最終顧客が不明の場合は「不明」、未定の場合は「未定」を選択ください。</inlineHelpText>
    <label>最終顧客</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>登録/選択した取引先が事業所レコードタイプではありません。
取引先を新規作成する場合は、事業所として登録してください。</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>事業所</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>案件 (最終顧客)</relationshipLabel>
    <relationshipName>Client</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/ConstructionDistinction__c.field-meta.xml
<CustomField>
    <fullName>ConstructionDistinction__c</fullName>
    <label>工事区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>新設</fullName>
            </value>
            <value>
                <fullName>更新（自社既設）</fullName>
            </value>
            <value>
                <fullName>更新（他社既設）</fullName>
            </value>
            <value>
                <fullName>更新（蓄電池）</fullName>
            </value>
            <value>
                <fullName>増設</fullName>
            </value>
            <value>
                <fullName>修繕・改造</fullName>
            </value>
            <value>
                <fullName>保守</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>新設（建屋新設）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋新設）</label>
            </value>
            <value>
                <fullName>新設（建屋既存）</fullName>
                <isActive>false</isActive>
                <label>新設（建屋既存）</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EstimatedIssuedDate_01__c.field-meta.xml
<CustomField>
    <fullName>EstimatedIssuedDate_01__c</fullName>
    <label>発行予定日①</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/RequestTask__c.object-meta.xml
<CustomObject>
    <label>依頼タスク</label>
    <nameField>
        <label>依頼タスク件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RequestTask__c/fields/DocumentOutputFlag__c.field-meta.xml
<CustomField>
    <fullName>DocumentOutputFlag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>帳票出力済みフラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/DueDate__c.field-meta.xml
<CustomField>
    <fullName>DueDate__c</fullName>
    <label>希望回答期限</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>案件</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>依頼タスク</relationshipLabel>
    <relationshipName>Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/RequestDestination__c.field-meta.xml
<CustomField>
    <fullName>RequestDestination__c</fullName>
    <label>依頼先</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TaskCategory__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>神電</fullName>
            </value>
            <value>
                <fullName>伊電</fullName>
            </value>
            <value>
                <fullName>配電</fullName>
            </value>
            <value>
                <fullName>プラ建</fullName>
            </value>
            <value>
                <fullName>C電</fullName>
            </value>
            <value>
                <fullName>力電</fullName>
            </value>
            <value>
                <fullName>系電</fullName>
            </value>
            <value>
                <fullName>通電</fullName>
            </value>
            <value>
                <fullName>鎌電</fullName>
            </value>
            <value>
                <fullName>IS統</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
                <isActive>false</isActive>
                <label>その他</label>
            </value>
            <value>
                <fullName>・・・</fullName>
                <isActive>false</isActive>
                <label>・・・</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/RequestDestination_other__c.field-meta.xml
<CustomField>
    <fullName>RequestDestination_other__c</fullName>
    <label>依頼先場所（依頼先で「その他」を選択した場合は入力ください）</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/Requester__c.field-meta.xml
<CustomField>
    <fullName>Requester__c</fullName>
    <defaultValue>$User.Division</defaultValue>
    <label>依頼元</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>本社　通シ</fullName>
            </value>
            <value>
                <fullName>本社　通シ・管理</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ一</fullName>
            </value>
            <value>
                <fullName>本社　通シ・通シ二</fullName>
            </value>
            <value>
                <fullName>本社　施設</fullName>
            </value>
            <value>
                <fullName>本社　施設・一</fullName>
            </value>
            <value>
                <fullName>本社　施設・二</fullName>
            </value>
            <value>
                <fullName>本社　施設・三</fullName>
            </value>
            <value>
                <fullName>本社　施設・DC</fullName>
            </value>
            <value>
                <fullName>本社　施設・販企</fullName>
            </value>
            <value>
                <fullName>本社　社シ一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・P推</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・一</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・二</fullName>
            </value>
            <value>
                <fullName>本社　社シ一・三</fullName>
            </value>
            <value>
                <fullName>本社　社シ二</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・企政</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・建防</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・道路</fullName>
            </value>
            <value>
                <fullName>本社　社シ二・S監</fullName>
            </value>
            <value>
                <fullName>本社　官公</fullName>
            </value>
            <value>
                <fullName>本社　官公・一</fullName>
            </value>
            <value>
                <fullName>本社　官公・二</fullName>
            </value>
            <value>
                <fullName>本社　海Ｆシ</fullName>
            </value>
            <value>
                <fullName>本社　社環計</fullName>
            </value>
            <value>
                <fullName>本社　社環計・企画</fullName>
            </value>
            <value>
                <fullName>本社　社環計・業務</fullName>
            </value>
            <value>
                <fullName>本社　社環計・品証</fullName>
            </value>
            <value>
                <fullName>本社　社環計・輸管</fullName>
            </value>
            <value>
                <fullName>本社　事管推</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/RequestTask__c/fields/TaskCategory__c.field-meta.xml
<CustomField>
    <fullName>TaskCategory__c</fullName>
    <label>依頼区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>提案書作成依頼</fullName>
            </value>
            <value>
                <fullName>見積照会</fullName>
            </value>
            <value>
                <fullName>原低依頼</fullName>
            </value>
            <value>
                <fullName>写真撮影依頼</fullName>
            </value>
            <value>
                <fullName>搬入依頼</fullName>
            </value>
            <value>
                <fullName>技派依頼</fullName>
            </value>
            <value>
                <fullName>製作所技術者選定依頼</fullName>
            </value>
            <value>
                <fullName>先行手配依頼</fullName>
            </value>
            <value>
                <fullName>技術者配置依頼</fullName>
            </value>
            <value>
                <fullName>その他依頼</fullName>
                <isActive>false</isActive>
                <label>その他依頼</label>
            </value>
            <value>
                <fullName>仕様承諾通知</fullName>
                <isActive>false</isActive>
                <label>仕様承諾通知</label>
            </value>
            <value>
                <fullName>原低依頼(工事)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(工事)</label>
            </value>
            <value>
                <fullName>原低依頼(製作所)</fullName>
                <isActive>false</isActive>
                <label>原低依頼(製作所)</label>
            </value>
            <value>
                <fullName>図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>図面作成依頼</label>
            </value>
            <value>
                <fullName>完成図書作成依頼</fullName>
                <isActive>false</isActive>
                <label>完成図書作成依頼</label>
            </value>
            <value>
                <fullName>工事コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>工事コスト積算依頼</label>
            </value>
            <value>
                <fullName>工事図面作成依頼</fullName>
                <isActive>false</isActive>
                <label>工事図面作成依頼</label>
            </value>
            <value>
                <fullName>工場立会検査調整</fullName>
                <isActive>false</isActive>
                <label>工場立会検査調整</label>
            </value>
            <value>
                <fullName>搬入調整依頼</fullName>
                <isActive>false</isActive>
                <label>搬入調整依頼</label>
            </value>
            <value>
                <fullName>搬入連絡</fullName>
                <isActive>false</isActive>
                <label>搬入連絡</label>
            </value>
            <value>
                <fullName>施工図作成依頼</fullName>
                <isActive>false</isActive>
                <label>施工図作成依頼</label>
            </value>
            <value>
                <fullName>機器搬入依頼</fullName>
                <isActive>false</isActive>
                <label>機器搬入依頼</label>
            </value>
            <value>
                <fullName>現地作業員調整依頼</fullName>
                <isActive>false</isActive>
                <label>現地作業員調整依頼</label>
            </value>
            <value>
                <fullName>現地試験成績書作成依頼</fullName>
                <isActive>false</isActive>
                <label>現地試験成績書作成依頼</label>
            </value>
            <value>
                <fullName>納入仕様書・竣工図修正依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書・竣工図修正依頼</label>
            </value>
            <value>
                <fullName>納入仕様書作成依頼</fullName>
                <isActive>false</isActive>
                <label>納入仕様書作成依頼</label>
            </value>
            <value>
                <fullName>納期変更依頼</fullName>
                <isActive>false</isActive>
                <label>納期変更依頼</label>
            </value>
            <value>
                <fullName>製作所コスト積算依頼</fullName>
                <isActive>false</isActive>
                <label>製作所コスト積算依頼</label>
            </value>
            <value>
                <fullName>試験要領書作成依頼</fullName>
                <isActive>false</isActive>
                <label>試験要領書作成依頼</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/RequestFormOutputLogicTest.cls
@isTest public with sharing class RequestFormOutputLogicTest {
    /**
     * @description 依頼区分に応じた処理実行テスト
     */
    private static void executeByTaskCategoryTest(String taskCategory) {
        Account account = new Account(
            Name = 'Test Account'
            , Type = 'エンドユーザー'

            // insertに必要な項目
            , RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND name = '事業所'].Id
        );
        insert account;

        Opportunity opportunity = new Opportunity(
            // insertに必要な項目
            AccountId = account.Id
            , CloseDate = Date.newInstance(2000, 1, 2) // OpportunityTriggerHandler.setOppItem で EstimatedIssuedDate_01__c に設定される。
            , Name = 'Test Opp'
            , Client__c = account.Id
            , StageName = '基本計画'
            , ConstructionDistinction__c = '新設'
        );
        insert opportunity;

        RequestTask__c requestTask = new RequestTask__c(
            // insertに必要な項目
            DueDate__c = Date.newInstance(2025, 5, 10)
            , Requester__c = '本社　施設'
            , RequestDestination__c = 'その他'
            , RequestDestination_other__c = 'テスト依頼先場所'
            , TaskCategory__c = taskCategory
            , Opportunity__c = opportunity.Id
        );
        insert requestTask;
        RequestFormOutputGenerator.getRequestTask(requestTask.Id);

        // execution
        Test.startTest();
        RequestFormOutputLogic.executeByTaskCategory(taskCategory, requestTask.Id);
        Test.stopTest();
    }

    /** 提案書作成依頼 */
    @isTest private static void executeByTaskCategoryTest1() {
        executeByTaskCategoryTest('提案書作成依頼');

        // assertion
        System.assertEquals('①提案業務依頼書', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 見積照会 */
    @isTest private static void executeByTaskCategoryTest2() {
        executeByTaskCategoryTest('見積照会');

        // assertion
        System.assertEquals('②見積照会書', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 写真撮影依頼 */
    @isTest private static void executeByTaskCategoryTest3() {
        executeByTaskCategoryTest('写真撮影依頼');

        // assertion
        System.assertEquals('③写真撮影依頼書', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 搬入依頼 */
    @isTest private static void executeByTaskCategoryTest4() {
        executeByTaskCategoryTest('搬入依頼');

        // assertion
        System.assertEquals('④機器搬入連絡表', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 技派依頼 */
    @isTest private static void executeByTaskCategoryTest5() {
        executeByTaskCategoryTest('技派依頼');

        // assertion
        System.assertEquals('⑤技術員派遣依頼書', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 製作所技術者選定依頼 */
    @isTest private static void executeByTaskCategoryTest6() {
        executeByTaskCategoryTest('製作所技術者選定依頼');

        // assertion
        System.assertEquals('⑥配置技術者選定依頼', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 先行手配依頼 */
    @isTest private static void executeByTaskCategoryTest7() {
        executeByTaskCategoryTest('先行手配依頼');

        // assertion
        System.assertEquals('⑦先行手配依頼書', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** 原低依頼 */
    @isTest private static void executeByTaskCategoryTest8() {
        executeByTaskCategoryTest('原低依頼');

        // assertion
        System.assertEquals('⑧原低依頼書', RequestFormOutputLogic.formName, '依頼区分に応じた処理実行が不正です。');
        System.assertNotEquals(null, RequestFormOutputLogic.inputCsv, '依頼区分に応じた処理実行が不正です。');
    }

    /** VRSetForm関数設定テスト */
    @isTest private static void vrSetFormTest() {
        // preparation
        String result;

        // execution
        result = RequestFormOutputLogic.vrSetForm('test.xlsx');

        // assertion
        System.assertEquals('<start>\r\nVrSetForm=form/依頼タスク/test.xlsx\r\n<end>\r\n', result, 'VRSetForm関数設定が不正です。');
    }

    /**
     * @description ファイル名設定処理テスト
     * "SVF雛形_”&"案件名_"&"帳票名_"&"yyyyMMdd"
     */
    @isTest private static void setFileNameTest() {
        // execution
        Test.startTest();
        RequestFormOutputLogic.setFileName('提案書作成依頼', 'テスト案件');
        Test.stopTest();

        // assertion
        System.assertEquals('SVF雛形_テスト案件_null_' + RequestFormOutputLogic.EXECUTED_DATE, RequestFormOutputLogic.fileName, 'ファイル名設定処理が不正です。');
    }

    /**
     * @description ファイルフォーマット設定処理テスト
     */
    private static void setFileFormatTest(String taskCategory) {
        // execution
        Test.startTest();
        RequestFormOutputLogic.setFileFormat(taskCategory);
        Test.stopTest();
    }

    /** 提案書作成依頼 */
    @isTest private static void setFileFormatTest1() {
        setFileFormatTest('提案書作成依頼');

        // assertion
        System.assertEquals('WORD', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.docx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 見積照会 */
    @isTest private static void setFileFormatTest2() {
        setFileFormatTest('見積照会');

        // assertion
        System.assertEquals('EXCEL', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.xlsx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 写真撮影依頼書 */
    @isTest private static void setFileFormatTest3() {
        setFileFormatTest('写真撮影依頼');

        // assertion
        System.assertEquals('EXCEL', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.xlsm', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 機器搬入連絡表 */
    @isTest private static void setFileFormatTest4() {
        setFileFormatTest('搬入依頼');

        // assertion
        System.assertEquals('EXCEL', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.xlsx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 技術員派遣依頼書 */
    @isTest private static void setFileFormatTest5() {
        setFileFormatTest('技派依頼');

        // assertion
        System.assertEquals('WORD', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.docx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 配置技術者選定依頼 */
    @isTest private static void setFileFormatTest6() {
        setFileFormatTest('製作所技術者選定依頼');

        // assertion
        System.assertEquals('EXCEL', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.xlsx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 先行手配依頼書 */
    @isTest private static void setFileFormatTest7() {
        setFileFormatTest('先行手配依頼');

        // assertion
        System.assertEquals('EXCEL', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.xlsx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /** 原低依頼書 */
    @isTest private static void setFileFormatTest8() {
        setFileFormatTest('原低依頼');

        // assertion
        System.assertEquals('EXCEL', RequestFormOutputLogic.fileFormat, 'ファイルフォーマット設定処理が不正です。');
        System.assertEquals('.xlsx', RequestFormOutputLogic.extention, 'ファイルフォーマット設定処理が不正です。');
    }

    /**
     * @description 帳票出力済みフラグが更新されていることのテスト
     */
    @isTest private static void updateDocumentOutputFlagTest(){
        Account account = new Account(
            Name = 'Test Account'
            , Type = 'エンドユーザー'

            // insertに必要な項目
            , RecordTypeId = [SELECT Id FROM RecordType WHERE SobjectType = 'Account' AND name = '事業所'].Id
        );
        insert account;

        Opportunity opportunity = new Opportunity(
            // insertに必要な項目
            AccountId = account.Id
            , CloseDate = Date.newInstance(2000, 1, 2) // OpportunityTriggerHandler.setOppItem で EstimatedIssuedDate_01__c に設定される。
            , Name = 'Test Opp'
            , Client__c = account.Id
            , StageName = '基本計画'
            , ConstructionDistinction__c = '新設'
        );
        insert opportunity;

        RequestTask__c requestTask = new RequestTask__c(
            // insertに必要な項目
            DueDate__c = Date.newInstance(2025, 5, 10)
            , Requester__c = '本社　施設'
            , RequestDestination__c = 'その他'
            , RequestDestination_other__c = 'テスト依頼先場所'
            , TaskCategory__c = '提案書作成依頼'
            , Opportunity__c = opportunity.Id
        );
        insert requestTask;

        // execution
        Test.startTest();
        RequestFormOutputGenerator.updateRequestTaskById(requestTask.Id);
        Test.stopTest();

        // フラグの更新は非同期で実行されるため再度クエリ発行
        RequestTask__c rt = [SELECT DocumentOutputFlag__c FROM RequestTask__c WHERE Id = :requestTask.Id LIMIT 1];
        System.assertEquals(true, rt.DocumentOutputFlag__c, '帳票出力済みフラグが更新されていません。');
    }
}