force-app/main/default/objects/Factory__c/Factory__c.object-meta.xml
<CustomObject>
    <label>場所別</label>
    <nameField>
        <displayFormat>MFG-{0000000}</displayFormat>
        <label>場所別番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Factory__c/fields/CopyBaseNo_txt__c.field-meta.xml
<CustomField>
    <fullName>CopyBaseNo_txt__c</fullName>
    <label>場所別コピー元番号（テキスト）</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Factory__c/fields/Factory__c.field-meta.xml
<CustomField>
    <fullName>Factory__c</fullName>
    <label>製作所</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>神電</fullName>
            </value>
            <value>
                <fullName>神電横浜(鎌IS統）</fullName>
            </value>
            <value>
                <fullName>伊電長崎</fullName>
            </value>
            <value>
                <fullName>本プラ建</fullName>
            </value>
            <value>
                <fullName>北プラ建</fullName>
            </value>
            <value>
                <fullName>中プラ建</fullName>
            </value>
            <value>
                <fullName>西プラ建</fullName>
            </value>
            <value>
                <fullName>九プラ建</fullName>
            </value>
            <value>
                <fullName>伊電</fullName>
            </value>
            <value>
                <fullName>配電</fullName>
            </value>
            <value>
                <fullName>系電</fullName>
            </value>
            <value>
                <fullName>力電</fullName>
            </value>
            <value>
                <fullName>通電</fullName>
            </value>
            <value>
                <fullName>鎌電</fullName>
            </value>
            <value>
                <fullName>名電</fullName>
            </value>
            <value>
                <fullName>京電</fullName>
            </value>
            <value>
                <fullName>C電</fullName>
            </value>
            <value>
                <fullName>MPEC東</fullName>
            </value>
            <value>
                <fullName>MPEC中</fullName>
            </value>
            <value>
                <fullName>MPEC西</fullName>
            </value>
            <value>
                <fullName>MPEC九</fullName>
            </value>
            <value>
                <fullName>MEBS</fullName>
            </value>
            <value>
                <fullName>MEE</fullName>
            </value>
            <value>
                <fullName>他社品調達</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/EstimatedIssuedDate_01__c.field-meta.xml
<CustomField>
    <fullName>EstimatedIssuedDate_01__c</fullName>
    <label>発行予定日①</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/factory__c.field-meta.xml
<CustomField>
    <fullName>factory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>場所別</label>
    <referenceTo>Factory__c</referenceTo>
    <relationshipLabel>案件</relationshipLabel>
    <relationshipName>FactoryProducts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ProductSpecification__c/ProductSpecification__c.object-meta.xml
<CustomObject>
    <label>機器仕様</label>
    <nameField>
        <displayFormat>PD-{0000000}</displayFormat>
        <label>機器仕様番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductSpecification__c/fields/FactoryRelationNo__c.field-meta.xml
<CustomField>
    <fullName>FactoryRelationNo__c</fullName>
    <label>場所別関連元番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ProductSpecification__c/fields/Factorys__c.field-meta.xml
<CustomField>
    <fullName>Factorys__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>場所別</label>
    <referenceTo>Factory__c</referenceTo>
    <relationshipLabel>機器仕様</relationshipLabel>
    <relationshipName>Factorys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QuoteBiddingInquiry__c/QuoteBiddingInquiry__c.object-meta.xml
<CustomObject>
    <label>見積・応札・手数料伺い</label>
    <nameField>
        <label>伺い件名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/RecordCloneSetting__mdt/RecordCloneSetting__mdt.object-meta.xml
<CustomObject>
    <description>RecordCloneの設定を保持する</description>
    <label>RecordClone設定</label>
</CustomObject>

force-app/main/default/objects/RecordCloneSetting__mdt/fields/value__c.field-meta.xml
<CustomField>
    <fullName>value__c</fullName>
    <label>値</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/RecordCloneHandler.cls
public class RecordCloneHandler {

    // TODO: error handling, try catch.
    public static sObject getOriginalRecord(Id recordId, sObjectSummary sObjSummary) {

        // concatenate clonable field names of child sObjects to build SOQL string
        String childrenSelect = '';
        if(sObjSummary.children != null && sObjSummary.children.size() > 0) {
            for (String childRelName : sObjSummary.children.keySet()){
                sObjectSummary child = sObjSummary.children.get(childRelName);
                List<String> childFields = child.filterClonableFields();
                if(child.isClonable && childFields.size() > 0) {
                    childrenSelect += ', ( SELECT Id, ' + String.join(childFields, ',') + ' FROM ' + childRelName + ' )';
                }
            }
        }
        // Build query string
        String q = 'SELECT Id, ' + String.join(sObjSummary.filterClonableFields(), ',') + childrenSelect + ' FROM ' + sObjSummary.apiName + ' WHERE Id = \'' + recordId + '\'';
        return Database.query(q);
    }

    public static sObject cloneRecord(sObject cloned, sObjectSummary sObjectSummary, String newRecordName) {

        // TODO: try catch error handling

        // remove original record ID, then insert.
        cloned.Id = null;
        if(sObjectSummary.isNamable) {
            cloned.put(sObjectSummary.nameField, newRecordName);
        }
        if(('Opportunity').equals(String.valueOf(cloned.getSObjectType()))){
            cloned.put('StageName', '基本計画');
            cloned.put('EstimatedIssuedDate_01__c', null);
            // cloned.put('CloseDate', Date.today().AddYears(1)); //コピー時に空欄にするよう仕様変更（売上予定日と合わせる）
        }
        insert cloned;

        if(sObjectSummary.children != null && sObjectSummary.children.keySet().size() > 0) {

            // append to child records' name fields
            String todayStr = Datetime.now().format('yyyy/MM/dd');

            // remove child record IDs, assign then cloned parent record Id to ref field
            for(String childRelName : sObjectSummary.children.keySet()) {
                sObjectSummary childSummary = sObjectSummary.children.get(childRelName);

                if(!childSummary.isClonable) continue;
                sObject[] children;
                try {
                    children = cloned.getSObjects(childRelName);
                } catch(System.SObjectException e) {
                    // TODO : handle error with proper exception class.
                    continue;
                }
                if(children == null) continue;

                // On creating an opportunity record, system automatically creates an OpportunityContactRole record.
                // Delete the created record as of now.
                if(sObjectSummary.apiName == 'Opportunity' && childRelName == 'OpportunityContactRoles') {
                    OpportunityContactRole[] ocrs = [SELECT Id FROM OpportunityContactRole WHERE OpportunityId = :cloned.Id];
                    delete ocrs;
                }

                for(Integer i = 0; i < children.size(); i++) {
                    children[i].put('Id', null);
                    if(childSummary.isNamable) {
                        String currentNameValue = (String) children[i].get(childSummary.nameField);
                        //20241212 oh 見積・応札・手数料伺いコピーの分岐判断を追加する
                        if(('QuoteBiddingInquiry__c').equals(String.valueOf(cloned.getSObjectType()))){
                            children[i].put(childSummary.nameField, currentNameValue);
                        } else {
                            children[i].put(childSummary.nameField, 'Cloned - ' + todayStr + ' : ' + currentNameValue);
                        }
                    }
                    children[i].put(childSummary.parentRelationshipField, cloned.Id);

                    // 20200117 chiba 処理追加 start
                    if(('ProductSpecification__c').equals(String.valueOf(children.getSObjectType()))){
                        children[i].put('Factorys__c', null);
                    }
                    // 20200117 chiba 処理追加 end
                }
                insert children;
            }
        }

        // TODO: 作成したオブジェクトの名前とレコード件数を返す。
        return cloned;
    }

    // 20200117 chiba 処理追加 start
    public static sObject clearRecord(sObject cloned, sObjectSummary sObjectSummary) {

        // コピーした子オブジェクトが存在するかを確認し、存在する場合、クリア処理を実施する。
        if(sObjectSummary.children != null && sObjectSummary.children.keySet().size() > 0) {

            //カスタムメタデータを取得しておく
            RecordCloneSetting__mdt[] RecordCloneSetting = [SELECT MasterLabel , value__c FROM RecordCloneSetting__mdt];

            for(String childRelName : sObjectSummary.children.keySet()) {
                sObjectSummary childSummary = sObjectSummary.children.get(childRelName);

                if(!childSummary.isClonable) continue;
                sObject[] children;
                try {
                    children = cloned.getSObjects(childRelName);
                } catch(System.SObjectException e) {
                    // TODO : handle error with proper exception class.
                    continue;
                }
                if(children == null) continue;

                //カスタム項目の型を取得する為、SObjectFieldを取得しておく
                DescribeSObjectResult sObjectDescribe = children.getSObjectType().getDescribe();
                Map<String, SObjectField> fields = sObjectDescribe.fields.getMap();

                for(sObject child : children) {
                    if(RecordCloneSetting.isEmpty())continue;
                    //クリア処理
                    for (RecordCloneSetting__mdt rcs : RecordCloneSetting) {

                        if(String.valueOf(children.getSObjectType()).equals(rcs.MasterLabel)){
                            if(String.isBlank(rcs.value__c))continue;
                            String[] items = rcs.value__c.split(',');

                            for(String item:items){
                                if(String.isBlank(item))continue;
                                DescribeFieldResult field = fields.get(item).getDescribe();
                                Schema.DisplayType fldType = field.getType();
                                //チェック型は、nullセットでエラーとなる為、「false」を設定なしとする。
                                if(('BOOLEAN').equals(String.valueOf(fldType))){
                                    child.put(item, false);
                                }else{
                                    child.put(item, null);
                                }
                            }

                            //機器仕様の場合は、場所別の参照関係を指定する。
                            if(('ProductSpecification__c').equals(String.valueOf(children.getSObjectType()))){
                                //移行時にエラーとなるためTry-Catch追加
                                try {
                                    String FactoryRelationNo = String.valueOf(child.get('FactoryRelationNo__c'));
                                    if(String.isBlank(FactoryRelationNo))continue;
                                    ID FactoryId = null;
                                    sObject[] children_search;
                                    for(String childRelName_search : sObjectSummary.children.keySet()) {
                                        try {
                                            children_search = cloned.getSObjects(childRelName_search);
                                        } catch(System.SObjectException e) {
                                            // TODO : handle error with proper exception class.
                                            continue;
                                        }
                                        if(children_search == null)continue;
                                        for(sObject child_search : children_search) {
                                            if(('Factory__c').equals(String.valueOf(children_search.getSObjectType())) && FactoryRelationNo.equals(String.valueOf(child_search.get('CopyBaseNo_txt__c')))){
                                                FactoryId = child_search.Id;
                                            }
                                        }
                                    }
                                    child.put('Factorys__c', FactoryId);
                                //移行時にエラーとなるためTry-Catch追加
                                } catch(System.SObjectException e) {
                                // TODO : handle error with proper exception class.
                                    continue;
                                }
                            }
                        }
                    }
                }
                System.debug('◆◆◆◆upsert対象：'+children);
                upsert children;
            }
        }

        // 処理結果のフラグを返す。
        return cloned;
    }
    // 20200117 chiba 処理追加 end
}