force-app/main/default/objects/Detail__c/Detail__c.object-meta.xml
<CustomObject>
    <label>明細</label>
    <nameField>
        <label>表示用テキスト</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail__c/fields/CreditWC__c.field-meta.xml
<CustomField>
    <fullName>CreditWC__c</fullName>
    <label>WC単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/CreditWeight__c.field-meta.xml
<CustomField>
    <fullName>CreditWeight__c</fullName>
    <label>単位重量</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>見積項目</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>明細</relationshipLabel>
    <relationshipName>Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>備考</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <formula>Device__r.PriceCoefficient__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>価格係数</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/PricingTableUniqueKey__c.field-meta.xml
<CustomField>
    <fullName>PricingTableUniqueKey__c</fullName>
    <label>価格表ユニークキー</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/ProvisionUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>ProvisionUnitPrice__c</fullName>
    <label>提供単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/UnitPriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>UnitPriceCoefficient__c</fullName>
    <label>単価係数</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/WcCoefficient__c.field-meta.xml
<CustomField>
    <fullName>WcCoefficient__c</fullName>
    <label>WC係数</label>
    <precision>6</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/AgencyProvisionPriceSum__c.field-meta.xml
<CustomField>
    <fullName>AgencyProvisionPriceSum__c</fullName>
    <label>代理店提供価格合計(積み上げ)</label>
    <summarizedField>Detail__c.ProvisionPrice__c</summarizedField>
    <summaryForeignKey>Detail__c.Device__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/CreditAgencyProvisionUnitPrice__c.field-meta.xml
<CustomField>
    <fullName>CreditAgencyProvisionUnitPrice__c</fullName>
    <label>単位代理店提供単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/CreditQuoteAmount__c.field-meta.xml
<CustomField>
    <fullName>CreditQuoteAmount__c</fullName>
    <label>単位見積金額</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/CreditWC__c.field-meta.xml
<CustomField>
    <fullName>CreditWC__c</fullName>
    <label>WC単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/CreditWeight__c.field-meta.xml
<CustomField>
    <fullName>CreditWeight__c</fullName>
    <label>単位重量</label>
    <precision>10</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/GeneralAdminExpensesExistence__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdminExpensesExistence__c</fullName>
    <defaultValue>true</defaultValue>
    <label>一般管理費有無</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <formula>IF( GeneralAdminExpensesExistence__c ,PriceSum__c *  GeneralAdministrativeExpensesCopy__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般管理費</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/GeneralAdministrativeExpensesCopy__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpensesCopy__c</fullName>
    <label>一般管理費率</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MinorClassification__c.field-meta.xml
<CustomField>
    <fullName>MinorClassification__c</fullName>
    <label>小分類名</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MajorClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>66kV C-GIS</fullName>
            </value>
            <value>
                <fullName>22kV C-GIS</fullName>
            </value>
            <value>
                <fullName>ブロック(気中)キュービクル</fullName>
            </value>
            <value>
                <fullName>特高監視盤</fullName>
            </value>
            <value>
                <fullName>特高変圧器</fullName>
            </value>
            <value>
                <fullName>高圧変圧器</fullName>
            </value>
            <value>
                <fullName>変圧器収納盤</fullName>
            </value>
            <value>
                <fullName>バスダクト</fullName>
            </value>
            <value>
                <fullName>高圧コンビ盤</fullName>
            </value>
            <value>
                <fullName>高圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧盤</fullName>
            </value>
            <value>
                <fullName>現場盤</fullName>
            </value>
            <value>
                <fullName>リレー盤</fullName>
            </value>
            <value>
                <fullName>ACB盤</fullName>
            </value>
            <value>
                <fullName>200V</fullName>
            </value>
            <value>
                <fullName>400V</fullName>
            </value>
            <value>
                <fullName>共通</fullName>
            </value>
            <value>
                <fullName>3.0kV/3.3kV</fullName>
            </value>
            <value>
                <fullName>6.0kV/6.6kV</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>計装盤</fullName>
            </value>
            <value>
                <fullName>記録計</fullName>
            </value>
            <value>
                <fullName>ラック･パネル計器</fullName>
            </value>
            <value>
                <fullName>流量計</fullName>
            </value>
            <value>
                <fullName>水位計</fullName>
            </value>
            <value>
                <fullName>濃度計</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ACG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <inlineHelpText>大分類が「材料」or「システムインテグレーション費」の場合は要入力</inlineHelpText>
    <label>手入力金額設定根拠</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/OwnerBranchOffice__c.field-meta.xml
<CustomField>
    <fullName>OwnerBranchOffice__c</fullName>
    <formula>TEXT(Quote__r.PickDivision__c )</formula>
    <label>共有先の支社</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <defaultValue>1</defaultValue>
    <label>価格係数</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/PriceSum__c.field-meta.xml
<CustomField>
    <fullName>PriceSum__c</fullName>
    <formula>IF( ISNULL(CreditQuoteAmount__c)
    ,  StandardPriceSumFormula__c * PriceCoefficient__c
    , CreditQuoteAmount__c * PriceCoefficient__c
)</formula>
    <label>積算金額×価格係数</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuantityNumeric__c.field-meta.xml
<CustomField>
    <fullName>QuantityNumeric__c</fullName>
    <description>数量（Quantity__c）の入力値を数値として保持するための項目</description>
    <formula>VALUE( Quantity__c )</formula>
    <label>数量</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/SalesCostSum__c.field-meta.xml
<CustomField>
    <fullName>SalesCostSum__c</fullName>
    <formula>PriceSum__c +  GeneralAdministrativeExpenses__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>見積金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/StandardPriceSum__c.field-meta.xml
<CustomField>
    <fullName>StandardPriceSum__c</fullName>
    <label>見積金額合計(積み上げ)</label>
    <summarizedField>Detail__c.Price__c</summarizedField>
    <summaryForeignKey>Detail__c.Device__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>単位</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/WcSum__c.field-meta.xml
<CustomField>
    <fullName>WcSum__c</fullName>
    <label>WC金額(積み上げ)</label>
    <summarizedField>Detail__c.WC__c</summarizedField>
    <summaryForeignKey>Detail__c.Device__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/WeightSum__c.field-meta.xml
<CustomField>
    <fullName>WeightSum__c</fullName>
    <label>重量合計(積み上げ)</label>
    <summarizedField>Detail__c.Weight__c</summarizedField>
    <summaryForeignKey>Detail__c.Device__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/AgencyProvisionPriceSum__c.field-meta.xml
<CustomField>
    <fullName>AgencyProvisionPriceSum__c</fullName>
    <label>代理店提供価格総合計</label>
    <summarizedField>Device__c.AgencyProvisionPriceSumFormula__c</summarizedField>
    <summaryForeignKey>Device__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/external_file_url__c.field-meta.xml
<CustomField>
    <fullName>external_file_url__c</fullName>
    <label>外部ファイルURL</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <defaultValue>IF ($RecordType.Name = &quot;施設&quot;, &quot;0&quot;, &quot;&quot;)</defaultValue>
    <label>一般管理費率</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/WcSum__c.field-meta.xml
<CustomField>
    <fullName>WcSum__c</fullName>
    <label>WC金額合計</label>
    <summarizedField>Device__c.WcSumFormula__c</summarizedField>
    <summaryForeignKey>Device__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/DeviceController.cls
public with sharing class DeviceController {
    @AuraEnabled
    public static List<Device__c> getDevice(Id recordId) {
        System.debug(recordId);
        return [
            SELECT Id, Quote__c,Quote__r.PowerFrequency__c,PriceCoefficient__c,
            Quote__r.RecordType.DeveloperName,
            Quote__r.external_file_url__c,
            QuoteSpecificationNumber__c, Name, 
            toLabel(MajorClassification__c), MinorClassification__c, 
            CreditWC__c, CreditQuoteAmount__c, CreditWeight__c, 
            CreditAgencyProvisionUnitPrice__c, Note__c, WcSum__c, PriceSum__c, WeightSum__c, AgencyProvisionPriceSum__c, 
            StandardPriceSum__c, SalesCostSum__c, 
            GeneralAdministrativeExpenses__c, 
            GeneralAdministrativeExpensesCopy__c,
            OwnerBranchOffice__c,
            GeneralAdminExpensesExistence__c, QuantityNumeric__c, Unit__c,
            (select id,Name1__c,WcCoefficient__c,UnitPriceCoefficient__c,ProvisionUnitPrice__c,PricingTableUniqueKey__c from Details__r order by PricingTableUniqueKey__c)
            FROM Device__c
            WHERE Id =: recordId
        ];
    }
}