force-app/main/default/objects/Detail__c/Detail__c.object-meta.xml
<CustomObject>
    <label>明細</label>
    <nameField>
        <label>表示用テキスト</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>種類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>見積項目</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>明細</relationshipLabel>
    <relationshipName>Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/MajorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationCode__c</fullName>
    <label>大分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/MajorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationName__c</fullName>
    <label>大分類名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/MinorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationCode__c</fullName>
    <label>小分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/MinorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationName__c</fullName>
    <label>小分類名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name2__c.field-meta.xml
<CustomField>
    <fullName>Name2__c</fullName>
    <label>名称2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name3__c.field-meta.xml
<CustomField>
    <fullName>Name3__c</fullName>
    <label>名称3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name4__c.field-meta.xml
<CustomField>
    <fullName>Name4__c</fullName>
    <label>名称4</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name5__c.field-meta.xml
<CustomField>
    <fullName>Name5__c</fullName>
    <label>名称5</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name6__c.field-meta.xml
<CustomField>
    <fullName>Name6__c</fullName>
    <label>名称6</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/PricingTable__c.field-meta.xml
<CustomField>
    <fullName>PricingTable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>価格表</label>
    <referenceTo>PricingTable__c</referenceTo>
    <relationshipName>Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MinorClassification__c.field-meta.xml
<CustomField>
    <fullName>MinorClassification__c</fullName>
    <label>小分類名</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MajorClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>66kV C-GIS</fullName>
            </value>
            <value>
                <fullName>22kV C-GIS</fullName>
            </value>
            <value>
                <fullName>ブロック(気中)キュービクル</fullName>
            </value>
            <value>
                <fullName>特高監視盤</fullName>
            </value>
            <value>
                <fullName>特高変圧器</fullName>
            </value>
            <value>
                <fullName>高圧変圧器</fullName>
            </value>
            <value>
                <fullName>変圧器収納盤</fullName>
            </value>
            <value>
                <fullName>バスダクト</fullName>
            </value>
            <value>
                <fullName>高圧コンビ盤</fullName>
            </value>
            <value>
                <fullName>高圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧盤</fullName>
            </value>
            <value>
                <fullName>現場盤</fullName>
            </value>
            <value>
                <fullName>リレー盤</fullName>
            </value>
            <value>
                <fullName>ACB盤</fullName>
            </value>
            <value>
                <fullName>200V</fullName>
            </value>
            <value>
                <fullName>400V</fullName>
            </value>
            <value>
                <fullName>共通</fullName>
            </value>
            <value>
                <fullName>3.0kV/3.3kV</fullName>
            </value>
            <value>
                <fullName>6.0kV/6.6kV</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>計装盤</fullName>
            </value>
            <value>
                <fullName>記録計</fullName>
            </value>
            <value>
                <fullName>ラック･パネル計器</fullName>
            </value>
            <value>
                <fullName>流量計</fullName>
            </value>
            <value>
                <fullName>水位計</fullName>
            </value>
            <value>
                <fullName>濃度計</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ACG</fullName>
            </value>
            <value>
                <fullName>エンジン(DG)</fullName>
            </value>
            <value>
                <fullName>HDIPカメラ装置</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>機器事業部 変圧器</fullName>
                <isActive>false</isActive>
                <label>機器事業部 変圧器</label>
            </value>
            <value>
                <fullName>機器事業部 高圧コンデンサ/リアクトル</fullName>
                <isActive>false</isActive>
                <label>機器事業部 高圧コンデンサ/リアクトル</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RecordTypeOfQuote__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeOfQuote__c</fullName>
    <label>見積レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/PricingTable__c.object-meta.xml
<CustomObject>
    <label>価格表</label>
    <nameField>
        <displayFormat>K-{00000000}</displayFormat>
        <label>価格表番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PricingTable__c/fields/BU__c.field-meta.xml
<CustomField>
    <fullName>BU__c</fullName>
    <description>S：施設、M：水環境、K：官需</description>
    <inlineHelpText>S：施設、M：水環境、K：官需</inlineHelpText>
    <label>BU</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>BU</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/CategoryCode__c.field-meta.xml
<CustomField>
    <fullName>CategoryCode__c</fullName>
    <label>種類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/CharacterSymbol__c.field-meta.xml
<CustomField>
    <fullName>CharacterSymbol__c</fullName>
    <label>文字記号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/EquipmentNumber__c.field-meta.xml
<CustomField>
    <fullName>EquipmentNumber__c</fullName>
    <label>器具番号</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <label>周波数</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Frequency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MajorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationCode__c</fullName>
    <label>大分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MajorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MajorClassificationName__c</fullName>
    <label>大分類名</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MinorClassificationCode__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationCode__c</fullName>
    <label>小分類コード</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/MinorClassificationName__c.field-meta.xml
<CustomField>
    <fullName>MinorClassificationName__c</fullName>
    <label>小分類名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name3__c.field-meta.xml
<CustomField>
    <fullName>Name3__c</fullName>
    <label>名称3</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Name4__c.field-meta.xml
<CustomField>
    <fullName>Name4__c</fullName>
    <description>既存マスタに109文字のデータが存在するため名称4のみ最大文字数を拡張</description>
    <label>名称4</label>
    <length>130</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SymbolObject__mdt/SymbolObject__mdt.object-meta.xml
<CustomObject>
    <label>図記号</label>
</CustomObject>

force-app/main/default/objects/SymbolObject__mdt/fields/CharacterSymbol__c.field-meta.xml
<CustomField>
    <fullName>CharacterSymbol__c</fullName>
    <label>文字記号</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SymbolObject__mdt/fields/InstrumentSymbol__c.field-meta.xml
<CustomField>
    <fullName>InstrumentSymbol__c</fullName>
    <label>器具記号</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SymbolObject__mdt/fields/SymbolID__c.field-meta.xml
<CustomField>
    <fullName>SymbolID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <label>図記号ID</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/SymbolObject__mdt/fields/SymbolName__c.field-meta.xml
<CustomField>
    <fullName>SymbolName__c</fullName>
    <label>名称</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DetailsAddControllerTest.cls
/**
 * 明細追加画面コントローラーのテスト
 */
@isTest
public with sharing class  DetailsAddControllerTest {
    private static final String RECORDTYPE_NAME_DETAIL = '明細';
    private static final String RECORDTYPE_NAME_CHSSIS = '筐体';
    private static final String Frequency_50Hz = '50Hz';
    private static final String Frequency_60Hz = '60Hz';
    private static final String CATEGORYCODE_50Hz = '01';
    private static final String CATEGORYCODE_60Hz = '02';
    private static final List<String> BU_LIST = new List<String>{'S','K','M'};
    private static SymbolObject__mdt mdtObj = [Select Id,SymbolID__c,
                                                SymbolName__c,CharacterSymbol__c,
                                                InstrumentSymbol__c
                                            From SymbolObject__mdt 
                                            LIMIT 1];
    private static Quote__c quote;//見積
    private static Device__c dv;//見積項目
    private static Device__c dv1;//見積項目１
    private static List<PricingTable__c> tables;

    //価格表データ作成
    private static void createDate(String qRtName,String major, String minor, String powerFrequency){
        List<RecordType> recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Quote__c' and name = :qRtName];
        List<RecordType> dvType = [SELECT Id FROM RecordType WHERE SobjectType = 'Device__c' and name = :qRtName];

        //見積
        quote = new Quote__c(
            QuoteNumber__c = '1',
            PowerFrequency__c = powerFrequency,
            RecordTypeId = recType[0].Id
        );
        insert quote;
        //見積項目
        dv = new Device__c(
            Name = qRtName+ major,
            QuoteSpecificationNumber__c = '111111',
            RecordTypeOfQuote__c = qRtName,
            MajorClassification__c = major,
            MinorClassification__c = minor,
            Quote__c =quote.Id,
            RecordTypeId = dvType[0].Id
        );
        insert dv;

        //見積項目１
        dv1 = new Device__c(
            Name = qRtName+ major+'01',
            QuoteSpecificationNumber__c = '222222',
            RecordTypeOfQuote__c = qRtName,
            MajorClassification__c = major,
            MinorClassification__c = minor,
            Quote__c =quote.Id,
            RecordTypeId = dvType[0].Id
        );
        insert dv1;

        // レコードタイプ（価格表）取得
        Map<String, Id> pricingRecordTypeByName = new Map<String, Id>();
        for (RecordType rt : [SELECT Id,Name FROM RecordType WHERE SobjectType = 'PricingTable__c']) {
            pricingRecordTypeByName.put(rt.Name, rt.Id);
        }

        //登録用価格表リスト
        tables = new List<PricingTable__c>();
        Integer index = 1;
        for (String bu: BU_LIST){
            for (String rtName  : pricingRecordTypeByName.keyset()) {
                Id rtId = pricingRecordTypeByName.get(rtName);
                // 価格表
                PricingTable__c table = new PricingTable__c(
                    RecordTypeId = rtId 
                    , BU__c = bu
                    , MajorClassificationCode__c = '01'
                    , MajorClassificationName__c = major
                    , MinorClassificationCode__c = '11'
                    , MinorClassificationName__c = minor
                    , CategoryCode__c = (powerFrequency==Frequency_60Hz?'02':'01')
                    , Frequency__c = powerFrequency
                    , CharacterSymbol__c = mdtObj.CharacterSymbol__c
                    , EquipmentNumber__c = mdtObj.InstrumentSymbol__c
                    , Name1__c = 'Name1'
                    , Name2__c = 'EP=WC×2'
                    , Name3__c = 'Name3'
                    , Name4__c = 'Name4'
                    , Name5__c = 'Name5'
                    , Name6__c = 'Name6'
                    , Name7__c = 'Name7'
                    , Name8__c = 'Name8'
                    , Name9__c = 'Name9'
                    , MasterCode__c = 'MasterCode'
                    , WC__c = 1
                    , Note__c = (major=='高圧コンビ'?'note':'')
                    , RECNo__c = index
                );
                index = index + 1;
                tables.add(table);
                if (rtName == RECORDTYPE_NAME_CHSSIS) {
                    PricingTable__c table03 = new PricingTable__c(
                        RecordTypeId = rtId
                        , BU__c = bu
                        , MajorClassificationCode__c = '01'
                        , MajorClassificationName__c = major
                        , MinorClassificationCode__c = '11'
                        , MinorClassificationName__c = minor
                        , CategoryCode__c = '03'
                        , CategoryName__c ='変圧器収納盤（高圧）'
                        , Frequency__c = powerFrequency
                        , CharacterSymbol__c = mdtObj.CharacterSymbol__c
                        , EquipmentNumber__c = mdtObj.InstrumentSymbol__c
                        , Name1__c = 'Name1'
                        , Name2__c = 'EP=WC×2'
                        , Name3__c = 'Name3'
                        , Name4__c = 'Name4'
                        , Name5__c = 'Name5'
                        , Name6__c = 'Name6'
                        , Name7__c = 'Name7'
                        , Name8__c = 'Name8'
                        , Name9__c = 'Name9'
                        , MasterCode__c = 'MasterCode'
                        , WC__c = 1
                        , RECNo__c = 9
                    );
                    tables.add(table03);
                }
            }
        }
        if (tables.size() > 0) insert tables;
    }

    //図記号画面の一覧
    @isTest static void getSymbolObjectRecordsTest() {
        String qRtName='施設';
        String major='変圧器';
        String minor='高圧変圧器';
        String powerFrequency='60Hz';

        createDate(qRtName,major, minor, powerFrequency);
        Test.startTest();
        //図記号画面の一覧を検索する
        String str =  DetailsAddController.getSymbolObjectRecords();

        //図検索
        String strImage = DetailsAddController.getPricingTableRecordsByImage(
                                dv.Id, 
                                new List<String>{mdtObj.Id},
                                500,
                                1,
                                null);
        Test.stopTest();

        System.assertNotEquals(null, str);
        List<DetailsAddController.SymbolObject> rtnList = (List<DetailsAddController.SymbolObject>)JSON.deserialize(str, List<DetailsAddController.SymbolObject>.class);
        System.assertEquals(rtnList.size()>0, true);

        System.assertNotEquals(null, strImage);

    }
    //Buが変わった
    //見積番号が変わった
    //マスター検索
    @isTest static void priceTableTest() {
        String qRtName='施設';
        String major='変圧器';
        String minor='機器事業部 変圧器';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //BUが選択の場合、大分類、見積番号のプルダウンリストを取得
        Map<String, List<Map<String, String>>> res =  DetailsAddController.pickedBUAfter('S');

        //大分類が選択の場合、小分類のプルダウンリストを取得
        Map<String, List<Map<String, String>>> resMajor =  DetailsAddController.pickedMajorAfter('S',major);

        //見積番号が選択の場合、項目番号のプルダウンリストを取得
        Map<String, List<Map<String, String>>> resQuoteNumber =  DetailsAddController.pickedQuoteNumberAfter(quote.Id,dv.Id);

        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );

        List<DetailsAddController.PricingTableInputOnly> intensifyList = new List<DetailsAddController.PricingTableInputOnly>();
        
        for (Integer i = 0;i<tables.size();i++) {
            if (tables.get(i).BU__c == 'S') {
                DetailsAddController.PricingTableInputOnly intensify = new DetailsAddController.PricingTableInputOnly();
                intensify.Id = tables.get(i).Id;
                intensify.Quantity = 1;
                intensify.WCCoefficient = 1;
                intensify.CreditWC = 1;
                intensify.UnitPriceCoefficient = 1;
                intensify.ProvisionUnitPrice = 1;
                intensify.UnitWeight = 1;
                intensify.WC = 1;
                intensify.Price = 1;
                intensify.ProvisionPrice = 1;
                intensify.Weight = 1;
                intensifyList.add(intensify);
            }
        }
       //価格表を基に登録された場合
        String strSubmitDetails = DetailsAddController.submitDetails(JSON.serialize(intensifyList), dv.Id);
        Test.stopTest();

        System.assertEquals(res.get('quoteNumber').size(), 1);
        System.assertEquals(res.get('major').size(), 1);
        System.assertEquals(resMajor.get('minor').size(), 1);
        System.assertEquals(resQuoteNumber.get('name').size(), 1);
        System.assertNotEquals(null, strMaster);
        System.assertEquals(strSubmitDetails, dv.Quote__c);
    }

    //マスター検索
    @isTest static void priceTableTest_1() {
        String qRtName='施設';
        String major='高圧コンビ';
        String minor='高圧コンビ盤';
        String powerFrequency='60Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );

        List<DetailsAddController.PricingTableInputOnly> intensifyList = new List<DetailsAddController.PricingTableInputOnly>();
        
        for (Integer i = 0;i<tables.size();i++) {
            if (tables.get(i).BU__c == 'S') {
                DetailsAddController.PricingTableInputOnly intensify = new DetailsAddController.PricingTableInputOnly();
                intensify.Id = tables.get(i).Id;
                intensify.Quantity = 1;
                intensify.WCCoefficient = 1;
                intensify.CreditWC = 1;
                intensify.UnitPriceCoefficient = 1;
                intensify.ProvisionUnitPrice = 1;
                intensify.UnitWeight = 1;
                intensify.WC = 1;
                intensify.Price = 1;
                intensify.ProvisionPrice = 1;
                intensify.Weight = 1;
                intensifyList.add(intensify);
            }
        }
       //価格表を基に登録された場合
        String strSubmitDetails = DetailsAddController.submitDetails(JSON.serialize(intensifyList), dv.Id);

        //登録した後にマスター検索
        String strMasterAfter = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            JSON.serialize(intensifyList)
                            );

        Test.stopTest();
        System.assertNotEquals(null, strMaster);
        System.assertNotEquals(null, strMasterAfter);
        System.assertEquals(strSubmitDetails, dv.Quote__c);
    }

    //マスター検索
    @isTest static void priceTableTest_2() {
        String qRtName='水環境';
        String major='計装機器';
        String minor='計装盤';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //図検索
        String strImage = DetailsAddController.getPricingTableRecordsByImage(
            dv.Id, 
            new List<String>{mdtObj.Id},
            500,
            1,
            null);
        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'M',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );
        Test.stopTest();
        System.assertNotEquals(null, strImage);
        System.assertNotEquals(null, strMaster);
    }
   //マスター検索
   @isTest static void priceTableTest_3() {
        String qRtName='施設';
        String major='進相コンデンサ/リアクトル';
        String minor='機器事業部 高圧コンデンサ/リアクトル';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //図検索
        String strImage = DetailsAddController.getPricingTableRecordsByImage(
            dv.Id, 
            new List<String>{mdtObj.Id},
            500,
            1,
            null);
        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );
        Test.stopTest();
        System.assertNotEquals(null, strImage);
        System.assertNotEquals(null, strMaster);
    }
    //マスター検索
   @isTest static void priceTableTest_4() {
        String qRtName='施設';
        String major='発電機';
        String minor='エンジン(DG)';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );
        Test.stopTest();
        System.assertNotEquals(null, strMaster);
    }
    //マスター検索
    @isTest static void priceTableTest_5() {
        String qRtName='施設';
        String major='コントロールセンタ(C/C)';
        String minor='200V';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );
        Test.stopTest();
        System.assertNotEquals(null, strMaster);
    }
    //マスター検索
    @isTest static void priceTableTest_6() {
        String qRtName='官需';
        String major='CCTVカメラ設備[国交省本省宛て提出機器単体費等]';
        String minor='HDIPカメラ装置';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);

        Test.startTest();
        //マスター検索
        String strMaster = DetailsAddController.getPricingTableRecords(
                            dv.Id,'S',
                            major,
                            minor,
                            500,
                            1,
                            null
                            );
        Test.stopTest();
        System.assertNotEquals(null, strMaster);
    }
    //見積項目検索
    @isTest static void detailTest() {
        String qRtName='施設';
        String major='変圧器';
        String minor='機器事業部 変圧器';
        String powerFrequency='50Hz';

        createDate(qRtName,major, minor, powerFrequency);
        //参照見積項目の明細
        Detail__c dv1Detail = new Detail__c();
        dv1Detail.Device__c = dv1.Id;//機器ID
        dv1Detail.Name1__c = 'Name1';
        dv1Detail.Name2__c = 'EP=WC×2';
        dv1Detail.Name3__c = 'Name3';
        dv1Detail.Name4__c = 'Name4';
        dv1Detail.Name5__c = 'Name5';
        dv1Detail.Name6__c = 'Name6';
        dv1Detail.Name7__c = 'Name7';
        dv1Detail.Name8__c = 'Name8';
        dv1Detail.Name9__c = 'Name9';
        dv1Detail.PricingTableUniqueKey__c = tables.get(0).UniqueKey__c;//機器ID
        insert dv1Detail;
        Test.startTest();
        //見積検索
        String strDetail = DetailsAddController.getDetailTableRecords(dv1.Id,
                                                                        500,
                                                                        1,
                                                                        null);

        DetailsAddController.PricingTableInputOnly intensify = new DetailsAddController.PricingTableInputOnly();

        intensify.Id = dv1Detail.Id;
        intensify.Quantity = 1;
        intensify.WCCoefficient = 1;
        intensify.CreditWC = 1;
        intensify.UnitPriceCoefficient = 1;
        intensify.ProvisionUnitPrice = 1;
        intensify.UnitWeight = 1;
        intensify.WC = 1;
        intensify.Price = 1;
        intensify.ProvisionPrice = 1;
        intensify.Weight = 1;
        List<DetailsAddController.PricingTableInputOnly> intensifyList = new List<DetailsAddController.PricingTableInputOnly>{intensify};
        //明細を基に登録された場合
        String strSubmitDetails = DetailsAddController.submitDetails(JSON.serialize(intensifyList), dv.Id);
        Test.stopTest();
        DetailsAddController.PricingTableWrapper scnInfo = (DetailsAddController.PricingTableWrapper)JSON.deserialize(strDetail, DetailsAddController.PricingTableWrapper.class);
        System.assertEquals(scnInfo.records.size(), 1);
        System.assertEquals(strSubmitDetails, dv.Quote__c);
    }
}