force-app/main/default/objects/Detail__c/Detail__c.object-meta.xml
<CustomObject>
    <label>明細</label>
    <nameField>
        <label>表示用テキスト</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>見積項目</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>明細</relationshipLabel>
    <relationshipName>Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <formula>Device__r.PriceCoefficient__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>価格係数</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>単価</label>
    <precision>11</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <formula>IF( GeneralAdminExpensesExistence__c ,PriceSum__c *  GeneralAdministrativeExpensesCopy__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般管理費</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/NETCalculateCategory__c.field-meta.xml
<CustomField>
    <fullName>NETCalculateCategory__c</fullName>
    <label>NET計算区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>受変電</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>自家発</fullName>
            </value>
            <value>
                <fullName>ビルシ</fullName>
            </value>
            <value>
                <fullName>映像</fullName>
            </value>
            <value>
                <fullName>労務</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <defaultValue>1</defaultValue>
    <label>価格係数</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量（数量×合計の計算式有り）</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <defaultValue>IF ($RecordType.Name = &quot;施設&quot;, &quot;0&quot;, &quot;&quot;)</defaultValue>
    <label>一般管理費率</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuotePriceSum__c.field-meta.xml
<CustomField>
    <fullName>QuotePriceSum__c</fullName>
    <label>客先回答価格総合計</label>
    <summarizedField>Device__c.ClientAnswerAmountTotal__c</summarizedField>
    <summaryForeignKey>Device__c.Quote__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SelfTotal_NET_General__c.field-meta.xml
<CustomField>
    <fullName>SelfTotal_NET_General__c</fullName>
    <inlineHelpText>コピー時には変更不可(コピー後の変更は可)</inlineHelpText>
    <label>手入力用全体NET（ゼネコン）</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SelfTotal_NET_LastAcc__c.field-meta.xml
<CustomField>
    <fullName>SelfTotal_NET_LastAcc__c</fullName>
    <inlineHelpText>コピー時には変更不可(コピー後の変更は可)</inlineHelpText>
    <label>手入力用全体NET（最終顧客）</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/SelfTotal_NET_Sub__c.field-meta.xml
<CustomField>
    <fullName>SelfTotal_NET_Sub__c</fullName>
    <inlineHelpText>コピー時には変更不可(コピー後の変更は可)</inlineHelpText>
    <label>手入力用全体NET（サブコン）</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/QuoteTriggerTest.cls
@isTest
private class QuoteTriggerTest {
    @testSetup
    static void quotedataCreation() {
        List<RecordType> recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Quote__c' and name = '施設'];

        List<Quote__c> qtList = new List<Quote__c>();
        Quote__c qoute1 = new Quote__c(
            //GeneralAdministrativeExpenses__c = 1,　コメントアウト中
            PowerFrequency__c = '50Hz',
            RecordTypeId = recType[0].Id,
            QuoteNumber__c = '1'
        );
        qtList.add(qoute1);

        Quote__c qoute2 = new Quote__c(
            //GeneralAdministrativeExpenses__c = 1,　コメントアウト中
            PowerFrequency__c = '50Hz',
            RecordTypeId = recType[0].Id,
            QuoteNumber__c = '1'
        );
        qtList.add(qoute2);
        
        insert qtList;

        List<Device__c> deList = new List<Device__c>();
        Device__c dv1 = new Device__c(
            QuoteSpecificationNumber__c = '001',
            Name = '品名',
            MajorClassification__c = 'UPS',
            NETCalculateCategory__c = '受変電',
            Quote__c = qoute1.Id,
            PriceCoefficient__c=1,
            Quantity__c = '１2'

        );
        deList.add(dv1);
        Device__c dv2 = new Device__c(
            QuoteSpecificationNumber__c = '001',
            Name = '品名',
            MajorClassification__c = 'UPS',
            NETCalculateCategory__c = 'UPS',
            Quote__c = qoute2.Id,
            PriceCoefficient__c=1,
            Quantity__c = '２'

        );
        deList.add(dv2);
        insert deList;

        List<Detail__c> dList = new List<Detail__c>();
        Detail__c dtl1 = new Detail__c(
            Device__c = dv1.Id,
            Name = '名称1',
            Quantity__c = 1,
            UnitPrice__c = 1000
        );
        dList.add(dtl1);
        Detail__c dtl2 = new Detail__c(
            Device__c = dv2.Id,
            Name = '名称2',
            Quantity__c = 2,
            UnitPrice__c = 2000
        );
        dList.add(dtl2);
        insert dList;
    }

    @IsTest
    private static void cloneQuoteAndRelatedRecordsTest() {
        //テスト実行
        Test.startTest();
        quotedataCreation();
        List<Quote__c> cloneQtList = new List<Quote__c>();
        for(Quote__c qt : [SELECT Id,  PowerFrequency__c,QuoteNumber__c,QuotePriceSum__c FROM Quote__c //GeneralAdministrativeExpenses__c,をコメントアウト中
        ]){
            Quote__c qClone = qt.clone();
            // qClone.SelfTotal_NET_LastAcc__c=1;
            cloneQtList.add(qClone);
        }

        insert cloneQtList;
        
        Test.stopTest();

    }
    @IsTest
    private static void updateQuoteAndRelatedRecordsTest() {
        //テスト実行
        Test.startTest();
        quotedataCreation();
        List<Quote__c> updateQtList = new List<Quote__c>();
        for(Quote__c qt : [SELECT Id,  PowerFrequency__c,QuoteNumber__c,QuotePriceSum__c FROM Quote__c //GeneralAdministrativeExpenses__c,をコメントアウト中
        ]){
            // Quote__c qClone = qt.clone();
            qt.SelfTotal_NET_LastAcc__c=1;
            qt.SelfTotal_NET_General__c=1;
            qt.SelfTotal_NET_Sub__c=1;
            updateQtList.add(qt);
        }

        update updateQtList;
        
        Test.stopTest();

    }
    @isTest
    private static void convertFullToHalfTest(){
        List<RecordType> recType = [SELECT Id FROM RecordType WHERE SobjectType = 'Quote__c' and name = '施設'];
        List<Quote__c> qList = new List<Quote__c>();
        //一般管理費が半角の場合
        Quote__c q1 = new Quote__c(
            QuoteNumber__c = '全角入力テスト_半角ver',
            GeneralAdministrativeExpenses__c = '1',//半角数字
            PowerFrequency__c = '50Hz',
            RecordTypeId = recType[0].Id
        );
        qList.add(q1);
        //一般管理費が全角の場合
        Quote__c q2 = new Quote__c(
            QuoteNumber__c = '全角入力テスト_全角ver',
            GeneralAdministrativeExpenses__c = '１',//全角数字
            PowerFrequency__c = '50Hz',
            RecordTypeId = recType[0].Id
        );
        qList.add(q2);
        //一般管理費が半角・全角複合の場合
        Quote__c q3 = new Quote__c(
            QuoteNumber__c = '全角入力テスト_半角全角複合ver',
            GeneralAdministrativeExpenses__c = '1２',//半角数字、全角数字複合
            PowerFrequency__c = '50Hz',
            RecordTypeId = recType[0].Id
        );
        qList.add(q3);

        //テスト実行
        Test.startTest();

        insert qList;

        Test.stopTest();

        List<Quote__c> qResult1 = [SELECT Id
                                        ,QuoteNumber__c
                                        ,GeneralAdministrativeExpenses__c
                                        ,PowerFrequency__c
                                        ,RecordTypeId
                                        FROM Quote__c WHERE Id = :q1.Id];
        List<Quote__c> qResult2 = [SELECT Id
                                        , QuoteNumber__c
                                        , GeneralAdministrativeExpenses__c
                                        , PowerFrequency__c
                                        , RecordTypeId
                                        FROM Quote__c WHERE Id = :q2.Id];
        List<Quote__c> qResult3 = [SELECT Id
                                        , QuoteNumber__c
                                        , GeneralAdministrativeExpenses__c
                                        , PowerFrequency__c
                                        , RecordTypeId
                                        FROM Quote__c WHERE Id = :q3.Id];

        System.assertEquals('1', qResult1[0].GeneralAdministrativeExpenses__c);
        System.assertEquals('1', qResult2[0].GeneralAdministrativeExpenses__c);
        System.assertEquals('12', qResult3[0].GeneralAdministrativeExpenses__c);

    }
}