force-app/main/default/objects/Detail__c/Detail__c.object-meta.xml
<CustomObject>
    <label>明細</label>
    <nameField>
        <label>表示用テキスト</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Detail__c/fields/CreditWeight__c.field-meta.xml
<CustomField>
    <fullName>CreditWeight__c</fullName>
    <label>単位重量</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Device__c.field-meta.xml
<CustomField>
    <fullName>Device__c</fullName>
    <label>見積項目</label>
    <referenceTo>Device__c</referenceTo>
    <relationshipLabel>明細</relationshipLabel>
    <relationshipName>Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name2__c.field-meta.xml
<CustomField>
    <fullName>Name2__c</fullName>
    <label>名称2</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Name3__c.field-meta.xml
<CustomField>
    <fullName>Name3__c</fullName>
    <label>名称3</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>備考</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <formula>Device__r.PriceCoefficient__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>価格係数</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/PricingTable__c.field-meta.xml
<CustomField>
    <fullName>PricingTable__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>価格表</label>
    <referenceTo>PricingTable__c</referenceTo>
    <relationshipName>Details</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Detail__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <formula>CreditWeight__c  *  Quantity__c</formula>
    <label>重量</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/Device__c.object-meta.xml
<CustomObject>
    <label>見積項目</label>
    <nameField>
        <label>見積項目名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Device__c/fields/ClientAnswerWeight_free__c.field-meta.xml
<CustomField>
    <fullName>ClientAnswerWeight_free__c</fullName>
    <label>客先回答重量(手入力)</label>
    <precision>7</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/CreditWeight__c.field-meta.xml
<CustomField>
    <fullName>CreditWeight__c</fullName>
    <label>単位重量</label>
    <precision>10</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/DisplayOrder__c.field-meta.xml
<CustomField>
    <fullName>DisplayOrder__c</fullName>
    <label>表示順</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/EquipManageCostTarget__c.field-meta.xml
<CustomField>
    <fullName>EquipManageCostTarget__c</fullName>
    <defaultValue>true</defaultValue>
    <label>国土交通省機器管理費対象</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/GeneralAdminExpensesExistence__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdminExpensesExistence__c</fullName>
    <defaultValue>true</defaultValue>
    <label>一般管理費有無</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <formula>IF( GeneralAdminExpensesExistence__c ,PriceSum__c *  GeneralAdministrativeExpensesCopy__c, 0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>一般管理費</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/MajorClassification__c.field-meta.xml
<CustomField>
    <fullName>MajorClassification__c</fullName>
    <label>大分類名</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <controllingField>RecordTypeOfQuote__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>MajorClassification</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/MinorClassification__c.field-meta.xml
<CustomField>
    <fullName>MinorClassification__c</fullName>
    <label>小分類名</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MajorClassification__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>66kV C-GIS</fullName>
            </value>
            <value>
                <fullName>22kV C-GIS</fullName>
            </value>
            <value>
                <fullName>ブロック(気中)キュービクル</fullName>
            </value>
            <value>
                <fullName>特高監視盤</fullName>
            </value>
            <value>
                <fullName>特高変圧器</fullName>
            </value>
            <value>
                <fullName>高圧変圧器</fullName>
            </value>
            <value>
                <fullName>変圧器収納盤</fullName>
            </value>
            <value>
                <fullName>バスダクト</fullName>
            </value>
            <value>
                <fullName>高圧コンビ盤</fullName>
            </value>
            <value>
                <fullName>高圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧コンデンサ・リアクトル</fullName>
            </value>
            <value>
                <fullName>低圧盤</fullName>
            </value>
            <value>
                <fullName>現場盤</fullName>
            </value>
            <value>
                <fullName>リレー盤</fullName>
            </value>
            <value>
                <fullName>ACB盤</fullName>
            </value>
            <value>
                <fullName>200V</fullName>
            </value>
            <value>
                <fullName>400V</fullName>
            </value>
            <value>
                <fullName>共通</fullName>
            </value>
            <value>
                <fullName>3.0kV/3.3kV</fullName>
            </value>
            <value>
                <fullName>6.0kV/6.6kV</fullName>
            </value>
            <value>
                <fullName>CTR</fullName>
            </value>
            <value>
                <fullName>OPS</fullName>
            </value>
            <value>
                <fullName>計装盤</fullName>
            </value>
            <value>
                <fullName>記録計</fullName>
            </value>
            <value>
                <fullName>ラック･パネル計器</fullName>
            </value>
            <value>
                <fullName>流量計</fullName>
            </value>
            <value>
                <fullName>水位計</fullName>
            </value>
            <value>
                <fullName>濃度計</fullName>
            </value>
            <value>
                <fullName>その他</fullName>
            </value>
            <value>
                <fullName>ACG</fullName>
            </value>
            <value>
                <fullName>屋内</fullName>
            </value>
            <value>
                <fullName>屋外</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>施設</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/NETCalculateCategory__c.field-meta.xml
<CustomField>
    <fullName>NETCalculateCategory__c</fullName>
    <label>NET計算区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>受変電</fullName>
            </value>
            <value>
                <fullName>UPS</fullName>
            </value>
            <value>
                <fullName>自家発</fullName>
            </value>
            <value>
                <fullName>ビルシ</fullName>
            </value>
            <value>
                <fullName>映像</fullName>
            </value>
            <value>
                <fullName>労務</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <inlineHelpText>大分類が「材料」or「システムインテグレーション費」の場合は要入力</inlineHelpText>
    <label>手入力金額設定根拠</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/PriceCoefficient__c.field-meta.xml
<CustomField>
    <fullName>PriceCoefficient__c</fullName>
    <defaultValue>1</defaultValue>
    <label>価格係数</label>
    <precision>6</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>数量（数量×合計の計算式有り）</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <inlineHelpText>明細の変圧器、コンデンサ、発電機は周波数により価格が異なるので、周波数の異なるエリアの見積にコピーする場合は注意してください</inlineHelpText>
    <label>見積</label>
    <referenceTo>Quote__c</referenceTo>
    <relationshipLabel>見積項目</relationshipLabel>
    <relationshipName>Devices</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <formula>Quote__r.QuoteNumber__c</formula>
    <label>見積番号</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/QuoteSpecificationNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteSpecificationNumber__c</fullName>
    <label>項目番号</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device__c/fields/RecordTypeOfQuote__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeOfQuote__c</fullName>
    <label>見積レコードタイプ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>施設</fullName>
            </value>
            <value>
                <fullName>水環境</fullName>
            </value>
            <value>
                <fullName>官需</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Device__c/fields/Unit__c.field-meta.xml
<CustomField>
    <fullName>Unit__c</fullName>
    <label>単位</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/PricingTable__c.object-meta.xml
<CustomObject>
    <label>価格表</label>
    <nameField>
        <displayFormat>K-{00000000}</displayFormat>
        <label>価格表番号</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/PricingTable__c/fields/Name1__c.field-meta.xml
<CustomField>
    <fullName>Name1__c</fullName>
    <label>名称1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Note__c.field-meta.xml
<CustomField>
    <fullName>Note__c</fullName>
    <label>備考</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/fields/Weight__c.field-meta.xml
<CustomField>
    <fullName>Weight__c</fullName>
    <label>単位重量</label>
    <precision>13</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PricingTable__c/recordTypes/Chassis.recordType-meta.xml
<RecordType>
    <fullName>Chassis</fullName>
    <active>true</active>
    <label>筐体</label>
</RecordType>

force-app/main/default/objects/PricingTable__c/recordTypes/Detail.recordType-meta.xml
<RecordType>
    <fullName>Detail</fullName>
    <active>true</active>
    <label>明細</label>
</RecordType>

force-app/main/default/objects/Quote__c/Quote__c.object-meta.xml
<CustomObject>
    <label>見積</label>
    <nameField>
        <displayFormat>Q-{YYYY}{MM}{DD}-{000000}</displayFormat>
        <label>見積コード</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Quote__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>見積</relationshipLabel>
    <relationshipName>Account</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/GeneralAdministrativeExpenses__c.field-meta.xml
<CustomField>
    <fullName>GeneralAdministrativeExpenses__c</fullName>
    <defaultValue>IF ($RecordType.Name = &quot;施設&quot;, &quot;0&quot;, &quot;&quot;)</defaultValue>
    <label>一般管理費率</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/OutputSheetName__c.field-meta.xml
<CustomField>
    <fullName>OutputSheetName__c</fullName>
    <label>出力帳票名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/PowerFrequency__c.field-meta.xml
<CustomField>
    <fullName>PowerFrequency__c</fullName>
    <label>電源周波数</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>50Hz</fullName>
            </value>
            <value>
                <fullName>60Hz</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Quote__c/fields/QuoteNumber__c.field-meta.xml
<CustomField>
    <fullName>QuoteNumber__c</fullName>
    <label>見積番号</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Quote__c/fields/Subject__c.field-meta.xml
<CustomField>
    <fullName>Subject__c</fullName>
    <label>件名</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/DetailsInputForExtraHighControllerTest.cls
@isTest
public with sharing class DetailsInputForExtraHighControllerTest {
    
    @TestSetup
    static void makeData(){
        Integer recNo = 0;
        List<PricingTable__c> pricingDataOil = initPricingTableDataOil(recNo);
        insert pricingDataOil;
        List<PricingTable__c> pricingDataMold = initPricingTableDataMold(recNo);
        insert pricingDataMold;
        List<PricingTable__c> pricingDataGas = initPricingTableDataGas(recNo);
        insert pricingDataGas;
        initStandardData();
    }
    static void initStandardData() {
        //////////////////////////////////////////////////////////////////////////////////////////////
        //                    Account, Quote__c, Device__c, Detail__c                               //
        //////////////////////////////////////////////////////////////////////////////////////////////
        String DEFAULT_MAJOR_CLASSIFICATION = '変圧器';
        String DEFAULT_MINOR_CLASSIFICATION = '特高変圧器';

        Account account = new Account(
            Name='Test Account Name'
        );
        insert account;

        // 施設
        RecordType quoteFacilityRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name='施設' AND SobjectType='Quote__c' LIMIT 1];
        Quote__c quote1 = new Quote__c(
            Account__c=account.Id,
            Subject__c='Test Quote Subject 1',
            QuoteNumber__c='1234567890',
            GeneralAdministrativeExpenses__c='23',
            PowerFrequency__c='50Hz', // {50Hz, 60Hz}
            OutputSheetName__c='TestQuoteOutputSheetName',
            RecordTypeId=quoteFacilityRecordType.Id
        );
        insert quote1;

        // 水環境
        RecordType quoteWaterRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name='水環境' AND SobjectType='Quote__c' LIMIT 1];
        Quote__c quote2 = new Quote__c(
            Account__c=account.Id,
            Subject__c='Test Quote Subject 2',
            QuoteNumber__c='1234567891',
            GeneralAdministrativeExpenses__c='25',
            PowerFrequency__c='60Hz', // {50Hz, 60Hz}
            OutputSheetName__c='TestQuoteOutputSheetName',
            RecordTypeId=quoteWaterRecordType.Id
        );
        insert quote2;

        Quote__c quote3 = new Quote__c(
            Account__c=account.Id,
            Subject__c='Test Quote Subject 3',
            QuoteNumber__c='1234567892',
            GeneralAdministrativeExpenses__c='25',
            PowerFrequency__c='60Hz', // {50Hz, 60Hz}
            OutputSheetName__c='TestQuoteOutputSheetName',
            RecordTypeId=quoteWaterRecordType.Id
        );
        insert quote3;

        // 官需
        RecordType quotePDemandRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name='官需' AND SobjectType='Quote__c' LIMIT 1];
        Quote__c quote4 = new Quote__c(
            Account__c=account.Id,
            Subject__c='Test Quote Subject 4',
            QuoteNumber__c='1234567893',
            GeneralAdministrativeExpenses__c='25',
            PowerFrequency__c='60Hz', // {50Hz, 60Hz}
            OutputSheetName__c='TestQuoteOutputSheetName',
            RecordTypeId=quotePDemandRecordType.Id
        );
        insert quote4;

        // 施設
        RecordType deviceFacilityRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name='施設' AND SobjectType='Device__c' LIMIT 1];
        Device__c device1 = new Device__c(
            Quote__c=quote1.Id,
            Name='Test Device Name 1',
            Note__c='Test Device Note',
            Quantity__c='1',
            Unit__c='piece',
            QuoteSpecificationNumber__c='1234567890',
            NETCalculateCategory__c='', // {受変電, UPS, 自家発, ビルシ, 映像, 労務}
            RecordTypeOfQuote__c='施設', // {施設, 水環境, 官需}
            MajorClassification__c=DEFAULT_MAJOR_CLASSIFICATION,
            MinorClassification__c=DEFAULT_MINOR_CLASSIFICATION,
            ClientAnswerWeight_free__c=0,
            CreditWeight__c=0,
            PriceCoefficient__c=0,
            DisplayOrder__c=1,
            EquipManageCostTarget__c=false,
            GeneralAdminExpensesExistence__c=false,
            RecordTypeId=deviceFacilityRecordType.Id
        );
        insert device1;

        Device__c device2 = new Device__c(
            Quote__c=quote1.Id,
            Name='Test Device Name 2',
            Note__c='Test Device Note',
            Quantity__c='1',
            Unit__c='piece',
            QuoteSpecificationNumber__c='1234567891',
            NETCalculateCategory__c='', // {受変電, UPS, 自家発, ビルシ, 映像, 労務}
            RecordTypeOfQuote__c='施設', // {施設, 水環境, 官需}
            MajorClassification__c=DEFAULT_MAJOR_CLASSIFICATION,
            MinorClassification__c=DEFAULT_MINOR_CLASSIFICATION,
            ClientAnswerWeight_free__c=0,
            CreditWeight__c=0,
            PriceCoefficient__c=0,
            DisplayOrder__c=1,
            EquipManageCostTarget__c=false,
            GeneralAdminExpensesExistence__c=false,
            RecordTypeId=deviceFacilityRecordType.Id
        );
        insert device2;

        // 水環境
        RecordType deviceWaterRecordType = [SELECT Id, Name, DeveloperName FROM RecordType WHERE Name='水環境' AND SobjectType='Device__c' LIMIT 1];
        Device__c device3 = new Device__c(
            Quote__c=quote2.Id,
            Name='Test Device Name 3',
            Note__c='Test Device Note',
            Quantity__c='1',
            Unit__c='piece',
            QuoteSpecificationNumber__c='1234567892',
            NETCalculateCategory__c='', // {受変電, UPS, 自家発, ビルシ, 映像, 労務}
            RecordTypeOfQuote__c='水環境', // {施設, 水環境, 官需}
            MajorClassification__c=DEFAULT_MAJOR_CLASSIFICATION,
            MinorClassification__c=DEFAULT_MINOR_CLASSIFICATION,
            ClientAnswerWeight_free__c=0,
            CreditWeight__c=0,
            PriceCoefficient__c=0,
            DisplayOrder__c=1,
            EquipManageCostTarget__c=false,
            GeneralAdminExpensesExistence__c=false,
            RecordTypeId=deviceWaterRecordType.Id
        );
        insert device3;

        List<Detail__c> details = new List<Detail__c>();
        // 筐体 :: GIS直結
        details.add(new Detail__c(
            Device__c=device2.Id,
            Name='特高TR油入',
            Name1__c='油 スポットネットワーク',
            Name2__c='屋外',
            Name3__c='三相',
            Name4__c='22,000V',
            PricingTableUniqueKey__c='筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,000kVA特高TR油入',
            UnitPrice__c=12000000,
            DetailCategory__c='筐体',
            Quantity__c=1,
            WcCalculationRate__c=0.0,
            Name5__c='6,600V',
            Name6__c='1,000kVA',
            Name10__c='特高TR油入',
            detailedStatementText__c='TR',
            SpecialSpecificationNo__c=3,
            MajorClassificationName__c='変圧器',
            MajorClassificationCode__c='23',
            MinorClassificationName__c='特高変圧器',
            MinorClassificationCode__c='01',
            CategoryCode__c='01'
        ));

        //  明細
        details.add(new Detail__c(
            Device__c=device2.Id,
            Name='特高油入',
            Name1__c='油',
            Name2__c='GIS直結',
            Name3__c='1,000kVA',
            PricingTableUniqueKey__c='明細S変圧器特高変圧器油GIS直結1,000kVA',
            UnitPrice__c=2100000,
            DetailCategory__c='明細',
            Quantity__c=1,
            SpecialSpecificationNo__c=0,
            MajorClassificationName__c='変圧器',
            MajorClassificationCode__c='23',
            MinorClassificationName__c='特高変圧器',
            MinorClassificationCode__c='01',
            CategoryCode__c='00'
        ));

        //  明細 : OLTC付
        details.add(new Detail__c(
            Device__c=device2.Id,
            Name='特高油入',
            Name1__c='油',
            Name2__c='OLTC付',
            PricingTableUniqueKey__c='明細S変圧器特高変圧器油OLTC付',
            UnitPrice__c=22000000,
            DetailCategory__c='明細',
            Quantity__c=1,
            SpecialSpecificationNo__c=0,
            MajorClassificationName__c='変圧器',
            MajorClassificationCode__c='23',
            MinorClassificationName__c='特高変圧器',
            MinorClassificationCode__c='01',
            CategoryCode__c='00'
        ));
        insert details;

        
    } 

    static List<PricingTable__c> initPricingTableDataOil(Integer recNo) {
        List<PricingTable__c> pricingTableList = new List<PricingTable__c>();
        RecordType chassisRecordType = [SELECT Id, DeveloperName  FROM RecordType WHERE DeveloperName='Chassis' LIMIT 1];
        RecordType detailRecordType = [SELECT Id, DeveloperName  FROM RecordType WHERE DeveloperName='Detail' LIMIT 1];

        List<String> name6List = new List<String>{'1,000kVA', '1,200kVA', '1,250kVA', '1,500kVA', '2,000kVA', '2,500kVA'};
        List<Decimal> priceList = new List<Decimal>{9800000, 11100000, 13200000, 16100000, 20100000, 21100000};

        List<String> keyList11 = new List<String>{'筐体S変圧器特高変圧器60Hz油屋内三相22,000V6,600V1,000kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相22,000V6,600V1,200kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相22,000V6,600V1,250kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相22,000V6,600V1,500kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相22,000V6,600V2,000kVA特高TR油入'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '22,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '50Hz';
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '22,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '01';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        List<String> keyList12 = new List<String>{'筐体S変圧器特高変圧器60Hz油屋内三相11,000V6,600V1,000kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相11,000V6,600V1,200kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相11,000V6,600V1,250kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油屋内三相11,000V6,600V1,500kVA特高TR油入'};
        for (Integer i = 0; i < 4 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '11,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        for (Integer i = 0; i < 4 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '50Hz';
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '11,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '01';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        for (Integer i = 0; i < 1 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '33,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        for (Integer i = 0; i < 1 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '50Hz';
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '33,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '01';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        List<String> keyList21 = new List<String>{'筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,000kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,200kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,250kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,500kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V2,000kVA特高TR油入'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = '油 スポットネットワーク';
            pricingTable.Name2__c = '屋外';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '22,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        // for (Integer i = 0; i < 5 ; i++) {
        //     PricingTable__c pricingTable = new PricingTable__c();
        //     pricingTable.RecordTypeId = chassisRecordType.Id;
        //     pricingTable.DisplayName__c = '特高TR油入';
        //     pricingTable.CategoryName__c = '50Hz';
        //     pricingTable.Name1__c = '油 スポットネットワーク';
        //     pricingTable.Name2__c = '屋外';
        //     pricingTable.Name3__c = '三相';
        //     pricingTable.Name4__c = '22,000V';
        //     pricingTable.Name5__c = '6,600V';
        //     pricingTable.Name6__c = name6List.get(i);
        //     pricingTable.Name10__c = '特高TR油入';
        //     pricingTable.Price__c = priceList.get(i);
        //     pricingTable.BU__c = 'S';
        //     pricingTable.detailedStatementText__c = 'TR';
        //     pricingTable.SpecialSpecificationNo__c = 0;
        //     pricingTable.MajorClassificationName__c  = '変圧器';
        //     pricingTable.MajorClassificationCode__c  = '23';
        //     pricingTable.MinorClassificationName__c = '特高変圧器';
        //     pricingTable.MinorClassificationCode__c = '01';
        //     pricingTable.CategoryCode__c = '01';
        //     pricingTable.RECNo__c=++recNo;
        //     pricingTableList.add(pricingTable);
        // }

        List<String> keyList22 = new List<String>{'筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相66,000V13,800V1,000kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相66,000V13,800V1,200kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相66,000V13,800V1,250kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相66,000V13,800V1,500kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相66,000V13,800V2,000kVA特高TR油入'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = '油 スポットネットワーク';
            pricingTable.Name2__c = '屋外';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '66,000V';
            pricingTable.Name5__c = '13,800V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TR油入';
            pricingTable.CategoryName__c = '50Hz';
            pricingTable.Name1__c = '油 スポットネットワーク';
            pricingTable.Name2__c = '屋外';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '66,000V';
            pricingTable.Name5__c = '13,800V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '01';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        List<String> keyList3 = new List<String>{'明細S変圧器特高変圧器油GIS直結1,000kVA特高TR油入',
                                                '明細S変圧器特高変圧器油GIS直結1,200kVA特高TR油入',
                                                '明細S変圧器特高変圧器油GIS直結1,250kVA特高TR油入',
                                                '明細S変圧器特高変圧器油GIS直結1,500kVA特高TR油入',
                                                '明細S変圧器特高変圧器油GIS直結2,000kVA特高TR油入'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = detailRecordType.Id;
            pricingTable.DisplayName__c = '特高油入';
            pricingTable.CategoryName__c = null;
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = 'GIS直結';
            pricingTable.Name3__c = name6List.get(i);
            pricingTable.Name4__c = null;
            pricingTable.Name5__c = null;
            pricingTable.Name6__c = null;
            pricingTable.Name10__c = null;
            pricingTable.Price__c = priceList.get(0);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '00';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        List<String> keyList4 = new List<String>{'明細S変圧器特高変圧器油OLTC付',
                                                '明細S変圧器特高変圧器油OLTC付',
                                                '明細S変圧器特高変圧器油OLTC付',
                                                '明細S変圧器特高変圧器油OLTC付',
                                                '明細S変圧器特高変圧器油OLTC付'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = detailRecordType.Id;
            pricingTable.DisplayName__c = '特高油入';
            pricingTable.CategoryName__c = null;
            pricingTable.Name1__c = '油';
            pricingTable.Name2__c = 'OLTC付';
            pricingTable.Name3__c = name6List.get(i);
            pricingTable.Name4__c = null;
            pricingTable.Name5__c = null;
            pricingTable.Name6__c = null;
            pricingTable.Name10__c = null;
            pricingTable.Price__c = priceList.get(0);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = null;
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '00';
            pricingTable.RECNo__c=++recNo;
            pricingTableList.add(pricingTable);
        }

        return pricingTableList;
    }

    static List<PricingTable__c> initPricingTableDataMold(Integer recNo) {
        List<PricingTable__c> pricingTableList = new List<PricingTable__c>();
        RecordType chassisRecordType = [SELECT Id, DeveloperName  FROM RecordType WHERE DeveloperName='Chassis' LIMIT 1];
        RecordType detailRecordType = [SELECT Id, DeveloperName  FROM RecordType WHERE DeveloperName='Detail' LIMIT 1];

        List<String> name6List = new List<String>{'1,000kVA', '1,200kVA', '1,250kVA', '1,500kVA', '2,000kVA'};
        List<Decimal> priceList = new List<Decimal>{9800000, 11100000, 13200000, 16100000, 20100000};
        List<String> keyList = new List<String>{'筐体S変圧器特高変圧器60Hzモールド三相22,000V6,600V1,000kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzモールド三相22,000V6,600V1,200kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzモールド三相22,000V6,600V1,250kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzモールド三相22,000V6,600V1,500kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzモールド三相22,000V6,600V2,000kVA特高TR油入'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TRモールド';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = 'モールド';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '22,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;

            pricingTableList.add(pricingTable);
        }

        return pricingTableList;
    }

    static List<PricingTable__c> initPricingTableDataGas(Integer recNo) {
        List<PricingTable__c> pricingTableList = new List<PricingTable__c>();
        RecordType chassisRecordType = [SELECT Id, DeveloperName  FROM RecordType WHERE DeveloperName='Chassis' LIMIT 1];
        RecordType detailRecordType = [SELECT Id, DeveloperName  FROM RecordType WHERE DeveloperName='Detail' LIMIT 1];

        List<String> name6List = new List<String>{'1,000kVA', '1,200kVA', '1,250kVA', '1,500kVA', '2,000kVA'};
        List<Decimal> priceList = new List<Decimal>{9800000, 11100000, 13200000, 16100000, 20100000};
        List<String> keyList = new List<String>{'筐体S変圧器特高変圧器60Hzガス三相22,000V6,600V1,000kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzガス三相22,000V6,600V1,200kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzガス三相22,000V6,600V1,250kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzガス三相22,000V6,600V1,500kVA特高TR油入',
                                                '筐体S変圧器特高変圧器60Hzガス三相22,000V6,600V2,000kVA特高TR油入'};
        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TRガス';
            pricingTable.CategoryName__c = '60Hz';
            pricingTable.Name1__c = 'ガス';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '22,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '02';
            pricingTable.RECNo__c=++recNo;

            pricingTableList.add(pricingTable);
        }

        for (Integer i = 0; i < 5 ; i++) {
            PricingTable__c pricingTable = new PricingTable__c();
            pricingTable.RecordTypeId = chassisRecordType.Id;
            pricingTable.DisplayName__c = '特高TRガス';
            pricingTable.CategoryName__c = '50Hz';
            pricingTable.Name1__c = 'ガス';
            pricingTable.Name2__c = '屋内';
            pricingTable.Name3__c = '三相';
            pricingTable.Name4__c = '22,000V';
            pricingTable.Name5__c = '6,600V';
            pricingTable.Name6__c = name6List.get(i);
            pricingTable.Name10__c = '特高TR油入';
            pricingTable.Price__c = priceList.get(i);
            pricingTable.BU__c = 'S';
            pricingTable.detailedStatementText__c = 'TR';
            pricingTable.SpecialSpecificationNo__c = 0;
            pricingTable.MajorClassificationName__c  = '変圧器';
            pricingTable.MajorClassificationCode__c  = '23';
            pricingTable.MinorClassificationName__c = '特高変圧器';
            pricingTable.MinorClassificationCode__c = '01';
            pricingTable.CategoryCode__c = '01';
            pricingTable.RECNo__c=++recNo;

            pricingTableList.add(pricingTable);
        }

        return pricingTableList;
    }


    @IsTest
    private static void getDetailsInputForExtraHighInfoCase1Test() {

        Device__c device = [SELECT Id, Quote__c FROM Device__c WHERE Name='Test Device Name 1' LIMIT 1];

        Boolean isInit = true;
        String deviceId = device.Id;
        String screenType = '1';
        String searchCondition1 = '1';
        String searchCondition2 = '0';
        String searchCondition3 = '0';
        String searchCondition4 = '0';
        String searchCondition5 = '0';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.getDetailsInputForExtraHighInfo(
            isInit,
            deviceId,
            screenType,
            searchCondition1,
            searchCondition2,
            searchCondition3,
            searchCondition4,
            searchCondition5
        );
        Test.stopTest();
        Map<String, Object> res_actaulMap = (Map<String, Object>)JSON.deserializeUntyped(res_actaul);

        System.debug('================Case1=================');

        String errorMsg = '';
        Boolean isNoData = false;

        String inputedId = null;
        String displayCondition = null;
        Decimal displayTotal = null;

        String displayLabel = '特高TR 油入 屋内 GIS直結なし 電圧仕様標準 OLTCなし スポットネットワークなし';
        
        Assert.areEqual(errorMsg, res_actaulMap.get('errorMsg'));
        Assert.areEqual(isNoData, res_actaulMap.get('isNoData'));
        Assert.areEqual(inputedId, res_actaulMap.get('inputedId'));
        Assert.areEqual(displayCondition, res_actaulMap.get('displayCondition'));
        Assert.areEqual(displayTotal, res_actaulMap.get('displayTotal'));

        Assert.areEqual(displayLabel, res_actaulMap.get('displayLabel'));

        Assert.areEqual('1', res_actaulMap.get('screenType'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition1'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition2'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition3'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition4'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition5'));

        //Check [headerList]
        List<Object> headerList_expectList = new List<Object>{
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>true, 'rowSpanCnt'=>4, 'value'=>'容量'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'一次電圧'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'11,000V'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'22,000V'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'33,000V'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'二次電圧'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'6,600V'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'6,600V'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'6,600V'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'相数'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'三相'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'三相'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'三相'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'周波数'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'50Hz'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>null},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'GIS直結'},
                    
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'50Hz'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>null},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'GIS直結'},

                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'50Hz'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>null},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'GIS直結'}
                }
            }
        };

        List<Object> headerList_actualList = (List<Object>)res_actaulMap.get('headerList');
        for(Integer i=0; i<headerList_actualList.size(); i++) {
            Map<String, Object> cell_expect = (Map<String, Object>)headerList_expectList.get(i);
            List<Object> cellList_expect = (List<Object>)cell_expect.get('cellList');
            Map<String, Object> cell_actaul = (Map<String, Object>)headerList_actualList.get(i);
            List<Object> cellList_actaul = (List<Object>)cell_actaul.get('cellList');

            for(Integer j=0; j<cellList_actaul.size(); j++) {
                Assert.areEqual(cellList_expect.get(j), cellList_actaul.get(j));
            }
        }

        // Check [bodyList]
        List<Object> bodyList_expectList = new List<Object>{
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,000kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>9800000, 'title'=>'油 屋内 三相 11,000V 6,600V 1,000kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>9800000, 'title'=>'油 屋内 三相 22,000V 6,600V 1,000kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>9800000, 'title'=>'油 屋内 三相 33,000V 6,600V 1,000kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,200kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'11,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>11100000, 'title'=>'油 屋内 三相 11,000V 6,600V 1,200kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'11,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>11100000, 'title'=>'油 屋内 三相 22,000V 6,600V 1,200kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,250kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'13,200,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>13200000, 'title'=>'油 屋内 三相 11,000V 6,600V 1,250kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'13,200,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>13200000, 'title'=>'油 屋内 三相 22,000V 6,600V 1,250kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,500kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'16,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>16100000, 'title'=>'油 屋内 三相 11,000V 6,600V 1,500kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'16,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>16100000, 'title'=>'油 屋内 三相 22,000V 6,600V 1,500kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'2,000kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'20,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>20100000, 'title'=>'油 屋内 三相 22,000V 6,600V 2,000kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TR 油入"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'―'}
                }
            }
        };           

        List<Object> bodyList_actualList = (List<Object>)res_actaulMap.get('bodyList');
        for(Integer i=0; i<bodyList_actualList.size(); i++) {
            Map<String, Object> cell_expect = (Map<String, Object>)bodyList_expectList.get(i);
            List<Object> cellList_expect = (List<Object>)cell_expect.get('cellList');
            Map<String, Object> cell_actaul = (Map<String, Object>)bodyList_actualList.get(i);
            List<Object> cellList_actaul = (List<Object>)cell_actaul.get('cellList');

            for(Integer j=0; j<cellList_actaul.size(); j++) {
                Map<String, Object> expect = (Map<String, Object>)cellList_expect.get(j);
                Map<String, Object> actaul = (Map<String, Object>)cellList_actaul.get(j);

                if(actaul.get('value') instanceof Map<string,object>) {
                    Assert.areEqual(expect.get('colSpanCnt'), actaul.get('colSpanCnt'));
                    Assert.areEqual(expect.get('isColSpan'), actaul.get('isColSpan'));
                    Assert.areEqual(expect.get('isRowSpan'), actaul.get('isRowSpan'));
                    Assert.areEqual(expect.get('rowSpanCnt'), actaul.get('rowSpanCnt'));
                    Assert.areEqual(expect.get('isEdit'), actaul.get('isEdit'));

                    Map<String, Object> expect_value = (Map<String, Object>)expect.get('value');
                    Map<String, Object> actaul_value = (Map<String, Object>)actaul.get('value');
                    Assert.areEqual(expect_value.get('Price'), actaul_value.get('Price'));
                    Assert.areEqual(expect_value.get('isChecked'), actaul_value.get('isChecked'));
                    Assert.areEqual(expect_value.get('title'), actaul_value.get('title'));
                } else {
                    Assert.areEqual(expect, actaul);
                }
            }
        }
    }

    @IsTest
    private static void getDetailsInputForExtraHighInfoCase2Test() {

        Device__c device = [SELECT Id, Quote__c FROM Device__c WHERE Name='Test Device Name 1' LIMIT 1];

        Boolean isInit = true;
        String deviceId = device.Id;
        String screenType = '2';
        String searchCondition1 = '1';
        String searchCondition2 = '0';
        String searchCondition3 = '0';
        String searchCondition4 = '0';
        String searchCondition5 = '0';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.getDetailsInputForExtraHighInfo(
            isInit,
            deviceId,
            screenType,
            searchCondition1,
            searchCondition2,
            searchCondition3,
            searchCondition4,
            searchCondition5
        );
        Test.stopTest();
        Map<String, Object> res_actaulMap = (Map<String, Object>)JSON.deserializeUntyped(res_actaul);

        System.debug('================Case2=================');

        String errorMsg = '';
        Boolean isNoData = true;

        String inputedId = null;
        String displayCondition = null;
        Decimal displayTotal = null;

        String displayLabel = null;
    
        List<Object> headerList = null;
        List<Object> bodyList = null;

        Assert.areEqual(errorMsg, res_actaulMap.get('errorMsg'));
        Assert.areEqual(isNoData, res_actaulMap.get('isNoData'));
        Assert.areEqual(inputedId, res_actaulMap.get('inputedId'));
        Assert.areEqual(displayCondition, res_actaulMap.get('displayCondition'));
        Assert.areEqual(displayTotal, res_actaulMap.get('displayTotal'));

        Assert.areEqual(displayLabel, res_actaulMap.get('displayLabel'));
        Assert.areEqual(headerList, res_actaulMap.get('headerList'));
        Assert.areEqual(bodyList, res_actaulMap.get('bodyList'));

        Assert.areEqual('2', res_actaulMap.get('screenType'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition1'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition2'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition3'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition4'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition5'));

        
    }

    @IsTest
    private static void getDetailsInputForExtraHighInfoCase3Test() {

        Device__c device = [SELECT Id, Quote__c FROM Device__c WHERE Name='Test Device Name 1' LIMIT 1];

        Boolean isInit = true;
        String deviceId = device.Id;
        String screenType = '3';
        String searchCondition1 = '1';
        String searchCondition2 = '0';
        String searchCondition3 = '0';
        String searchCondition4 = '0';
        String searchCondition5 = '0';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.getDetailsInputForExtraHighInfo(
            isInit,
            deviceId,
            screenType,
            searchCondition1,
            searchCondition2,
            searchCondition3,
            searchCondition4,
            searchCondition5
        );
        Test.stopTest();
        Map<String, Object> res_actaulMap = (Map<String, Object>)JSON.deserializeUntyped(res_actaul);

        System.debug('================Case3=================');

        String errorMsg = '';
        Boolean isNoData = false;

        String inputedId = null;
        String displayCondition = null;
        Decimal displayTotal = null;

        String displayLabel = '特高TRガス 屋内 GIS直結なし 電圧仕様標準 OLTCなし スポットネットワークなし';
        
        Assert.areEqual(errorMsg, res_actaulMap.get('errorMsg'));
        Assert.areEqual(isNoData, res_actaulMap.get('isNoData'));
        Assert.areEqual(inputedId, res_actaulMap.get('inputedId'));
        Assert.areEqual(displayCondition, res_actaulMap.get('displayCondition'));
        Assert.areEqual(displayTotal, res_actaulMap.get('displayTotal'));

        Assert.areEqual(displayLabel, res_actaulMap.get('displayLabel'));
    
        Assert.areEqual('3', res_actaulMap.get('screenType'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition1'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition2'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition3'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition4'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition5'));

        //Check [headerList]
        List<Object> headerList_expectList = new List<Object>{
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>true, 'rowSpanCnt'=>4, 'value'=>'容量'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'一次電圧'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'22,000V'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'二次電圧'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'6,600V'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'相数'},
                    new Map<String, Object>{'colSpanCnt'=>3, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'三相'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'周波数'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'50Hz'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>null},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'GIS直結'}
                }
            }
        };

        List<Object> headerList_actualList = (List<Object>)res_actaulMap.get('headerList');
        for(Integer i=0; i<headerList_actualList.size(); i++) {
            Map<String, Object> cell_expect = (Map<String, Object>)headerList_expectList.get(i);
            List<Object> cellList_expect = (List<Object>)cell_expect.get('cellList');
            Map<String, Object> cell_actaul = (Map<String, Object>)headerList_actualList.get(i);
            List<Object> cellList_actaul = (List<Object>)cell_actaul.get('cellList');

            for(Integer j=0; j<cellList_actaul.size(); j++) {
                Assert.areEqual(cellList_expect.get(j), cellList_actaul.get(j));
            }
        }

        // Check [bodyList]
        List<Object> bodyList_expectList = new List<Object>{
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,000kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'9,800,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>9800000, 'title'=>'ガス 屋内 三相 22,000V 6,600V 1,000kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TRガス"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'0'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,200kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'11,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>11100000, 'title'=>'ガス 屋内 三相 22,000V 6,600V 1,200kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TRガス"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'0'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,250kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'13,200,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>13200000, 'title'=>'ガス 屋内 三相 22,000V 6,600V 1,250kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TRガス"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'0'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'1,500kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'16,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>16100000, 'title'=>'ガス 屋内 三相 22,000V 6,600V 1,500kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TRガス"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'0'}
                }
            },
            new Map<String, List<Object>>{
                'cellList'=>new List<Object>{
                    new Map<String, Object>{'colSpanCnt'=>2, 'isColSpan'=>true, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'2,000kVA'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'20,100,000'},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>true, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>new Map<String, Object>{'id'=>'', 'isChecked'=>false, 'price'=>20100000, 'title'=>'ガス 屋内 三相 22,000V 6,600V 2,000kVA@@{"スポットネットワーク":"なし","OLTC":"なし","電圧仕様":"標準","GIS直結":"なし","設置場所":"屋内","screenType":"特高TRガス"}'}},
                    new Map<String, Object>{'colSpanCnt'=>null, 'isColSpan'=>false, 'isEdit'=>false, 'isRowSpan'=>false, 'rowSpanCnt'=>null, 'value'=>'0'}
                }
            }
        };           

        List<Object> bodyList_actualList = (List<Object>)res_actaulMap.get('bodyList');
        for(Integer i=0; i<bodyList_actualList.size(); i++) {
            Map<String, Object> cell_expect = (Map<String, Object>)bodyList_expectList.get(i);
            List<Object> cellList_expect = (List<Object>)cell_expect.get('cellList');
            Map<String, Object> cell_actaul = (Map<String, Object>)bodyList_actualList.get(i);
            List<Object> cellList_actaul = (List<Object>)cell_actaul.get('cellList');

            for(Integer j=0; j<cellList_actaul.size(); j++) {
                Map<String, Object> expect = (Map<String, Object>)cellList_expect.get(j);
                Map<String, Object> actaul = (Map<String, Object>)cellList_actaul.get(j);

                if(actaul.get('value') instanceof Map<string,object>) {
                    Assert.areEqual(expect.get('colSpanCnt'), actaul.get('colSpanCnt'));
                    Assert.areEqual(expect.get('isColSpan'), actaul.get('isColSpan'));
                    Assert.areEqual(expect.get('isRowSpan'), actaul.get('isRowSpan'));
                    Assert.areEqual(expect.get('rowSpanCnt'), actaul.get('rowSpanCnt'));
                    Assert.areEqual(expect.get('isEdit'), actaul.get('isEdit'));

                    Map<String, Object> expect_value = (Map<String, Object>)expect.get('value');
                    Map<String, Object> actaul_value = (Map<String, Object>)actaul.get('value');
                    Assert.areEqual(expect_value.get('Price'), actaul_value.get('Price'));
                    Assert.areEqual(expect_value.get('isChecked'), actaul_value.get('isChecked'));
                    Assert.areEqual(expect_value.get('title'), actaul_value.get('title'));
                } else {
                    Assert.areEqual(expect, actaul);
                }
            }
        }
    }

    @IsTest
    private static void getDetailsInputForExtraHighInfoCase4Test() {

        Device__c device = [SELECT Id, Quote__c FROM Device__c WHERE Name='Test Device Name 1' LIMIT 1];

        Boolean isInit = true;
        String deviceId = device.Id;
        String screenType = '1';
        String searchCondition1 = '1';
        String searchCondition2 = '2';
        String searchCondition3 = '0';
        String searchCondition4 = '0';
        String searchCondition5 = '0';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.getDetailsInputForExtraHighInfo(
            isInit,
            deviceId,
            screenType,
            searchCondition1,
            searchCondition2,
            searchCondition3,
            searchCondition4,
            searchCondition5
        );
        Test.stopTest();
        Map<String, Object> res_actaulMap = (Map<String, Object>)JSON.deserializeUntyped(res_actaul);

        System.debug('================Case4=================');

        String errorMsg = '';
        Boolean isNoData = true;

        String inputedId = null;
        String displayCondition = null;
        Decimal displayTotal = null;

        String displayLabel = null;
        
        List<Object> headerList = null;
        List<Object> bodyList = null;

    
        Assert.areEqual(errorMsg, res_actaulMap.get('errorMsg'));
        Assert.areEqual(isNoData, res_actaulMap.get('isNoData'));
        Assert.areEqual(inputedId, res_actaulMap.get('inputedId'));
        Assert.areEqual(displayCondition, res_actaulMap.get('displayCondition'));
        Assert.areEqual(displayTotal, res_actaulMap.get('displayTotal'));

        Assert.areEqual(displayLabel, res_actaulMap.get('displayLabel'));
        Assert.areEqual(headerList, res_actaulMap.get('headerList'));
        Assert.areEqual(bodyList, res_actaulMap.get('bodyList'));

        Assert.areEqual('1', res_actaulMap.get('screenType'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition1'));
        Assert.areEqual('2', res_actaulMap.get('searchCondition2'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition3'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition4'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition5'));
    }

    @IsTest
    private static void getDetailsInputForExtraHighInfoCase5Test() {

        Device__c device = [SELECT Id, Quote__c FROM Device__c WHERE Name='Test Device Name 2' LIMIT 1];
        PricingTable__c pricingTable = [SELECT Id, Name, RECNo__c,
                                                    MajorClassificationCode__c, 
                                                    MajorClassificationName__c, 
                                                    MinorClassificationCode__c, 
                                                    MinorClassificationName__c, 
                                                    CategoryCode__c,CategoryName__c,
                                                    Name1__c, Name2__c,Name3__c,Name4__c,Name5__c, Name6__c, Name7__c, Name8__c, Name9__c, Name10__c, 
                                                    BU__c, WC__c, Price__c, UniqueKey__c,ConditionForSearchformula__c,
                                                    Weight__c,DisplayName__c,detailedStatementText__c,SpecialSpecificationNo__c,
                                                    Note__c
                                                FROM PricingTable__c
                                                WHERE UniqueKey__c='筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,000kVA特高TR油入'
                                                LIMIT 1
                                            ];

        Boolean isInit = true;
        String deviceId = device.Id;
        String screenType = '1';
        String searchCondition1 = '2';
        String searchCondition2 = '2';
        String searchCondition3 = '1';
        String searchCondition4 = '1';
        String searchCondition5 = '1';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.getDetailsInputForExtraHighInfo(
            isInit,
            deviceId,
            screenType,
            searchCondition1,
            searchCondition2,
            searchCondition3,
            searchCondition4,
            searchCondition5
        );
        Test.stopTest();
        Map<String, Object> res_actaulMap = (Map<String, Object>)JSON.deserializeUntyped(res_actaul);

        System.debug('================Case5=================');
        
        String errorMsg = '';
        Boolean isNoData = true;

        String inputedId = pricingTable.Id;
        String displayCondition = '油 スポットネットワーク 屋外 三相 22,000V 6,600V 1,000kVA';
        Decimal displayTotal = 36100000;

        String displayLabel = null;
        
        List<Object> headerList = null;
        List<Object> bodyList = null;

    
        Assert.areEqual(errorMsg, res_actaulMap.get('errorMsg'));
        Assert.areEqual(isNoData, res_actaulMap.get('isNoData'));
        Assert.areEqual(inputedId, res_actaulMap.get('inputedId'));
        Assert.areEqual(displayCondition, res_actaulMap.get('displayCondition'));
        Assert.areEqual(displayTotal, res_actaulMap.get('displayTotal'));

        Assert.areEqual(displayLabel, res_actaulMap.get('displayLabel'));
        Assert.areEqual(headerList, res_actaulMap.get('headerList'));
        Assert.areEqual(bodyList, res_actaulMap.get('bodyList'));

        Assert.areEqual('1', res_actaulMap.get('screenType'));
        Assert.areEqual('2', res_actaulMap.get('searchCondition1'));
        Assert.areEqual('0', res_actaulMap.get('searchCondition2'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition3'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition4'));
        Assert.areEqual('1', res_actaulMap.get('searchCondition5'));
    }

    @IsTest
    private static void submitDetailsForExtraHighSuccessTest() {

        Device__c device = [SELECT Id, Quote__c FROM Device__c WHERE Name='Test Device Name 2' LIMIT 1];
        PricingTable__c pricingTable = [SELECT Id, Name, RECNo__c,
                                                    MajorClassificationCode__c, 
                                                    MajorClassificationName__c, 
                                                    MinorClassificationCode__c, 
                                                    MinorClassificationName__c, 
                                                    CategoryCode__c,CategoryName__c,
                                                    Name1__c, Name2__c,Name3__c,Name4__c,Name5__c, Name6__c, Name7__c, Name8__c, Name9__c, Name10__c, 
                                                    BU__c, WC__c, Price__c, UniqueKey__c,ConditionForSearchformula__c,
                                                    Weight__c,DisplayName__c,detailedStatementText__c,SpecialSpecificationNo__c,
                                                    Note__c
                                                FROM PricingTable__c
                                                WHERE UniqueKey__c='筐体S変圧器特高変圧器60Hz油屋内三相22,000V6,600V1,200kVA特高TR油入'
                                                LIMIT 1
                                            ];
        String deviceId = device.Id;
        String rId = pricingTable.Id;
        String cnt = '1';
        String title = '{"スポットネットワーク":"あり","OLTC":"あり","電圧仕様":"6,600V","GIS直結":"あり","設置場所":"屋外","screenType":"特高TR 油入"}';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.submitDetailsForExtraHigh(
            deviceId,
            rId,
            cnt,
            title
        );
        Test.stopTest();

        System.debug('================すべての明細　Delete=================');
        List<String> oldDetailList = new List<String>{
            '筐体S変圧器特高変圧器60Hz油 スポットネットワーク屋外三相22,000V6,600V1,000kVA特高TR油入',
            '明細S変圧器特高変圧器油GIS直結1,000kVA',
            '明細S変圧器特高変圧器油OLTC付'
        };
        List<Detail__c> oldDetails = [SELECT Id FROM Detail__c WHERE PricingTableUniqueKey__c IN:oldDetailList];
        Assert.areEqual(0, oldDetails.size());


        List<Detail__c> details = [SELECT Id
                                        ,Device__c
                                        ,Name
                                        ,Name1__c
                                        ,Name2__c
                                        ,Name3__c
                                        ,Name4__c
                                        ,PricingTableUniqueKey__c
                                        ,CreditWC__c
                                        ,UnitPrice__c
                                        ,CreditWeight__c
                                        ,DetailCategory__c
                                        ,Quantity__c
                                        ,WcCalculationRate__c
                                        ,Note__c
                                        ,Name5__c
                                        ,Name6__c
                                        ,Name7__c
                                        ,Name8__c
                                        ,Name9__c
                                        ,Name10__c
                                        ,detailedStatementText__c
                                        ,SpecialSpecificationNo__c
                                        ,MajorClassificationName__c
                                        ,MajorClassificationCode__c
                                        ,MinorClassificationName__c
                                        ,MinorClassificationCode__c
                                        ,CategoryName__c
                                        ,CategoryCode__c
                                    FROM Detail__c
                                    WHERE Device__c =:deviceId];
        
        Map<String, String> searchConditionMap = (Map<String, String>)JSON.deserialize(title, Map<String, String>.class);
        for(Detail__c detail : details) {
            if(detail.DetailCategory__c=='筐体') {
                System.debug('================筐体=================');
                Assert.areEqual(deviceId, detail.Device__c);
                Assert.areEqual(pricingTable.DisplayName__c, detail.Name);
                Assert.areEqual(pricingTable.Name1__c, detail.Name1__c);
                Assert.areEqual(pricingTable.Name2__c, detail.Name2__c);
                Assert.areEqual(pricingTable.Name3__c, detail.Name3__c);
                Assert.areEqual(pricingTable.Name4__c, detail.Name4__c);
                Assert.areEqual(pricingTable.UniqueKey__c, detail.PricingTableUniqueKey__c);
                Assert.areEqual(pricingTable.WC__c, detail.CreditWC__c);
                Assert.areEqual(pricingTable.Price__c, detail.UnitPrice__c);
                Assert.areEqual(pricingTable.Weight__c, detail.CreditWeight__c);
                Assert.areEqual('筐体', detail.DetailCategory__c);
                Assert.areEqual(1, detail.Quantity__c);
                Assert.areEqual(0, detail.WcCalculationRate__c);
                Assert.areEqual(pricingTable.Note__c, detail.Note__c);
                Assert.areEqual(pricingTable.Name5__c, detail.Name5__c);
                Assert.areEqual(pricingTable.Name6__c, detail.Name6__c);
                Assert.areEqual(pricingTable.Name7__c, detail.Name7__c);
                Assert.areEqual(pricingTable.Name8__c, detail.Name8__c);
                Assert.areEqual(pricingTable.Name9__c, detail.Name9__c);
                Assert.areEqual(pricingTable.Name10__c, detail.Name10__c);
                Assert.areEqual(pricingTable.detailedStatementText__c, detail.detailedStatementText__c);
                Assert.areEqual(pricingTable.SpecialSpecificationNo__c, detail.SpecialSpecificationNo__c);
                Assert.areEqual(pricingTable.MajorClassificationName__c, detail.MajorClassificationName__c);
                Assert.areEqual(pricingTable.MajorClassificationCode__c, detail.MajorClassificationCode__c);
                Assert.areEqual(pricingTable.MinorClassificationName__c, detail.MinorClassificationName__c);
                Assert.areEqual(pricingTable.MinorClassificationCode__c, detail.MinorClassificationCode__c);
                Assert.areEqual(pricingTable.CategoryName__c, detail.CategoryName__c);
                Assert.areEqual(pricingTable.CategoryCode__c, detail.CategoryCode__c);
            } else if(detail.Name2__c=='GIS直結') {
                System.debug('================GIS直結=================');
                PricingTable__c pricingTableGIS = [SELECT Id, Name, RECNo__c,
                                                                MajorClassificationCode__c, 
                                                                MajorClassificationName__c, 
                                                                MinorClassificationCode__c, 
                                                                MinorClassificationName__c, 
                                                                CategoryCode__c,CategoryName__c,
                                                                Name1__c, Name2__c,Name3__c,Name4__c,Name5__c, Name6__c, Name7__c, Name8__c, Name9__c, Name10__c, 
                                                                WC__c, WcCalculationRate__c, Price__c, UniqueKey__c,
                                                                Weight__c,DisplayName__c,detailedStatementText__c,SpecialSpecificationNo__c,
                                                                Note__c
                                                            FROM PricingTable__c
                                                            WHERE
                                                                RecordType.DeveloperName = :'Detail' AND
                                                                MajorClassificationName__c = :pricingTable.MajorClassificationName__c AND 
                                                                MinorClassificationName__c = :pricingTable.MinorClassificationName__c AND 
                                                                BU__c = :pricingTable.BU__c AND 
                                                                CategoryCode__c = '00' AND 
                                                                Name1__c =:'油' AND
                                                                Name2__c =:'GIS直結' AND
                                                                Name3__c =:pricingTable.Name6__c
                                                            LIMIT 1];

                                                            Assert.areEqual(deviceId, detail.Device__c);
                                                            Assert.areEqual(pricingTableGIS.DisplayName__c, detail.Name);
                                                            Assert.areEqual(pricingTableGIS.Name1__c, detail.Name1__c);
                                                            Assert.areEqual(pricingTableGIS.Name2__c, detail.Name2__c);
                                                            Assert.areEqual(pricingTableGIS.Name3__c, detail.Name3__c);
                                                            Assert.areEqual(pricingTableGIS.Name4__c, detail.Name4__c);
                                                            Assert.areEqual(pricingTableGIS.UniqueKey__c, detail.pricingTableUniqueKey__c);
                                                            Assert.areEqual(pricingTableGIS.WC__c, detail.CreditWC__c);
                                                            Assert.areEqual(pricingTableGIS.Price__c, detail.UnitPrice__c);
                                                            Assert.areEqual(pricingTableGIS.Weight__c, detail.CreditWeight__c);
                                                            Assert.areEqual('明細', detail.DetailCategory__c);
                                                            Assert.areEqual(1, detail.Quantity__c);
                                                            Assert.areEqual(pricingTableGIS.WcCalculationRate__c, detail.WcCalculationRate__c);
                                                            Assert.areEqual(pricingTableGIS.Note__c, detail.Note__c);
                                                            Assert.areEqual(pricingTableGIS.Name5__c, detail.Name5__c);
                                                            Assert.areEqual(pricingTableGIS.Name6__c, detail.Name6__c);
                                                            Assert.areEqual(pricingTableGIS.Name7__c, detail.Name7__c);
                                                            Assert.areEqual(pricingTableGIS.Name8__c, detail.Name8__c);
                                                            Assert.areEqual(pricingTableGIS.Name9__c, detail.Name9__c);
                                                            Assert.areEqual(pricingTableGIS.Name10__c, detail.Name10__c);
                                                            Assert.areEqual(pricingTableGIS.detailedStatementText__c, detail.detailedStatementText__c);
                                                            Assert.areEqual(pricingTableGIS.SpecialSpecificationNo__c, detail.SpecialSpecificationNo__c);
                                                            Assert.areEqual(pricingTableGIS.MajorClassificationName__c, detail.MajorClassificationName__c);
                                                            Assert.areEqual(pricingTableGIS.MajorClassificationCode__c, detail.MajorClassificationCode__c);
                                                            Assert.areEqual(pricingTableGIS.MinorClassificationName__c, detail.MinorClassificationName__c);
                                                            Assert.areEqual(pricingTableGIS.MinorClassificationCode__c, detail.MinorClassificationCode__c);
                                                            Assert.areEqual(pricingTableGIS.CategoryName__c, detail.CategoryName__c);
                                                            Assert.areEqual(pricingTableGIS.CategoryCode__c, detail.CategoryCode__c);
            } else if(detail.Name2__c=='OLTC付') {
                System.debug('================OLTC付=================');
                PricingTable__c pricingTableOLTC = [SELECT Id, Name, RECNo__c,
                                                                MajorClassificationCode__c, 
                                                                MajorClassificationName__c, 
                                                                MinorClassificationCode__c, 
                                                                MinorClassificationName__c, 
                                                                CategoryCode__c,CategoryName__c,
                                                                Name1__c, Name2__c,Name3__c,Name4__c,Name5__c, Name6__c, Name7__c, Name8__c, Name9__c, Name10__c, 
                                                                WC__c, WcCalculationRate__c, Price__c, UniqueKey__c,
                                                                Weight__c,DisplayName__c,detailedStatementText__c,SpecialSpecificationNo__c,
                                                                Note__c
                                                            FROM PricingTable__c
                                                            WHERE
                                                                RecordType.DeveloperName = :'Detail' AND
                                                                MajorClassificationName__c = :pricingTable.MajorClassificationName__c AND 
                                                                MinorClassificationName__c = :pricingTable.MinorClassificationName__c AND 
                                                                BU__c = :pricingTable.BU__c AND 
                                                                CategoryCode__c = :'00' AND 
                                                                Name1__c =:'油' AND
                                                                Name2__c =:'OLTC付'
                                                            LIMIT 1];

                                                            Assert.areEqual(deviceId, detail.Device__c);
                                                            Assert.areEqual(pricingTableOLTC.DisplayName__c, detail.Name);
                                                            Assert.areEqual(pricingTableOLTC.Name1__c, detail.Name1__c);
                                                            Assert.areEqual(pricingTableOLTC.Name2__c, detail.Name2__c);
                                                            Assert.areEqual(pricingTableOLTC.Name3__c, detail.Name3__c);
                                                            Assert.areEqual(pricingTableOLTC.Name4__c, detail.Name4__c);
                                                            Assert.areEqual(pricingTableOLTC.UniqueKey__c, detail.pricingTableUniqueKey__c);
                                                            Assert.areEqual(pricingTableOLTC.WC__c, detail.CreditWC__c);
                                                            Assert.areEqual(pricingTableOLTC.Price__c, detail.UnitPrice__c);
                                                            Assert.areEqual(pricingTableOLTC.Weight__c, detail.CreditWeight__c);
                                                            Assert.areEqual('明細', detail.DetailCategory__c);
                                                            Assert.areEqual(1, detail.Quantity__c);
                                                            Assert.areEqual(pricingTableOLTC.WcCalculationRate__c, detail.WcCalculationRate__c);
                                                            Assert.areEqual(pricingTableOLTC.Note__c, detail.Note__c);
                                                            Assert.areEqual(pricingTableOLTC.Name5__c, detail.Name5__c);
                                                            Assert.areEqual(pricingTableOLTC.Name6__c, detail.Name6__c);
                                                            Assert.areEqual(pricingTableOLTC.Name7__c, detail.Name7__c);
                                                            Assert.areEqual(pricingTableOLTC.Name8__c, detail.Name8__c);
                                                            Assert.areEqual(pricingTableOLTC.Name9__c, detail.Name9__c);
                                                            Assert.areEqual(pricingTableOLTC.Name10__c, detail.Name10__c);
                                                            Assert.areEqual(pricingTableOLTC.detailedStatementText__c, detail.detailedStatementText__c);
                                                            Assert.areEqual(pricingTableOLTC.SpecialSpecificationNo__c, detail.SpecialSpecificationNo__c);
                                                            Assert.areEqual(pricingTableOLTC.MajorClassificationName__c, detail.MajorClassificationName__c);
                                                            Assert.areEqual(pricingTableOLTC.MajorClassificationCode__c, detail.MajorClassificationCode__c);
                                                            Assert.areEqual(pricingTableOLTC.MinorClassificationName__c, detail.MinorClassificationName__c);
                                                            Assert.areEqual(pricingTableOLTC.MinorClassificationCode__c, detail.MinorClassificationCode__c);
                                                            Assert.areEqual(pricingTableOLTC.CategoryName__c, detail.CategoryName__c);
                                                            Assert.areEqual(pricingTableOLTC.CategoryCode__c, detail.CategoryCode__c);
            }
        }
        

        System.debug(res_actaul);
        //Assert.areEqual(res_expect, res_actaul);
    }

    @IsTest
    private static void submitDetailsForExtraHighErrorTest() {

        String deviceId = 'XXXXXXXXXXXXXXXXXXXXXXXX';
        String rId = 'XXXXXXXXXXXXXXXXXXXXXXXX';
        String cnt = 'XXXXXXXXXXXXXXXXXXXXXXXX';
        String title = 'XXXXXXXXXXXXXXXXXXXXXXXX';

        Test.startTest();
        String res_actaul = DetailsInputForExtraHighController.submitDetailsForExtraHigh(
            deviceId,
            rId,
            cnt,
            title
        );
        Test.stopTest();

        String res_expect = 'Error';
        Assert.areEqual(res_expect, res_actaul);
    }
}